force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
                <default>true</default>
                <label>Integration</label>
            </value>
            <value>
                <fullName>Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Valid_for_Retrial__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Retrial__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Valid for Retrial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Webservice_params__c.field-meta.xml
<CustomField>
    <fullName>Webservice_params__c</fullName>
    <label>Webservice params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Webservice_Request__c.field-meta.xml
<CustomField>
    <fullName>Webservice_Request__c</fullName>
    <label>Webservice Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FetchCustomerBillingGroups</fullName>
            </value>
            <value>
                <fullName>FetchBillingSOFs</fullName>
            </value>
            <value>
                <fullName>FetchProductSubscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FetchBackupandPowerTest.cls
@isTest(SeeAllData=true)
public class FetchBackupandPowerTest 
{

    @isTest static void positiveTest1()
    {
        Test.startTest();
		Integration_Message__c msg = new Integration_Message__c();
        msg.Webservice_Request__c='FetchProductSubscription';
        msg.Webservice_params__c='P000174,P000673,P000672';
        msg.Valid_For_Retrial__c=false;
        msg.Unique_Key__c= '12345';
        msg.Message_Type__c ='Integration';
        insert msg;  
        Test.stopTest();
        
        
    }

}