force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Sch_SCFContractsIntegration.cls
/*
*   Name        : Sch_SCFContractsIntegration
*   Description : Create Integration Job after SCF Process is done
*   Functions   : Create Integration Job after SCF Process is done
*   Author      : Nandish Shenoy
*   Create On   : 
*   |-------------------------------------------------------------------------|
*   | Version | Modified By      | Date       | Comment                       |
*   |-------------------------------------------------------------------------|
*   | 0.1     |                  |            | Initial Version of Class      |
*   |-------------------------------------------------------------------------|
*/  
public class Sch_SCFContractsIntegration implements Schedulable {
    
    public Set<Id> setOpportunityIds;

    public Sch_SCFContractsIntegration( set<Id> setOpportunityIds ) {
        this.setOpportunityIds = setOpportunityIds;
    }

    public void execute(SchedulableContext SC) {
        List<Integration_Message__c> lstMessages = new List<Integration_Message__c>();
        IntegrationBase iBase = new IntegrationBase();
        for(Opportunity objOpp : [Select Id, SBQQ__AmendedContract__c, (Select Id From SBQQ__Contracts__r) From Opportunity Where Id In :setOpportunityIds ]) {
            
            Id contractId = objOpp.SBQQ__AmendedContract__c;
            if( objOpp.SBQQ__AmendedContract__c == null ) {
                contractId = objOpp.SBQQ__Contracts__r[0].Id;
            }
            Integration_Message__c objMessage = new Integration_Message__c();
            objMessage = iBase.createIMRecord( null, contractId ,'', '', '','', '', '', false, IntegrationConstants.STR_CONTRACT_TEMPLATE_NAME);
            lstMessages.add( objMessage );
            objMessage.Unique_Key__c = contractId + '_' + IntegrationConstants.STR_CONTRACT_TEMPLATE_NAME + '_' + 'Pending';
        }    
        upsert lstMessages Unique_Key__c;
        Batch_Kill_IntegrationSCFJob batchJob = new Batch_Kill_IntegrationSCFJob();  
        batchJob.jobId = SC.getTriggerId();
        database.executeBatch( batchJob, 1 );
    }  
    
}