force-app/main/default/objects/ID__mdt/ID__mdt.object-meta.xml
<CustomObject>
    <description>IDs to be used in automations and codes</description>
    <label>ID</label>
    <pluralLabel>IDs</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem/fields/Dimension_Type__c.field-meta.xml
<CustomField>
    <fullName>Dimension_Type__c</fullName>
    <formula>SBQQ__QuoteLine__r.Dimension_Type__c</formula>
    <label>Dimension Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Expected_MRC__c.field-meta.xml
<CustomField>
    <fullName>Expected_MRC__c</fullName>
    <label>Expected Unit MRC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ExpectedARC__c.field-meta.xml
<CustomField>
    <fullName>ExpectedARC__c</fullName>
    <inlineHelpText>Annual Contract Value</inlineHelpText>
    <label>ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ExpectedOTC__c.field-meta.xml
<CustomField>
    <fullName>ExpectedOTC__c</fullName>
    <label>Expected Unit OTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Number_of_Months_Formula__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Months_Formula__c</fullName>
    <formula>Opportunity.Number_Of_Months__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Months Formula</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <formula>CASESAFEID(Opportunity.Pricebook2Id)</formula>
    <label>Pricebook Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quote_Line_Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Final_Unit_Price__c</fullName>
    <formula>SBQQ__QuoteLine__r.Final_Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Line Final Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Segment_Label__c.field-meta.xml
<CustomField>
    <fullName>Segment_Label__c</fullName>
    <formula>SBQQ__QuoteLine__r.SBQQ__SegmentLabel__c</formula>
    <label>Segment Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTriggerHandler.cls
public class OpportunityLineItemTriggerHandler extends TriggerHandler {
    public static boolean inFutureContext = false;
    
	public override void afterInsert() {
        if (!inFutureContext)
        	calculatePrices(new Map<Id, OpportunityLineItem>((List<OpportunityLineItem>) trigger.new).keySet());
    }

    public override void afterUpdate() {
        if (!inFutureContext)
            calculatePrices(new Map<Id, OpportunityLineItem>((List<OpportunityLineItem>) trigger.new).keySet());
    }
    
    @future
    public static void calculatePrices(Set<Id> optyLineItemIds) {
        inFutureContext = true;
        List<OpportunityLineItem> lstTriggerNew = [Select id, Pricebook_Id__c, Quantity, UnitPrice, Expected_MRC__c, ExpectedOTC__c, ExpectedARC__c,
                                                   Number_of_Months_Formula__c, Dimension_Type__c, Segment_Label__c, Quote_Line_Final_Unit_Price__c
                                                   from OpportunityLineItem where id in: optyLineItemIds];
        String  PreQuoteId = [SELECT Id__c FROM ID__mdt where MasterLabel = 'Pre-Quote'].Id__c;
        String StandardId = [SELECT Id__c FROM ID__mdt where MasterLabel = 'Standard'].Id__c;
        for (OpportunityLineItem line : lstTriggerNew) {
            if(line.Pricebook_Id__c == PreQuoteId){
                line.UnitPrice = 0;
                if(line.Expected_MRC__c == null)
                    line.UnitPrice = 0;
                else
                    line.UnitPrice = line.Expected_MRC__c * line.Number_of_Months_Formula__c;
                if(line.ExpectedOTC__c == null)
                    line.UnitPrice = line.UnitPrice;
                else
                    line.UnitPrice = line.UnitPrice + line.ExpectedOTC__c;
                //line.UnitPrice = (line.Expected_MRC__c == null? 0: line.Expected_MRC__c * line.Number_of_Months_Formula__c) + (line.ExpectedOTC__c == null? 0: line.ExpectedOTC__c);
            } else if(line.Pricebook_Id__c == StandardId){
                if(line.Dimension_Type__c == 'MRC'){
                    if(line.Segment_Label__c == 'Year  1'){
                        line.ExpectedOTC__c = 0;
                        line.Expected_MRC__c = line.Quote_Line_Final_Unit_Price__c;
                    } else{
                        line.ExpectedOTC__c = 0;
                        line.Expected_MRC__c = 0;
                    }
                } else if(line.Dimension_Type__c == 'OTC'){
                    line.ExpectedOTC__c = line.Quote_Line_Final_Unit_Price__c;
                    line.Expected_MRC__c = 0;
                } else if(line.Dimension_Type__c == 'VRC'){
                    
                }
                    
                
            }
            
            line.ExpectedARC__c = (((line.Expected_MRC__c == null ? 0 : line.Expected_MRC__c) * (line.Number_of_Months_Formula__c > 12 ? 12 : line.Number_of_Months_Formula__c)) + (line.ExpectedOTC__c == null ? 0 : line.ExpectedOTC__c)) * line.Quantity;
        }
        Update lstTriggerNew;
    }
}