force-app/main/default/objects/ContentVersion/fields/Public_URL__c.field-meta.xml
<CustomField>
    <fullName>Public_URL__c</fullName>
    <label>Public URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentVersionTriggerHandler.cls
/**
 * Created by yatishsalian on 27/06/22.
 */

public with sharing class ContentVersionTriggerHandler {

    public static boolean HandlerRecurrionVariable = false;

    public static void onAfterInsert(List<ContentVersion> triggerNew) {
        try {
            Map<Id, Id> contentDocumentIdVscontentVersionId = new Map<Id, Id>();
            for (ContentVersion cv :triggerNew) {
                if (cv.ContentDocumentId != null) {
                    //Map of contentDocumentId Vs contentVersionId
                    contentDocumentIdVscontentVersionId.put(cv.ContentDocumentId, cv.Id);
                }
            }
            system.debug('contentDocumentIdVscontentVersionId--' +
                    contentDocumentIdVscontentVersionId);

            if (contentDocumentIdVscontentVersionId.keySet() != null &&
                    contentDocumentIdVscontentVersionId.keySet().size() > 0) {
                //call future method to create new contentDistribution
                if(System.isFuture()){
                    createContentDistribution(contentDocumentIdVscontentVersionId);
                }
                else if(!System.isFuture()){
                    createContentDistributionFuture(contentDocumentIdVscontentVersionId);
                }
            }
        } catch (Exception e) {

            system.debug('Exception in ContentVersion trigger--' + e.getMessage() + ' At ' +
                    e.getLineNumber());
        }
    }

    public static void onAfterUpdate(List <ContentVersion> triggerNew, Map<Id, ContentVersion>
            triggerOldMap) {

        try {
            Map<Id, Id> contentDocumentIdVscontentVersionId = new Map<Id, Id>();
            for (ContentVersion cv :triggerNew) {
                if (cv.ContentDocumentId != null) {
                    //Map of contentDocumentId Vs contentVersionId
                    contentDocumentIdVscontentVersionId.put(cv.ContentDocumentId, cv.Id);
                }
            }
            system.debug('contentDocumentIdVscontentVersionId--' +
                    contentDocumentIdVscontentVersionId);

            if (contentDocumentIdVscontentVersionId.keySet() != null &&
                    contentDocumentIdVscontentVersionId.keySet().size() > 0) {
                //call future method to create new contentDistribution
                if(System.isFuture()){
                    createContentDistribution(contentDocumentIdVscontentVersionId);
                }
                else if(!System.isFuture()){
                    createContentDistributionFuture(contentDocumentIdVscontentVersionId);
                }
            }
        } catch (Exception e) {

            system.debug('Exception in ContentVersion trigger--' + e.getMessage() + ' At ' +
                    e.getLineNumber());
        }
    }

    public static void onAfterDelete(List<ContentVersion> triggerNew, Map<Id, ContentVersion>
            triggerOldMap) {
        /* call after delete actions */
    }

    public static void onBeforeInsert(List<ContentVersion> triggerNew) {}

    public static void onBeforeUpdate(List<ContentVersion> triggerNew, Map<Id, ContentVersion>
            triggerOldMap) {}

    public static void onBeforeDelete(List<ContentVersion> triggerOld, Map<Id, ContentVersion>
            triggerOldMap) {
        //call before delete actions
    }

    @Future
    public static void createContentDistributionFuture(Map<Id, Id> documentIdVsVersionId) {
        createContentDistribution(documentIdVsVersionId);
    }

    public static void createContentDistribution(Map<Id, Id> documentIdVsVersionId) {
        /*Document Object keyprefix*/
         Schema.DescribeSObjectResult r1 = Document__c.sObjectType.getDescribe();
         String DocumentPrefix = r1.getKeyPrefix();
         system.debug('DocumentPrefix--' + DocumentPrefix);
        /*Account Object keyprefix*/
         Schema.DescribeSObjectResult r2 = Account.sObjectType.getDescribe();
         String AccountPrefix = r2.getKeyPrefix();
         system.debug('AccountPrefix--' + AccountPrefix);
        /*Contact Object keyprefix*/
         Schema.DescribeSObjectResult r3 = Contact.sObjectType.getDescribe();
         String ContactPrefix = r3.getKeyPrefix();
         system.debug('ContactPrefix--' + ContactPrefix);
        /*Opportunity Object keyprefix*/
         Schema.DescribeSObjectResult r4 = Opportunity.sObjectType.getDescribe();
         String OpportunityPrefix = r4.getKeyPrefix();
         system.debug('OpportunityPrefix--' + OpportunityPrefix);
        /*Quote Object keyprefix*/
         Schema.DescribeSObjectResult r5 = SBQQ__Quote__c.sObjectType.getDescribe();
         String QuotePrefix = r5.getKeyPrefix();
         system.debug('QuotePrefix--' + QuotePrefix);
        /*Contract Object keyprefix*/
         Schema.DescribeSObjectResult r6 = Contract.sObjectType.getDescribe();
         String ContractPrefix = r6.getKeyPrefix();
         system.debug('ContractPrefix--' + ContractPrefix);
        

        Map<Id, Id> contentVersionIdVsLinkedEntityId = new Map<Id, Id>();
        Set<Id> contentDocumentIds = documentIdVsVersionId.keySet();

        //retrieve contentdocumentlink using contentdocumentId
        List<ContentDocumentLink> contentDocumentLink = [SELECT
                ContentDocumentId,Id,LinkedEntityId,ShareType FROM ContentDocumentLink WHERE
                ContentDocumentId = :contentDocumentIds];

        if (contentDocumentLink != null) {
            for (ContentDocumentLink cdl :contentDocumentLink) {
                system.debug('CDL--' + cdl);

                //check whether parent is EndeavorService's record or not
                // Need to be replaced with Document__C
                if (cdl.LinkedEntityId != null && (String.valueOf(cdl.LinkedEntityId).startsWith(DocumentPrefix) || String.valueOf(cdl.LinkedEntityId).startsWith(AccountPrefix) || String.valueOf(cdl.LinkedEntityId).startsWith(ContactPrefix) || String.valueOf(cdl.LinkedEntityId).startsWith(OpportunityPrefix) || String.valueOf(cdl.LinkedEntityId).startsWith(QuotePrefix)  || String.valueOf(cdl.LinkedEntityId).startsWith(ContractPrefix))) {

                    contentVersionIdVsLinkedEntityId.put(documentIdVsVersionId.get(cdl.ContentDocumentId),
                    cdl.LinkedEntityId);
                }
            }
        }
        system.debug('contentVersionIdVsLinkedEntityId--' + contentVersionIdVsLinkedEntityId);

        if (contentVersionIdVsLinkedEntityId.keySet() != null &&
                contentVersionIdVsLinkedEntityId.keySet().size() > 0) {
            List<ContentDistribution> contentDistributions = new List<ContentDistribution>();
            Map<Id, ContentVersion> contVersion = new Map<Id, ContentVersion>([select id, Title,
                    ContentDocumentId from ContentVersion where id in:contentVersionIdVsLinkedEntityId.keySet()]);
			List<ContentDistribution> listCD = [SELECT Id  FROM ContentDistribution WHERE ContentVersionId IN :contentVersionIdVsLinkedEntityId.keyset()];
            Map<Id, ContentDistribution> MapofCD = new Map<Id,ContentDistribution>();

            for (Id i: contentVersionIdVsLinkedEntityId.keySet()) {
                if(listCD.size() < 1){
                //create contentDistribution
                ContentDistribution cd = new ContentDistribution();
                cd.Name = contVersion.get(i).Title;
                cd.ContentVersionId = i;
                cd.RelatedRecordId = contentVersionIdVsLinkedEntityId.get(i);
                cd.PreferencesAllowOriginalDownload = true;
                cd.PreferencesAllowPDFDownload = true;
                cd.PreferencesAllowViewInBrowser = true;
                cd.PreferencesNotifyOnVisit = false;
                contentDistributions.add(cd);
                MapofCD.put(i,cd);
                system.debug('cd--' + cd);
                }
            }

            try {
                if (MapofCD.values().size() > 0) {
                    Database.insert(MapofCD.values(), false);
                    system.debug('contentDistributions--' + MapofCD.values());

                    //Get public document link and add that on dispensary record
                    List<ContentDistribution> conDist = [
                            SELECT DistributionPublicUrl, ContentDocumentId
                            FROM ContentDistribution
                            WHERE Id IN :MapofCD.values()
                    ];
                    List<ContentVersion> updateList = new List<ContentVersion>();
                    if (!conDist.isEmpty()) {
                        for (ContentDistribution cd : conDist) {
                            System.debug('Record Id:' + documentIdVsVersionId.containsKey(cd.ContentDocumentId));
                            if (documentIdVsVersionId.containsKey(cd.ContentDocumentId)) {
                                ContentVersion cv = new ContentVersion();
                                cv.Id = documentIdVsVersionId.get(cd.ContentDocumentId);
                                cv.Public_URL__c = cd.DistributionPublicUrl;

                                updateList.add(cv);
                            }
                        }
                        System.debug('##updateList :' + updateList);
                        if (!updateList.isEmpty()) {
                            ContentVersionTriggerHandler.HandlerRecurrionVariable = true;
                            Database.update(updateList, false);
                        }
                    }

                }
            }catch (Exception e){
                System.debug('Error Occured'+e.getLineNumber()+' === '+e.getMessage());
            }
    }
}

}