force-app/main/default/objects/Contract/fields/Additional_CC_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_CC_s_Email__c</fullName>
    <inlineHelpText>In case of multiple Id&apos;s use &apos;;&apos; as separator</inlineHelpText>
    <label>Additional CC&apos;s Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Customer Contact)</relationshipLabel>
    <relationshipName>Contracts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Is_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <label>Approved</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Variable_UOM__c.field-meta.xml
<CustomField>
    <fullName>Variable_UOM__c</fullName>
    <label>Variable UOM</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Variable_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hour</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>TB</fullName>
            </value>
            <value>
                <fullName>Mbps</fullName>
            </value>
            <value>
                <fullName>Tickets</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>Per Cubic Meter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Additional_CC_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_CC_s_Email__c</fullName>
    <inlineHelpText>In case of multiple Id&apos;s use &apos;;&apos; as separator</inlineHelpText>
    <label>Additional CC&apos;s Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Quotes (Bill To Address)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contracted__c.field-meta.xml
<CustomField>
    <fullName>Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Is_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Is_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PDF Generated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/No_of_days_per_month__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_per_month__c</fullName>
    <label>No of days per month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/No_of_hours_per_month__c.field-meta.xml
<CustomField>
    <fullName>No_of_hours_per_month__c</fullName>
    <label>No of hours per day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Quote #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Customer Accepted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Variable_Product_Count__c.field-meta.xml
<CustomField>
    <fullName>Variable_Product_Count__c</fullName>
    <label>Variable Product Count</label>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.Variable_Product__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Version</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>Used for Renewal Quotes</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/SCF.recordType-meta.xml
<RecordType>
    <fullName>SCF</fullName>
    <active>true</active>
    <description>Used for SCF/Amendment Quotes</description>
    <label>SCF</label>
</RecordType>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>CASESAFEID( SBQQ__Quote__r.SBQQ__Account__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Deactivation</fullName>
            </value>
            <value>
                <fullName>Facility Change</fullName>
            </value>
            <value>
                <fullName>Price Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Upgrade/Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Variable_UOM__c.field-meta.xml
<CustomField>
    <fullName>Variable_UOM__c</fullName>
    <formula>TEXT( SBQQ__Product__r.Variable_UOM__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variable UOM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateQuotePDFDocument.cls
public class GenerateQuotePDFDocument {
    public static Id fileId;
	public static String toEmail;
    public static ContentVersion file;
    public static String pdfName = '';

    public GenerateQuotePDFDocument() {

    }

    @AuraEnabled
	public static String pdfGenerationCheck(Id recordId, String pdfName) {
        SBQQ__Quote__c quote = [SELECT Id, SBQQ__Type__c,Bill_To_Address__c,Customer_Contact__c,	Variable_Product_Count__c ,No_of_days_per_month__c,No_of_hours_per_month__c, SCF_Type__c, Name, SBQQ__Status__c, Contracted__c, (SELECT Id, SCF_Type__c FROM SBQQ__LineItems__r WHERE SCF_Type__c = 'Transfer of Service') FROM SBQQ__Quote__c WHERE Id = : recordId];
        List<Sbqq__QuoteLine__c> quoteLineList = [Select SBQQ__Product__r.Variable_UOM__c from Sbqq__QuoteLine__c where SBQQ__Quote__c =:recordId];
        System.debug('quote.SBQQ__Status__c' + quote.SBQQ__Status__c);    
        System.debug('quote.Contracted__c' + quote.Contracted__c);
        System.debug('quote.SBQQ__Type__c' + quote.SBQQ__Type__c);
        for(Sbqq__QuoteLine__c quoteLine: quoteLineList){
			if(quoteLine.SBQQ__Product__r.Variable_UOM__c == 'Hour' && (quote.No_of_days_per_month__c == null || quote.No_of_hours_per_month__c == null) && quote.SBQQ__Type__c == 'Quote' ){ 
				throw new AuraHandledException('No. of days per month and No. of hours per day fields are required if variable product is involved in the quote.');
			}
            if(quote.Bill_To_Address__c == null || quote.Customer_Contact__c == null){
                 throw new AuraHandledException('Please fill Bill to Address and Customer Contact first.');
            }
		}
		if ((quote.SBQQ__Status__c == 'Approved' || quote.SBQQ__Status__c == 'Rejected' || quote.SBQQ__Status__c == 'Customer Accepted') && !quote.Contracted__c) {
			if(quote.SBQQ__Type__c == 'Amendment'){
				if(quote.SCF_Type__c == 'Address Change'){
					pdfName = 'SCFAddressChange';
				} else if(quote.SCF_Type__c == 'Bill Cycle Change'){
					pdfName = 'SCFBillCycleChange';
				} else if(quote.SCF_Type__c == 'Transfer of Service'){
					pdfName = 'SCFTransferOfService';
				} else if(quote.SCF_Type__c == 'Contract Line SCF'){
					pdfName = 'CombinedSCF';
				}
            }else if(quote.SBQQ__Type__c == 'Quote'){
                pdfName = 'SalesforceProposalTemplate';
			}else{
				pdfName = 'RenewalSCF';
			}
			
			System.debug('.....PDF NAme...' + pdfName);
        } else{
            if (!Test.isRunningTest()) { 
            throw new AuraHandledException('Cannot generate PDF until quote is approved.');
            }
        }

        return pdfName;
	}


	@AuraEnabled
	public static String SavePDFAsFile(Id recordId, String pdfName) {

		SBQQ__Quote__c quote = [SELECT Id, Name, Version__c, SBQQ__Account__c, Customer_Contact__r.Email,Is_PDF_Generated__c, Customer_Contact__c, Additional_CC_s_Email__c, Customer_Contact__r.Name FROM SBQQ__Quote__c WHERE Id = : recordId];

		if (quote.Version__c == null) {
			quote.Version__c = 0;
		}
		quote.Version__c = quote.Version__c + 1;		

        toEmail = quote.Customer_Contact__r.Email;
        
       	String pdfURL = '/apex/' + pdfName + '?id=' + RecordId;
		PageReference pdf = new PageReference(pdfURL);
		Blob pdfBody;

		if (Test.isRunningTest()) {
			pdfBody = blob.valueOf('Unit.Test');
		} else {
			pdfBody = pdf.getContent();
		}

		String currentDate = date.today().format();
        
        Document__c doc = new Document__c();
		//doc.Account__c = quote.SBQQ__Account__c;
        doc.Object__c = 'Quote';

        if(pdfName == 'SalesforceProposalTemplate'){
            doc.Document_Category__c = 'Quote';
            doc.Document__c = 'Proposal Quote';
            doc.Name = 'Proposal Quote';
        }else if(pdfName == 'CombinedSCF' || pdfName == 'SCFAddressChange' || pdfName == 'SCFBillCycleChange' || pdfName == 'SCFTransferOfService'){
            doc.Document_Category__c = 'SCF';
            doc.Document__c = 'SCF Quote';
            doc.Name = 'SCF Quote';
        }else{
			doc.Document_Category__c = 'Quote';
            doc.Document__c = 'Renewal Quote';
            doc.Name = 'Renewal Quote';
		}

		doc.Quote__c = RecordId;
		insert doc;

			quote.Is_PDF_Generated__c = true;
			update quote;

		file = new ContentVersion();
        file.VersionData = pdfbody;

        if(pdfName == 'SalesforceProposalTemplate'){
            file.title = quote.Name + 'Proposal' + 'V.' + quote.Version__c + '-' + currentDate + '.pdf';
		    file.pathOnClient =  quote.Name + 'Proposal' + 'V.' + quote.Version__c + '-' + currentDate + '.pdf';
        } else if(pdfName == 'CombinedSCF' || pdfName == 'SCFAddressChange' || pdfName == 'SCFBillCycleChange' || pdfName == 'SCFTransferOfService'){
            file.title = quote.Name + 'SCF' + 'V.' + quote.Version__c + '-' + currentDate + '.pdf';
		    file.pathOnClient =  quote.Name + 'SCF' + 'V.' + quote.Version__c + '-' + currentDate + '.pdf';
        } else{
            file.title = quote.Name + 'Renewal' + 'V.' + quote.Version__c + '-' + currentDate + '.pdf';
		    file.pathOnClient =  quote.Name + 'Renewal' + 'V.' + quote.Version__c + '-' + currentDate + '.pdf';
        }
		
		file.FirstPublishLocationId = doc.Id;
		insert file;
		
		ContentVersion c = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :file.Id];
		FileId = c.ContentDocumentId;

		//Update quote version
//		update quote;

		SaveQuotationWrapper  response = new SaveQuotationWrapper(FileId , toEmail);
		return JSON.serialize(response);
	}

	@AuraEnabled
	public static void sendEmail(Id recordId, String pdfName) {
		SavePDFAsFile(recordId, pdfName);
        SBQQ__Quote__c quote = [SELECT id, Customer_Contact__c, Additional_CC_s_Email__c, Customer_Contact__r.Email, Customer_Contact__r.Name FROM SBQQ__Quote__c WHERE Id = : recordId];
        
       // if(quote.Customer_Contact__c == '' || quote.Customer_Contact__c == NULL){
        if(quote.Customer_Contact__c == NULL){
            if (!Test.isRunningTest()) { 
            throw new AuraHandledException('Please specify Customer Contact.');
            }
        }

		String[] toRecipients = new List<String> {quote.Customer_Contact__r.Email};
		String[] ccRecipients = new List<String>();
        if(quote.Additional_CC_s_Email__c != NULL){
            ccRecipients = quote.Additional_CC_s_Email__c.split(';');
        }

		EmailTemplate emailTemplate = [SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body FROM EmailTemplate WHERE name = 'QuoteProposal'];
		String templateId = emailTemplate.Id ;

		ID targetObjId = quote.Customer_Contact__c;
		ID whatId = quote.id;

		String currentUserName = quote.Customer_Contact__r.Name;
        String currentUserEmail = quote.Customer_Contact__r.Email;

        /*String pdfURL = '/apex/' + pdfName + '?id=' + recordId;
		PageReference pdf = new PageReference(pdfURL);
		Blob pdfBody;

		if (Test.isRunningTest()) {
			pdfBody = blob.valueOf('Unit.Test');
		} else {
			pdfBody = pdf.getContent();
		}*/


		System.debug('calling send template email');
		sendTemplatedEmail(toRecipients, ccRecipients, templateId, targetObjId, whatId, currentUserName, currentUserEmail);
	}

	public static void sendTemplatedEmail(String[] toRecipients, String[] ccRecipients, String templateId, ID targetObjId, Id whatId,
	                                      String currentUserName, String currentUserEmail) {

		System.debug('inside send template email');
		Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

		/* Set Recipients Address */
		email.setToAddresses(toRecipients);

		/* Set CC Recipients Address */
		if(ccRecipients.size() > 0){
			email.setccAddresses(ccRecipients);
		}

		/* Set Contact ID here */
		email.setTargetObjectId(targetObjId);

		/* Replay to Address*/
		email.setReplyTo(currentUserEmail);

		/* Set Sender Display Name */
		email.setSenderDisplayName(currentUserName);

		/* Set Current Object ID for merge fields */
		email.setWhatId(whatId);

		/*Set Template ID coming from Custom Setting Named "EmailTemplateSetting__c" */
		email.setTemplateId(templateId);

		List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();

		//   for (Attachment a : attachList) {
		Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
		efa.setFileName(file.title);
		efa.setBody(file.VersionData);
		fileAttachments.add(efa);
		// }

		email.setFileAttachments(fileAttachments);
		//  }

		/* Set this email log under Activity History */
		email.setSaveAsActivity(true);

		try {
			Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});

			if (results.get(0).isSuccess()) {
				system.debug('Email has been send :  ' + results);
			} else {
				system.debug('Some error in sending email :  ' + results );
			}
		} catch (EmailException e) {
			System.debug('sendTemplatedEmail related errors in Quotation PDF :  ' + e.getMessage());
		}
	}

	public class  SaveQuotationWrapper {
		Id fileId;
        String emailRecipient;
        
		public SaveQuotationWrapper(Id fileId, String emailRecipient) {
			this.fileId = fileId;
			this.emailRecipient = emailRecipient;
		}
	}
}