force-app/main/default/objects/Contract/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Ship To Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <label>Approved</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/Draft.recordType-meta.xml
<RecordType>
    <fullName>Draft</fullName>
    <active>true</active>
    <label>Draft</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/SupportTo__c.field-meta.xml
<CustomField>
    <fullName>SupportTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SupporttoCustomerName__c.field-meta.xml
<CustomField>
    <fullName>SupporttoCustomerName__c</fullName>
    <label>Support to Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/About_Yotta_Summary_Type__c.field-meta.xml
<CustomField>
    <fullName>About_Yotta_Summary_Type__c</fullName>
    <label>About Yotta Summary Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brief</fullName>
            </value>
            <value>
                <fullName>Detailed</fullName>
                <default>true</default>
                <label>Detailed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contracted__c.field-meta.xml
<CustomField>
    <fullName>Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SCF_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>SCF_Approval_Status__c</fullName>
    <label>SCF Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
                <isActive>false</isActive>
                <label>Approval Required</label>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <isActive>false</isActive>
                <label>Not Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <inlineHelpText>Please use font size of 10</inlineHelpText>
    <label>Scope of Work</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Yotta_s_Certifications_Required__c.field-meta.xml
<CustomField>
    <fullName>Yotta_s_Certifications_Required__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Yotta’s Certifications Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Yotta_s_Customers_Required__c.field-meta.xml
<CustomField>
    <fullName>Yotta_s_Customers_Required__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Yotta’s Customers Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Yotta_s_Products_and_Services_Required__c.field-meta.xml
<CustomField>
    <fullName>Yotta_s_Products_and_Services_Required__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Yotta’s Products and Services Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>Used for Renewal Quotes</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/GenerateRenewalContractBatchTest.cls
@isTest 
public class GenerateRenewalContractBatchTest {
    
    static testMethod void testMethod1() 
    {
        //try{
        Account account = new Account();
        account.Name = 'Test Account-' + String.valueOf(System.now().getTime());
        account.Type = 'Prospect';
        insert account;
        
        List<Opportunity> opportunityList = TestDataFactory.createOpportunity(1,account.Id);
//        opportunityList[0].SupporttoCustomerName__c=account.Name;
        insert opportunityList;        
        
        System.debug('Id.valueOf(opportunityList.Id)' + Id.valueOf(opportunityList[0].Id));
        
        Sbqq__Quote__c quote = new Sbqq__Quote__c (Quote_Name__c = 'Test'  , SBQQ__Account__c = account.Id,
                                                   SBQQ__StartDate__c=System.today(),SBQQ__EndDate__c =System.today().addYears(1), SBQQ__SubscriptionTerm__c = 24,
                                                   Currency_Conversion_Factor__c =1,sbqq__Primary__c = true,
                                                   About_Yotta_Summary_Type__c = 'Detailed',Yotta_s_Products_and_Services_Required__c ='Yes',
                                                   Yotta_s_Certifications_Required__c = 'Yes',Yotta_s_Customers_Required__c = 'Yes',
                                                   SBQQ__Opportunity2__c= Id.valueOf(opportunityList[0].Id),
                                                   Scope_of_Work__c ='scope od work');
        insert quote;
        
        Sbqq__Quote__c quote1 = new Sbqq__Quote__c (Quote_Name__c = 'Test'  , SBQQ__Account__c = account.Id,
                                                    SBQQ__StartDate__c=System.today(),SBQQ__EndDate__c =System.today().addYears(1), SBQQ__SubscriptionTerm__c = 24,
                                                    Currency_Conversion_Factor__c =1,
                                                    About_Yotta_Summary_Type__c = 'Detailed',Yotta_s_Products_and_Services_Required__c ='Yes',
                                                    Yotta_s_Certifications_Required__c = 'Yes',Yotta_s_Customers_Required__c = 'Yes',
                                                    SBQQ__Opportunity2__c= Id.valueOf(opportunityList[0].Id),
                                                    Scope_of_Work__c ='scope od work');
        insert quote1;
              
        Contract contract = new Contract(Status = 'Draft' , AccountId = account.Id,     CurrencyIsoCode = 'INR',SBQQ__Opportunity__c = Id.valueOf(opportunityList[0].Id),
                                         Business_Unit__c='IN10',SBQQ__AmendmentStartDate__c =Date.newInstance(2019,05,28) ,SBQQ__Quote__c = quote1.Id,ContractTerm = 1,
                                         StartDate= system.today().addDays(2).addmonths(-1),Support_To_Account__c = account.Id,Renewal_Type__c = 'Auto',SBQQ__RenewalForecast__c = false,SBQQ__RenewalQuoted__c = false);
        //contract.Support_To_Account__c = contract.AccountId;
        insert contract;
        

        Contract contract1 = new Contract(Status = 'Draft' , AccountId = account.Id,     CurrencyIsoCode = 'INR',SBQQ__Opportunity__c = Id.valueOf(opportunityList[0].Id),
                                         Business_Unit__c='IN10',SBQQ__AmendmentStartDate__c =Date.newInstance(2019,05,28) ,SBQQ__Quote__c = quote1.Id,ContractTerm = 1,
                                         StartDate= system.today().addDays(1).addmonths(-1),Renewal_Type__c = 'Auto',Support_To_Account__c = account.Id,SBQQ__RenewalForecast__c = false,SBQQ__RenewalQuoted__c = false);
        //contract1.Support_To_Account__c = contract1.AccountId;
        insert contract1;
        

        contract1.Status = 'Approved';
        update contract1;
        contract1.Status = 'Activated';
        update contract1;
        Set<Id> OpportunityId = new Set<Id>();
        System.debug('contract.EndDate'+contract.EndDate);
        for(Opportunity opp: opportunityList){
            opp.SBQQ__RenewedContract__c = contract.Id;
            opp.SupportTo__c = account.Id;
            opp.SupporttoCustomerName__c = 'Test Account';
            OpportunityId.add(opp.Id);
        }
        update opportunityList;
        
        
        // quote.SBQQ__MasterContract__c = contract.Id;
        quote.SBQQ__Type__c = 'Renewal';
        quote.Contracted__c = False;
        quote.SCF_Approval_Status__c = 'Approved';
        update quote;
        
        Set<Id> contractIdset = new Set<Id>();
        ContractIdset.add(contract.Id);
            try{
        Test.startTest();
        
        List<sbqq__quote__c> quoteList = [Select Id,SBQQ__Type__c,SBQQ__StartDate__c,SBQQ__Primary__c,Contracted__c,SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.Renewal_Type__c from sbqq__quote__c where sbqq__type__c = 'Renewal'];
        
        GenerateRenewalContractBatch d = new GenerateRenewalContractBatch(null);
        Database.executeBatch(d);
        List<Contract> conList = [Select Id,Status,Renewal_Type__c,SBQQ__RenewalForecast__c,SBQQ__RenewalQuoted__c,EndDate from Contract];
                System.debug('conList:  '+conList);
        
        RenewContractsBatch a = new RenewContractsBatch(null);
        Database.executeBatch(a);
        
       	RenewContractsBatch c = new RenewContractsBatch(conList[1].id);
        Database.executeBatch(c);
        ExpireContractBatch b = new ExpireContractBatch();
        Database.executeBatch(b);

        ExpireContractBatchScheduler sh1 = new ExpireContractBatchScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, sh1 );
        
        ContractQuantitySplitHandler apc = new ContractQuantitySplitHandler(contractIdset, true);
                
		ContractQuantitySplitHandler apc1 = new ContractQuantitySplitHandler(contractIdset);


          Id jobId =  System.enqueueJob(apc);

          Id jobIdContract = System.enqueueJob(new GenerateContractQueueable(OpportunityId));
         AsyncExecutionSCF1 async = new AsyncExecutionSCF1(jobId,2);
         System.enqueueJob(async);
          
        
        
        Test.stopTest();
        }catch(Exception e){
            System.assertEquals(true, e.getMessage().contains('Support To details are Mandatory'));
        }
    }
    @isTest
    public static void GenContractTest1(){
                
        Test.startTest();
        try{
        GenerateRenewalContractScheduler sh1 = new GenerateRenewalContractScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, sh1 );
        }catch(Exception e){
 			System.assertEquals(true, e.getMessage().contains('Support To details are Mandatory'));           
        }
        Test.stopTest();
    }
    
     @isTest
    public static void RenewContractTest1(){
                
        Test.startTest();
        try{
        RenewContractsScheduler sh1 = new RenewContractsScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, sh1 );
        }catch(Exception e){
 			System.assertEquals(true, e.getMessage().contains('Support To details are Mandatory'));           
        }
        Test.stopTest();
    }
    
}