force-app/main/default/objects/Contract/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
            <value>
                <fullName>DEL</fullName>
                <isActive>false</isActive>
                <label>DEL</label>
            </value>
            <value>
                <fullName>IN13</fullName>
                <isActive>false</isActive>
                <label>Navi Mumbai – DC2</label>
            </value>
            <value>
                <fullName>IN22</fullName>
                <isActive>false</isActive>
                <label>YNS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <isActive>false</isActive>
                <label>YNS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN23</fullName>
                <isActive>false</isActive>
                <label>YNS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN21</fullName>
                <isActive>false</isActive>
                <label>YNS Mumbai – HO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>Used for Renewal Quotes</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Component_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Component_Quantity__c</fullName>
    <label>Quantity/Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Dimension_Type__c.field-meta.xml
<CustomField>
    <fullName>Dimension_Type__c</fullName>
    <formula>TEXT(SBQQ__Dimension__r.Dimension_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <defaultValue>&quot;Navi Mumbai – DC1&quot;</defaultValue>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <default>true</default>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Monthly_Price__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Price__c</fullName>
    <formula>Final_Unit_Price__c * SBQQ__Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Deactivation</fullName>
            </value>
            <value>
                <fullName>Facility Change</fullName>
            </value>
            <value>
                <fullName>Price Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Upgrade/Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <formula>TEXT(SBQQ__Product__r.Unit_of_Measurement__c)</formula>
    <label>UOM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RenewalReminderController.cls
/* ****************************************************************************************************************
Name          : RenewalReminderController
Description   : It is used for RenewalReminder email template to fetch required data from Contract 
on Contract
Author        : Riya Sharma(Compro Technologies)

**************************************************************************************************************** */
global without sharing class RenewalReminderController {

    
   
    global String quoteId{get;set;}
    global String businessUnit{get;set;}
    
    //This function is used to return the product values required in renewal reminder email template
    global Map<String, RenewalRemWrapper.ParentWrapper> QuoteLines{ get{   
        
        // quoteId = ApexPages.currentPage().getParameters().get('id');
        
       // System.debug('quoteId' + quoteId);
        List<SBQQ__QuoteLine__c> quoteLineItems = [Select id,toLabel(Location__c),SBQQ__NetPrice__c,SBQQ__Quote__r.SBQQ__EndDate__c,SBQQ__Quote__r.SBQQ__StartDate__c,Monthly_Price__c,
                                                   toLabel(SBQQ__Product__r.Family),SBQQ__Product__r.Name,SBQQ__Quantity__c,SBQQ__QuoteLine__c.SBQQ__ProductName__c,
                                                   SBQQ__QuoteLine__c.UOM__c,SBQQ__Dimension__r.Dimension_Type__c,SBQQ__Product__c ,Component_Quantity__c,
                                                   SBQQ__Dimension__r.Name,SBQQ__NetTotal__c,SBQQ__RequiredBy__c,SBQQ__OriginalQuoteLineId__c,
                                                   SBQQ__Number__c,Bundle_Description__c,SBQQ__Quote__r.Currency_Conversion_Factor__c from SBQQ__QuoteLine__c where
                                                   SBQQ__Quote__c = :quoteId AND Business_Unit__c = : businessUnit AND SCF_Type__c != 'Deactivation' AND
                                       SCF_Type__c != 'Cancellation' AND SBQQ__Quantity__c != 0];
        
        
        
        //System.debug('quoteLineItems'+quoteLineItems);
        RenewalRemWrapper.ParentWrapper parentWrap; //parent wrapper instance ;
        RenewalRemWrapper.ProductWrapper prodWrap; //child wrapper instance
        Map<String, RenewalRemWrapper.ParentWrapper> parentWrapMap = new Map<String, RenewalRemWrapper.ParentWrapper>();
        Map<String,RenewalRemWrapper.ParentWrapper> productWrapRevMap = new Map<String,RenewalRemWrapper.ParentWrapper>(); 
        
        Map<String,RenewalRemWrapper.ProductWrapper> prodWrapRevMap = new Map<String,RenewalRemWrapper.ProductWrapper>(); 
        integer count = 1;
        Set<String> productSet = new Set<String>();
        Id originalQuoteLine; 
        
        //This function sets the values for the parentWrap that includes the field on quote where required by is null thus indicating
        //parent quoteLine
        for(SBQQ__QuoteLine__c qtl: quoteLineItems){
            
        System.debug('SBQQ__Product__r.Family' +  qtl.SBQQ__Product__r.Family);
            if (qtl.SBQQ__RequiredBy__c == null){
                originalQuoteLine = qtl.SBQQ__OriginalQuoteLineId__c;
                parentWrap = new RenewalRemWrapper.ParentWrapper();   
                System.debug('originalQuoteLine'+originalQuoteLine);
                // This gets the originalQuoteLine's values which existed before the new quoteine was made
                List<SBQQ__QuoteLine__c> originalquoteLineList = [Select Location__c from SBQQ__QuoteLine__c where id=:originalQuoteLine];
                for(SBQQ__QuoteLine__c quoteLine : originalquoteLineList){
                    parentWrap.deliveryLocationRev = quoteLine.Location__c;
                    System.debug('quoteLine.Location__c' + quoteLine.Location__c);
                }
                                 
                parentWrap.Qty =qtl.sbqq__Quantity__c;
                parentWrap.productName = qtl.SBQQ__ProductName__c;
                parentWrap.productFamily = qtl.SBQQ__Product__r.Family;
                parentWrap.UOM = qtl.UOM__c;
                parentWrap.deliveryLocation = qtl.Location__c;
                parentWrap.productDescription = qtl.Bundle_Description__c;
                prodWrap = new RenewalRemWrapper.ProductWrapper();
                prodWrap.quoteLine = qtl;
                parentWrap.refNo = count;count++;
                //this gets the child quotelines values in a map and stores this quoteline values in wrapper
                parentWrap.bundleProductWrapperMap.put(qtl.Id, prodWrap);
                parentWrapMap.put(qtl.Id, parentWrap);
                productWrapRevMap.put(qtl.SBQQ__Product__c,parentWrap);
            }      
        }
        
        //This function sets the values for the childwrap that includes the field on quote where required by is not null 
        //but the id of the parent quoteLine
        for(SBQQ__QuoteLine__c qtl: quoteLineItems){
            if (qtl.SBQQ__RequiredBy__c != null ){
                if(parentWrapMap.containsKey(qtl.SBQQ__RequiredBy__c)){
                    parentWrap = parentWrapMap.get(qtl.SBQQ__RequiredBy__c);
                    prodWrap = parentWrap.bundleProductWrapperMap.get(qtl.SBQQ__RequiredBy__c);
                    
                    prodWrap.quoteLine = qtl;
                    
                    originalQuoteLine = qtl.SBQQ__OriginalQuoteLineId__c;
                    
                    // This gets the originalQuoteLine's values which existed before the new quoteine was made
                    List<SBQQ__QuoteLine__c> originalquoteLineList = [Select SBQQ__NetTotal__c from SBQQ__QuoteLine__c where id=:originalQuoteLine];
                    for(SBQQ__QuoteLine__c quoteLine : originalquoteLineList){
                        if(qtl.SBQQ__Dimension__r.Dimension_Type__c == 'MRC'){
                            prodWrap.mrcRevTotal =prodWrap.mrcRevTotal+ (quoteLine.Monthly_Price__c * quoteLine.SBQQ__Quote__r.Currency_Conversion_Factor__c);
                            
                            System.debug('prodWrap.mrcRevTotal' + prodWrap.mrcRevTotal);
                        }
                        if(qtl.SBQQ__Dimension__r.Dimension_Type__c == 'OTC'){
                            prodWrap.otcRevTotal =prodWrap.otcRevTotal+  (quoteLine.Monthly_Price__c * quoteLine.SBQQ__Quote__r.Currency_Conversion_Factor__c);
                            System.debug('prodWrap.otcRevTotal' + prodWrap.otcRevTotal);
                        }
                        else If(qtl.SBQQ__Dimension__r.Dimension_Type__c == 'VRC'){
                            prodWrap.vrcRevCharge = prodWrap.vrcRevCharge +  (quoteLine.Monthly_Price__c * quoteLine.SBQQ__Quote__r.Currency_Conversion_Factor__c);
                        } 
                    }
                    
                    prodWrap.productName = qtl.SBQQ__ProductName__c;
                    prodWrap.refNo = count;count++;
                    
                        
                        System.debug('qtl.SBQQ__Product__r.Name'+qtl.SBQQ__Product__r.Name);
                     
                    prodWrap.qty= qtl.SBQQ__Quantity__c;
                    prodWrap.UOM = qtl.UOM__c;
                    if(qtl.SBQQ__Dimension__r.Dimension_Type__c == 'MRC'){
                        prodWrap.mrcTotal =prodWrap.mrcTotal+ (qtl.Monthly_Price__c * qtl.SBQQ__Quote__r.Currency_Conversion_Factor__c);
                    }
                    if(qtl.SBQQ__Dimension__r.Dimension_Type__c == 'OTC'){
                        prodWrap.otcTotal =prodWrap.otcTotal+ (qtl.Monthly_Price__c * qtl.SBQQ__Quote__r.Currency_Conversion_Factor__c);
                    }
                    else If(qtl.SBQQ__Dimension__r.Dimension_Type__c == 'VRC'){
                        prodWrap.vrcCharge = prodWrap.vrcCharge +(qtl.Monthly_Price__c * qtl.SBQQ__Quote__r.Currency_Conversion_Factor__c);
                    }
                    
                    prodWrapRevMap.put(qtl.SBQQ__Product__c,prodWrap);
                    
                }   
                
            }
            prodWrapRevMap.put(qtl.sbqq__product__c,prodWrap);
            
        }
        
        // returnd wrapper class for all quotelines
        return parentWrapMap;
        
        
    }set;}
    
}