force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Last_Quote__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Last Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Lastest_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Lastest_Quote_Type__c</fullName>
    <formula>TEXT( Last_Quote__r.SBQQ__Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latest Quote Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ContractQuantitySplitHandler.cls
/* ****************************************************************************************************************
Name          : ContractQuantitySplitHandler
Description   : ContractQuantitySplitHandler Apex Queueable Class function is to split Subscription Quantity
                
Author        : Himanshu Maheshwari (Compro Technologies)
Creation Date : 13-November-2020
**************************************************************************************************************** */
public class ContractQuantitySplitHandler implements Queueable{
    public Set<Id> contractIdSet;
    public Boolean executeGenerateBillingGroup;
    
    public ContractQuantitySplitHandler(Set<Id> contractIdSet, Boolean executeGenerateBillingGroup) {
        this.contractIdSet = contractIdSet;
        this.executeGenerateBillingGroup = executeGenerateBillingGroup;
    }
    public ContractQuantitySplitHandler(Set<Id> contractIdSet){
        this.contractIdSet = contractIdSet;
        this.executeGenerateBillingGroup = false;
    }

    public void execute(QueueableContext context) {
        Map<Id, Contract> contractSCFMap = new Map<Id, Contract>([SELECT Id, Lastest_Quote_Type__c, Last_Quote__c, Last_Quote__r.SBQQ__Type__c, Contract_Number__c FROM Contract WHERE Id IN: contractIdSet]);
        ContractTriggerHandler.SplitSubscriptionQuantity(contractSCFMap);

        if(executeGenerateBillingGroup){
            BillingGroupHandler.generateBillingGroup(contractSCFMap.values());
        }
    }
    //System.enqueueJob(new SCFBillingGroupQueueableHandler(billingGrpContractIdSet));
}