force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Identity Proof</fullName>
            </value>
            <value>
                <fullName>Address Proof</fullName>
            </value>
            <value>
                <fullName>Additional/Optional Documents</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SCF</fullName>
                <label>Service Change Form</label>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Parent_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Name__c</fullName>
    <label>Parent Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Request_Envelope__c.field-meta.xml
<CustomField>
    <fullName>Request_Envelope__c</fullName>
    <label>Request Envelope</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Response_Envelope__c.field-meta.xml
<CustomField>
    <fullName>Response_Envelope__c</fullName>
    <label>Response Envelope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Batch_ContractDocumentsKafkaIntegration.cls
/*
*   Name        : Batch_ContractDocumentsKafkaIntegration
*   Description : Handles Document integration outside the Integration Framework
*   Author      : Nandish Shenoy
*   Create On   : 03 July 2020
*   |-------------------------------------------------------------------------|
*   | Version | Modified By      | Date       | Comment                       |
*   |-------------------------------------------------------------------------|
*   | 0.1     | Nandish          | 03/07/2020 | Initial Version of Class      |
*   |-------------------------------------------------------------------------|
*/
public class Batch_ContractDocumentsKafkaIntegration implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    public set<Id> setIdIntegratioMessage ;
    public List<Integration_Message__c> lstIntegrationMessages ;
    public Boolean isRetrialBatch = false;

    public Batch_ContractDocumentsKafkaIntegration(set<Id> setIdIntegrationMessage) {
        setIdIntegratioMessage = setIdIntegrationMessage;
        lstIntegrationMessages = new List<Integration_Message__c>();
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Set<Id> setIMIds = new Set<Id>(setIdIntegratioMessage);
        return Database.getQueryLocator('Select Id, Document__c, Contract__c ,Parent_Template_Name__c, Integration_Status__c, Name, Contract__r.Contract_Number__c FROM Integration_Message__c Where Id In :setIMIds');
    }

    public void execute(Database.BatchableContext bc, List<Integration_Message__c> scope) {
        Integration_Message__c objMsg = scope[0];
        List<Document__c> lstDocument = [SELECT Id, Name, Quote__c, Document_Category__c FROM Document__c WHERE Id = :objMsg.Document__c ];
        List<ContentDocumentLink> lstCDLink = [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink Where LinkedEntityId= :objMsg.Document__c ORDER BY Id DESC LIMIT 1];
        Id idCDId = lstCDLink[0].ContentDocumentId;
        List<ContentVersion> lstVersion = [SELECT VersionData, PathOnClient, FileExtension FROM ContentVersion WHERE ContentDocumentId = :idCDId AND IsLatest = true];
        
        DocumentWrapper objWrapper = new DocumentWrapper();
        objWrapper.docDetails = lstDocument[0];
        objWrapper.payload = EncodingUtil.base64Encode(lstVersion[0].VersionData);
        objWrapper.contractId = objMsg.Contract__r.Contract_Number__c;
        objWrapper.fileName = lstVersion[0].PathOnClient;

        //List<String> extensionSplit = objWrapper.fileName.split('\\.');
        //String extension = extensionSplit[extensionSplit.size() - 1];

        objWrapper.fileFormat = lstVersion[0].FileExtension;

        //String access_token = (new IntegrationBase()).getAuthorizationToken( Label.Kafka_Integration_Document_Authorization );
        HttpResponse res = (new IntegrationBase()).getAuthorizationToken( Label.Kafka_Integration_Document_Authorization );
        if( res.getStatusCode() == 200 || res.getStatusCode() == 201 ) {
            IntegrationBase.kafkaAuthToken token = (IntegrationBase.kafkaAuthToken)JSON.deserialize(res.getBody(), IntegrationBase.kafkaAuthToken.class);
            String access_token = token.access_token;
            HttpRequest req = new HttpRequest();
            Http mHttp = new Http();
            String resp = JSON.serialize(objWrapper);
            req.setMethod('POST'); 
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setHeader('Authorization', 'Bearer ' + access_token);
            req.setEndpoint(Label.Kafka_Integration_Document_Topic);
            req.setBody( resp );
            req.setTimeout(120000);
            HttpResponse response ;
            if(System.Test.isRunningTest()){
                response = new HttpResponse();
                response.setStatusCode(200);
            } else{
                response = mHttp.send(req);
            }
            system.debug('res' + response );
            if(response.getStatusCode() == 200) {
                objMsg.Integration_Status__c = 'Success';
            } else {
                objMsg.Integration_Status__c = 'Failed';
                objMsg.Error_Code__c = String.valueOf(response.getStatusCode());
            }   
            objMsg.Unique_Key__c = objMsg.Document__c + '_' + objMsg.Contract__c + '_' + objMsg.Parent_Template_Name__c + '_' + objMsg.Integration_Status__c + '_' + objMsg.Name;  
            objWrapper.payload = 'DOCUMENT_CONTENT_CANNOT_BE_DISPLAYED';
            objMsg.Request_Envelope__c = JSON.serialize(objWrapper);
            lstIntegrationMessages.add( objMsg );
        } else {
            objMsg.Integration_Status__c = 'Failed';
            objMsg.Error_Code__c = String.valueOf(res.getStatusCode());
            objMsg.Response_Envelope__c = res.getBody();
            objMsg.Unique_Key__c = objMsg.Document__c + '_' + objMsg.Contract__c + '_' + objMsg.Parent_Template_Name__c + '_' + objMsg.Integration_Status__c + '_' + objMsg.Name;  
            objWrapper.payload = 'DOCUMENT_CONTENT_CANNOT_BE_DISPLAYED';
            objMsg.Request_Envelope__c = JSON.serialize(objWrapper);
        }
    }

    public void finish(Database.BatchableContext bc) {
        if( !lstIntegrationMessages.isEmpty() ) {
            update lstIntegrationMessages;
        }
    }

    public class DocumentWrapper {
        public Document__c docDetails ;
        public String payload ;
        public String contractId ;
        public String fileName ;
        public String fileFormat ;
    }
}