force-app/main/default/objects/Contract/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <description>Customer Purchase Order#</description>
    <label>Customer PO#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Manual_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Manual_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/POC__c.field-meta.xml
<CustomField>
    <fullName>POC__c</fullName>
    <formula>TEXT(SBQQ__Opportunity__r.POC__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>POC?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/POC__c.field-meta.xml
<CustomField>
    <fullName>POC__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>POC?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__TerminatedDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TerminatedDate__c</fullName>
    <description>Date on which this subscription terminated.</description>
    <inlineHelpText>Date the subscription terminated. Automatically populated when covered asset is upgraded.</inlineHelpText>
    <label>Terminated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Deactivation</fullName>
            </value>
            <value>
                <fullName>Facility Change</fullName>
            </value>
            <value>
                <fullName>New Line</fullName>
            </value>
            <value>
                <fullName>Price Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Upgrade/Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RenewContractsBatch.cls
/* ****************************************************************************************************************
Name          : RenewContractsBatch
Description   : RenewContractsBatch Apex Batch Class function is to generate Renewal Opportunity & Quote

Author        : Himanshu Maheshwari (Compro Technologies)
Creation Date : 29-June-2020
**************************************************************************************************************** */
global class RenewContractsBatch implements Database.Batchable<SObject>, Database.Stateful {
    global Integer recordsProcessed = 0;
    String contractId;
    global RenewContractsBatch(){

    }
    global RenewContractsBatch (String cId) {
        contractId = cId;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query;
        if(contractId == '' || contractId == NULL)
            query = 'SELECT Id, Is_SCF_Generated__c, SBQQ__RenewalForecast__c, Renewal_Type__c, Manual_Renewal__c, Customer_PO__c, SCF_Type__c, SBQQ__RenewalQuoted__c FROM Contract WHERE Status = \'Activated\' AND EndDate = TOMORROW AND Renewal_Type__c = \'Auto\' AND SBQQ__RenewalForecast__c = FALSE AND SBQQ__RenewalQuoted__c = FALSE AND POC__c <> \'Yes\'';
        else
                query = 'SELECT Id, Is_SCF_Generated__c, SBQQ__RenewalForecast__c, Renewal_Type__c, Manual_Renewal__c, Customer_PO__c, SCF_Type__c, SBQQ__RenewalQuoted__c FROM Contract WHERE Id = \'' + contractId +  '\' AND Status = \'Activated\' AND Renewal_Type__c = \'Auto\' AND SBQQ__RenewalForecast__c = FALSE AND SBQQ__RenewalQuoted__c = FALSE AND POC__c <> \'Yes\'';
        system.debug('query===>'+query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Contract> scope){
        Map<Id, Contract> contractMap = new Map<Id, Contract>();
        List<Id> contractIdList = new List<Id>();

        Map<Id,List<SBQQ__Subscription__c>> contractVsSubs = new Map<Id,List<SBQQ__Subscription__c>>();
        List<Contract> contractList = [SELECT Id,(SELECT Name,SBQQ__TerminatedDate__c,SBQQ__RequiredById__c FROM SBQQ__Subscriptions__r WHERE SBQQ__RequiredById__c = Null AND SBQQ__TerminatedDate__c = Null) FROM Contract Where Id IN :scope ];
        for(Contract c :contractList){
            contractVsSubs.put(c.Id,c.SBQQ__Subscriptions__r);
        }

        for(Contract contract : scope){
            if(contractVsSubs.get(contract.Id).size() > 0){
                contractIdList.add(contract.Id);
            }
        }

        //Update SCF as Blank for Renewal Quote
        if(contractIdList.size() > 0){
            ContractSCFandRenewalHandler.updateSCFTypeRenewalContract(contractIdList);
        }

        for(Contract contract : scope){
            if(contractVsSubs.get(contract.Id).size() > 0){
                contract.SBQQ__RenewalQuoted__c = TRUE;
                contract.SBQQ__RenewalForecast__c = TRUE;
            }
        }

        if(scope.size() > 0){
            //update scope;
            Database.SaveResult[] updateResult = Database.update(scope, false);
            for(Database.SaveResult svRes: updateResult)
            {
                if(!svRes.isSuccess()){
                    insert new Error_Log__c(Message__c = svRes.getErrors()[0].getMessage(),Type__c = 'Renewal');
                }
            }
        }
    }

    global void finish(Database.BatchableContext bc){
        // Get the ID of the AsyncApexJob representing this batch job 
        // from Database.BatchableContext. 
        // Query the AsyncApexJob object to retrieve the current job's information. 
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];

        // OPTIONAL: Send an email to the Apex job's submitter notifying of job completion. 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] { 'yash.p@cloudroute.in','smadav@yotta.com',a.CreatedBy.Email };
        mail.setToAddresses(toAddresses);
        mail.setSubject('Contract Renewal Contract Batch ' + a.Status);
        mail.setPlainTextBody ('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}