force-app/main/default/objects/Contract/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <description>Customer Purchase Order#</description>
    <label>Customer PO#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Manual_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Manual_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Manual_Renewal_Updated_by_OMT__c.field-meta.xml
<CustomField>
    <fullName>Manual_Renewal_Updated_by_OMT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Renewal Updated by OMT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/POC__c.field-meta.xml
<CustomField>
    <fullName>POC__c</fullName>
    <formula>TEXT(SBQQ__Opportunity__r.POC__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>POC?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
                <default>true</default>
                <label>Auto</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Total_Grand_Total__c</fullName>
    <label>Total Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price__c</fullName>
    <label>Final Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <formula>TEXT( SBQQ__Product__r.Sale_Type__c )</formula>
    <label>Sale Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
                <default>true</default>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Deployment Pending</fullName>
            </value>
            <value>
                <fullName>Under Delivery</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Amendment in progress</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Under Decommission</fullName>
            </value>
            <value>
                <fullName>Under Commissioning</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Technical_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Technical_Start_Date__c</fullName>
    <label>Technical Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateRenewalTypeBatch.cls
/* ****************************************************************************************************************
Name          : UpdateRenewalTypeBatch
Description   : UpdateRenewalTypeBatch Apex Batch Class function is to update renewal status on Quote

Author        : Himanshu Maheshwari (Compro Technologies)
Creation Date : 13-November-2020
**************************************************************************************************************** */
global class UpdateRenewalTypeBatch implements Database.Batchable<SObject> { 
    public Id contractId;
    global Database.QueryLocator start(Database.BatchableContext bc){ 
        String query = 'SELECT Id, POC__c, ContractTerm, Manual_Renewal_Updated_by_OMT__c, Total_Grand_Total__c, Renewal_Type__c, Is_SCF_Generated__c, SBQQ__RenewalQuoted__c, Customer_PO__c FROM Contract';
        if(contractId != NULL){
            query += ' WHERE Id =: contractId';
        } else{
            query += ' WHERE Status = \'Activated\' AND SBQQ__RenewalQuoted__c = FALSE AND (EndDate = NEXT_N_DAYS: 30 OR POC__c = \'Yes\')';
        }

        return Database.getQueryLocator(query); 
    } 
    
    global void execute(Database.BatchableContext bc, List<Contract> scope){ 
        Map<Id, Boolean> subPriceDiffMap = new Map<Id, Boolean>();
        Map<Id, Contract> contractMap = new Map<Id, Contract>();
        List<String> SaleTypeList = new List<String>();
        Decimal lastPrice;
        
        //marks contract manual 
        // for(Contract contract : scope){ 
        //     if(contract.Customer_PO__c != NULL && contract.Customer_PO__c != ''){
        //         //contract.Manual_Renewal__c = TRUE;
        //         contract.Renewal_Type__c = 'Manual';
        //     }
        //     contractMap.put(contract.Id, contract);
        // } 
        
        //gets subscriptions in the contract and put into map on the basis of prices of all years being same or different
        for(SBQQ__Subscription__c sub : [SELECT Id, SBQQ__RequiredById__c, Final_Unit_Price__c, SBQQ__Contract__c, Technical_Start_Date__c, Sale_Type__c FROM SBQQ__Subscription__c WHERE SBQQ__Contract__c IN: scope AND Status__c != 'Cancelled' AND Status__c != 'Decommissioned' AND Status__c != 'Deactivated' AND Status__c != 'Under Decommission' AND SBQQ__Contract__r.ContractTerm > 12 AND SBQQ__RequiredById__c != NULL ORDER BY SBQQ__RequiredById__c, Final_Unit_Price__c]){ 
            if(subPriceDiffMap.containsKey(sub.SBQQ__RequiredById__c)){
                if(lastPrice != sub.Final_Unit_Price__c){
                    subPriceDiffMap.put(sub.SBQQ__Contract__c, TRUE);    
                }
            } else{
                subPriceDiffMap.put(sub.SBQQ__Contract__c, FALSE);
                lastPrice = sub.Final_Unit_Price__c;
            }
        }

        Contract contract = new Contract();
        Map<Id, String> salesTypeMap = new Map<Id, String>();
        for(SBQQ__Subscription__c sub : [SELECT Id, SBQQ__RequiredById__c, Final_Unit_Price__c, SBQQ__Contract__c, Technical_Start_Date__c, Sale_Type__c FROM SBQQ__Subscription__c WHERE SBQQ__Contract__c IN: scope AND Status__c != 'Cancelled' AND Status__c != 'Decommissioned' AND Status__c != 'Deactivated' AND Status__c != 'Under Decommission' AND SBQQ__RequiredById__c != NULL ORDER BY SBQQ__Contract__c, SBQQ__RequiredById__c, Final_Unit_Price__c, Sale_Type__c]){ 
            //puts the sale type into a map to check if the subscriptions contain all otc items
            //if(contractMap.keySet().size() > 0){
                // if(contractMap.containsKey(sub.SBQQ__Contract__c) && (sub.Technical_Start_Date__c == NULL || ((sub.Final_Unit_Price__c == NULL || sub.Final_Unit_Price__c == 0) && sub.SBQQ__RequiredById__c != '' && sub.SBQQ__RequiredById__c != NULL))){   
                if(contractMap.containsKey(sub.SBQQ__Contract__c) && (contract == NULL || contract.Id != contractMap.get(sub.SBQQ__Contract__c).Id)){  
                    contract = contractMap.get(sub.SBQQ__Contract__c);
                    saleTypeList = new List<String>();
                }

                saleTypeList.add(sub.Sale_Type__c);
                if((saleTypeList.contains('ZTAD') && saleTypeList.contains('ZTAN')) || (saleTypeList.contains('ZTAD') && !saleTypeList.contains('ZTAN'))){
                    contract.Renewal_Type__c = 'Auto';
                } else{
                    contract.Renewal_Type__c = 'Manual';
                }
                contractMap.put(sub.SBQQ__Contract__c, contract);
            //}
        }
        
        //Sets the renewal type of contract if it satisfies the manual or auto conditions
        for(Contract cntrct : scope){
            //if(contractMap.size() > 0){
                //if(cntrct.Is_SCF_Generated__c || cntrct.POC__c == 'Yes' || (cntrct.ContractTerm < 12 && cntrct.POC__c == 'No') || (cntrct.Total_Grand_Total__c == 0 && cntrct.POC__c == 'No') || (cntrct.ContractTerm > 12 && (subPriceDiffMap.containsKey(cntrct.Id) && subPriceDiffMap.get(cntrct.Id) )) || (contractMap.containsKey(cntrct.Id) && contractMap.get(cntrct.Id).Renewal_Type__c == 'Manual')){
                if(cntrct.Is_SCF_Generated__c || cntrct.POC__c == 'Yes' || cntrct.Total_Grand_Total__c == 0 || (cntrct.ContractTerm > 12 && (subPriceDiffMap.containsKey(cntrct.Id) && subPriceDiffMap.get(cntrct.Id))) || (contractMap.containsKey(cntrct.Id) && contractMap.get(cntrct.Id).Renewal_Type__c == 'Manual')){
                    cntrct.Renewal_Type__c = 'Manual';
                } else if((cntrct.ContractTerm > 12 && subPriceDiffMap.containsKey(cntrct.Id) && !subPriceDiffMap.get(cntrct.Id)) || !cntrct.Manual_Renewal_Updated_by_OMT__c || (contractMap.containsKey(cntrct.Id) && contractMap.get(cntrct.Id).Renewal_Type__c == 'Auto') || cntrct.ContractTerm < 12) {
                    cntrct.Renewal_Type__c = 'Auto';
                }
            //} 
        }
        
        update scope;
    }
    
    global void finish(Database.BatchableContext bc){ 
        
    }
}