force-app/main/default/objects/Contract/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Bill_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_End_Date__c</fullName>
    <label>Bill End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Bill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Start_Date__c</fullName>
    <label>Bill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Effective_date__c.field-meta.xml
<CustomField>
    <fullName>Effective_date__c</fullName>
    <description>Date for Contract Lines SCF</description>
    <label>Effective date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Finalized_Billing_Dates__c.field-meta.xml
<CustomField>
    <fullName>Finalized_Billing_Dates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To trigger subscriptions integration</description>
    <label>Finalized Billing Dates?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <label>Quote Line Sr #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Deactivation</fullName>
            </value>
            <value>
                <fullName>Facility Change</fullName>
            </value>
            <value>
                <fullName>New Line</fullName>
            </value>
            <value>
                <fullName>Price Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Upgrade/Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
                <default>true</default>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Deployment Pending</fullName>
            </value>
            <value>
                <fullName>Under Delivery</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Amendment in progress</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Under Decommission</fullName>
            </value>
            <value>
                <fullName>Under Commissioning</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Technical_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Technical_End_Date__c</fullName>
    <label>Technical End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Technical_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Technical_Start_Date__c</fullName>
    <label>Technical Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContractLinesSCF.cls
public class ContractLinesSCF {
@AuraEnabled
    public static List<SBQQ__Subscription__c> getSubscription(id recordId) {
        system.debug('recordId: '+recordId);
        return [select id, S_No__c, SBQQ__ProductName__c, SBQQ__Bundle__c, SBQQ__RequiredById__c, Bill_Start_Date__c, Bill_End_Date__c, Technical_Start_Date__c,Technical_End_Date__c, SBQQ__Contract__c,
                Finalized_Billing_Dates__c, SCF_Type__c, Effective_date__c, Status__c from SBQQ__Subscription__c where SBQQ__Contract__c =:recordId and SCF_Type__c = ''];
    }
    
@AuraEnabled
    public static List<String> getSCFTypes(){
        List<String> lstSCFTypes=new List<String>();
        Schema.DescribeFieldResult fieldResult = SBQQ__Subscription__c.SCF_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry s:ple){                
            lstSCFTypes.add(s.getLabel());                
        } 
        return lstSCFTypes;
    }
    
@AuraEnabled
	public static String updateRecords(List<SBQQ__Subscription__c> subscriptionList){
        string errorMessage  = 'SUCCESS';
        Map<id,SBQQ__Subscription__c> parentSubMap = new Map<id,SBQQ__Subscription__c>();
        Set<id> childSubIdSet = new Set<id>();
        Boolean flag = false;
        date minDate;
        
        for(SBQQ__Subscription__c sub : subscriptionList){
            if(sub.SBQQ__Bundle__c){
                parentSubMap.put(sub.id, sub);
                if(sub.SCF_Type__c!=null && sub.SCF_Type__c!=''){
                    sub.Status__c = 'Amendment in progress';
                    flag = true;
                    if(minDate == NULL || sub.Effective_date__c < minDate)
                        minDate = sub.Effective_date__c;
                }
            }
            else if(sub.SBQQ__RequiredById__c != null && sub.SBQQ__RequiredById__c != '')
                childSubIdSet.add(sub.id);
        }
       
        for(SBQQ__Subscription__c sub : subscriptionList){
            if(childSubIdSet.contains(sub.Id) && parentSubMap.containsKey(sub.SBQQ__RequiredById__c)){
                sub.SCF_Type__c = parentSubMap.get(sub.SBQQ__RequiredById__c).SCF_Type__c;
                sub.Effective_date__c = parentSubMap.get(sub.SBQQ__RequiredById__c).Effective_date__c;
                if(sub.SCF_Type__c!=null && sub.SCF_Type__c!='')
                    sub.Status__c = 'Amendment in progress';
            }
        }
        
        if(flag){
            Contract c = [Select id,SCF_Type__c, SBQQ__AmendmentStartDate__c from COntract where id =: subscriptionList[0].SBQQ__Contract__c];
            c.SCF_Type__c = 'Contract Line SCF';
            c.SBQQ__AmendmentStartDate__c = minDate;
            try{
                update subscriptionList;
                update c;
            }
            catch(exception e){
                errorMessage = e.getMessage();
            }
        }
        system.debug('Error Message: '+ errorMessage);
        return errorMessage;
    }
}