force-app/main/default/objects/Asset/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <formula>SBQQ__RequiredBySubscription__r.SBQQ__Contract__r.Currency_Conversion_Factor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Conversion Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Final_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Net_Price__c</fullName>
    <label>Final Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price__c</fullName>
    <label>Final Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Last_Quote__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Last Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <label>Model Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/SBQQ__Dimension__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__PriceDimensionHelp</customHelpPage>
    <label>Price Dimension</label>
    <nameField>
        <label>Dimension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Dimension_Type__c.field-meta.xml
<CustomField>
    <fullName>Dimension_Type__c</fullName>
    <label>Dimension Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>VRC</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Currency_Sensitive_Line__c.field-meta.xml
<CustomField>
    <fullName>Currency_Sensitive_Line__c</fullName>
    <formula>SBQQ__Contract__r.Currency_Conversion_Factor__c * Monthly_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency_Sensitive_Line</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Final_Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Net_Price__c</fullName>
    <label>Final Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Final_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price__c</fullName>
    <label>Final Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Dimension__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Dimension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Price Dimension associated with this Subscription</description>
    <inlineHelpText>Price Dimension associated with this Subscription</inlineHelpText>
    <label>Price Dimension</label>
    <referenceTo>SBQQ__Dimension__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity of this subscription product purchased by the customer.</description>
    <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SegmentEndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentEndDate__c</fullName>
    <description>For MDQ products, the End Date from the original segment&apos;s Quote Line.</description>
    <inlineHelpText>For MDQ products, the End Date from the original segment&apos;s Quote Line.</inlineHelpText>
    <label>Segment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SegmentStartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SegmentStartDate__c</fullName>
    <description>For MDQ products, the Start Date from the original segment&apos;s Quote Line.</description>
    <inlineHelpText>For MDQ products, the Start Date from the original segment&apos;s Quote Line.</inlineHelpText>
    <label>Segment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SubscriptionIntegrationSummerization.cls
/* ****************************************************************************************************************
Name          : SubscriptionIntegrationSummerization
Description   : Class to create custom JSON structure for year wise distribution of cost for bundle. 
Author        : Nandish Shenoy  
Creation Date : 27/5/2020
Modified Date : 27/5/2020
**************************************************************************************************************** */
public with sharing class SubscriptionIntegrationSummerization implements IntegrationExtension {
    
    public static Map<Id, List<SBQQ__Subscription__c>> mapBundleIdToComponentIds = new Map<Id, List<SBQQ__Subscription__c>>();
    public static Map<Id, List<Asset>> mapBundleIdToOTC = new Map<Id, List<Asset>>();
    public static Boolean isSCFContract = false;
    /**
     * extends IntegrationExtension Interface to implement custom JSON structures. Primitive parameter JSON is passed from Framework. 
     * Create wrapper class to extract parameters from JSON.
     **/
    public Object runExtension(String params) {
        Params objParam = (Params)JSON.deserialize(params, Params.class); 
        Id BundleId = objParam.id;

        if (mapBundleIdToComponentIds.isEmpty()) {
            SBQQ__Subscription__c objSub = [Select Id, SBQQ__Contract__c, SBQQ__Contract__r.SBQQ__Quote__c, SBQQ__Contract__r.Last_Quote__c From SBQQ__Subscription__c Where Id = :BundleId];
            for (SBQQ__Subscription__c objSubs : [
                    SELECT Id, SBQQ__SegmentLabel__c, SBQQ__SegmentStartDate__c, SBQQ__RequiredById__c,
                            SBQQ__SegmentEndDate__c, SBQQ__Product__r.ProductCode, SBQQ__Product__r.Model_Name__c,
                            SBQQ__Dimension__r.Dimension_Type__c, Currency_Sensitive_Line__c
                    FROM SBQQ__Subscription__c
                    WHERE SBQQ__Quantity__c >= 0 AND SBQQ__Dimension__c != null AND SBQQ__Contract__c = :objSub.SBQQ__Contract__c
            ]) {
                if (!mapBundleIdToComponentIds.containsKey(objSubs.SBQQ__RequiredById__c)) {
                    mapBundleIdToComponentIds.put(objSubs.SBQQ__RequiredById__c, new List<SBQQ__Subscription__c>{
                            objSubs
                    });
                } else {
                    mapBundleIdToComponentIds.get(objSubs.SBQQ__RequiredById__c).add(objSubs);
                }
            }
            system.debug('====' + mapBundleIdToComponentIds.keySet());
            for( Asset objAsset : [SELECT Id, Final_Unit_Price__c, Final_Net_Price__c, SBQQ__RequiredBySubscription__c, Currency_Conversion_Factor__c 
                                    FROM Asset 
                                    WHERE SBQQ__RequiredBySubscription__c  IN :mapBundleIdToComponentIds.keySet() ]) {
                if ( !mapBundleIdToOTC.containsKey( objAsset.SBQQ__RequiredBySubscription__c ) ) {
                    mapBundleIdToOTC.put( objAsset.SBQQ__RequiredBySubscription__c, new List<Asset>{ objAsset });
                } else {
                    mapBundleIdToOTC.get( objAsset.SBQQ__RequiredBySubscription__c ).add( objAsset );
                }
            }
        }
        Map<String, Map<String, outputJSON>> mapDimensionToYearToOPJSON =  new Map<String,Map<String, outputJSON>>();
        
        if( mapBundleIdToComponentIds.get(BundleId) != null ) {
            for( SBQQ__Subscription__c objSubs : mapBundleIdToComponentIds.get(BundleId)) {
                String strPriceDimension = objSubs.SBQQ__Dimension__r.Dimension_Type__c.toLowerCase();
                System.debug('Dimension name --'+strPriceDimension);
                if( !mapDimensionToYearToOPJSON.containsKey( strPriceDimension )) {
                    mapDimensionToYearToOPJSON.put( strPriceDimension, new Map<String, outputJSON>() );
                }          
                String segmentLabel = objSubs.SBQQ__SegmentLabel__c.replaceAll('\\s+','_');                           
                if( !mapDimensionToYearToOPJSON.get( strPriceDimension ).containsKey(segmentLabel) ) {
                    outputJSON obj = new outputJSON();

                    if (strPriceDimension == 'vrc') {
                        if (objSubs.SBQQ__Product__r.ProductCode == 'MTCOLO_Pow_001' || objSubs.SBQQ__Product__r.ProductCode == 'MTCOLO_Pow_002') {
                            obj.pricing = objSubs.Currency_Sensitive_Line__c;
                        } else if (objSubs.SBQQ__Product__r.Model_Name__c != 'Colo Power') {
                            obj.pricing = objSubs.Currency_Sensitive_Line__c;
                        }
                    } else {
                        obj.pricing = math.round(objSubs.Currency_Sensitive_Line__c);
                    }
                    obj.startDate = objSubs.SBQQ__SegmentStartDate__c;
                    obj.endDate = objSubs.SBQQ__SegmentEndDate__c;
                    mapDimensionToYearToOPJSON.get( strPriceDimension ).put( segmentLabel, obj );
                    continue;
                }
                outputJSON obj = mapDimensionToYearToOPJSON.get( strPriceDimension ).get( segmentLabel );
                if (strPriceDimension == 'vrc') {
                    if (objSubs.SBQQ__Product__r.ProductCode == 'MTCOLO_Pow_001' || objSubs.SBQQ__Product__r.ProductCode == 'MTCOLO_Pow_002') {
                        obj.pricing = objSubs.Currency_Sensitive_Line__c;
                    } else if (objSubs.SBQQ__Product__r.Model_Name__c != 'Colo Power') {
                        obj.pricing += objSubs.Currency_Sensitive_Line__c;
                    }
                } else {
                    obj.pricing += math.round(objSubs.Currency_Sensitive_Line__c);

                }
                System.debug('MRC Pricing : --'+obj.pricing);
            }
        }    
        Decimal OTC = 0;
        OTC.setScale(2);
        if( mapBundleIdToOTC.containsKey(BundleId) ) {    
            for( Asset objAsset : mapBundleIdToOTC.get( BundleId )) {
                if( objAsset.Final_Net_Price__c != null)  OTC += math.round(objAsset.Currency_Conversion_Factor__c * objAsset.Final_Net_Price__c);
            }
        }
        JSONGenerator jsonObject = JSON.createGenerator(true);
        jsonObject.writeStartObject();
        for( String strPriceKey : mapDimensionToYearToOPJSON.keySet() ) {
            jsonObject.writeObjectField(strPriceKey, mapDimensionToYearToOPJSON.get( strPriceKey ) );
        }
        System.debug('OTC Value:  --'+OTC);
        jsonObject.writeNumberField( 'otc', OTC.setScale(2));
        jsonObject.writeEndObject();
        return JSON.deserializeUntyped( jsonObject.getAsString() );
    }

    public class Params {
        public String id;
    }

    public class outputJSON {
        public Decimal pricing ;
        public Date startDate ;
        public Date endDate ;
    }
    
    public void runExtension(String params, String requestId){}
}