force-app/main/default/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Location_Availability__c.field-meta.xml
<CustomField>
    <fullName>Location_Availability__c</fullName>
    <label>Location Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZTAD</fullName>
                <label>Sale of Service</label>
            </value>
            <value>
                <fullName>ZTAN</fullName>
                <label>Sale of Equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Send Record To Kafka</inlineHelpText>
    <label>Send to Kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/SBQQ__Dimension__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__PriceDimensionHelp</customHelpPage>
    <label>Price Dimension</label>
    <nameField>
        <label>Dimension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Dimension_Type__c.field-meta.xml
<CustomField>
    <fullName>Dimension_Type__c</fullName>
    <label>Dimension Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>VRC</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Internal_Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Internal_Cost_Price__c</fullName>
    <label>Internal Cost Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Partner_Price__c.field-meta.xml
<CustomField>
    <fullName>Partner_Price__c</fullName>
    <label>Partner Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Product_Head_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Head_Price__c</fullName>
    <label>Product Head Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Sales_Head_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head_Price__c</fullName>
    <label>Sales Head Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TriggerController__c/TriggerController__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerController</label>
</CustomObject>

force-app/main/default/objects/TriggerController__c/fields/DeactivateObjectTrigger__c.field-meta.xml
<CustomField>
    <fullName>DeactivateObjectTrigger__c</fullName>
    <label>DeactivateObjectTrigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductTriggerHandlerTest.cls
@isTest(seeAllData=true)
public class ProductTriggerHandlerTest {
    
    @isTest
    public static void createProductAndSendToKafka(){
        
        /*TriggerController__c tc = new TriggerController__c(DeactivateObjectTrigger__c = '', isActive__c = TRUE);
        insert tc;
        */
        Product2 product7 = new Product2 (Name = 'Test' ,  CurrencyIsoCode = 'INR',Family='12',Business_Unit__c='IN10',SBQQ__Component__c = false,isActive=true,
                                          Product_Description__c ='product Description', Description ='description12',Location_Availability__c='  IN12',Sale_Type__c='ZTAN' );
        insert product7;    
        
        //Product2 prod = [Select Id, Send_To_API_Layer__c, Family FROM Product2 Where SBQQ__Component__c = false AND isActive=true LIMIT 1];
        product7.Name = 'Testing SomeChange';
        update product7;
        
        Product2 product8 = new Product2 (Name = 'Test' ,  CurrencyIsoCode = 'INR',Family='12',Business_Unit__c='IN10',SBQQ__Component__c = true,isActive = false,
                                          Product_Description__c ='product Description', Description ='description12',Location_Availability__c='  IN12',Sale_Type__c='ZTAN' );
        insert product8;    
        List<Sbqq__Dimension__c> priceDimensionList = new  List<Sbqq__Dimension__c>();
        Sbqq__Dimension__c priceDimension = new Sbqq__Dimension__c (Name = 'Recurring Charge' ,     Dimension_Type__c = 'MRC',  SBQQ__Type__c='Year',
                                                                    SBQQ__UnitPrice__c=125,Cost__c=123, Internal_Cost_Price__c=122,
                                                                    Sales_Price__c=2,Sales_Head_Price__c=3, Partner_Price__c=3,
                                                                    Product_Head_Price__c=4,sbqq__product__c=product8.Id);
        Insert priceDimension;
        product8.Name = 'Testing SomeChange';
        product8.isActive = true;
        update product8;
    }
}