force-app/main/default/objects/Product2/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <label>Model Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Family_Text__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Text__c</fullName>
    <description>Created By Nandish to be used in Contract Integration</description>
    <formula>CASE(TEXT( Family ), &apos;10&apos;,&apos;Colocation&apos;,
                     &apos;12&apos;,&apos;Network &amp; Connectivity&apos;,
                     &apos;13&apos;,&apos;Cyber Security&apos;,
                     &apos;14&apos;,&apos;Yotta Cloud&apos;,
                     &apos;16&apos;,&apos;Federated Cloud&apos;,
                     &apos;17&apos;,&apos;IT Management&apos;,
                     &apos;18&apos;, &apos;Traded Goods&apos;,
                     &apos;Ad-hoc&apos;,&apos;Ad-hoc&apos;, &apos;&apos;)</formula>
    <label>Product Family Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line_Text__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Text__c</fullName>
    <formula>CASE(TEXT( Product_Line__c ), 
&apos;16100&apos;,&apos;FEDERATED CLOUD&apos;,
&apos;13300&apos;,&apos;HOSTED SECURITY&apos;,
&apos;12100&apos;,&apos;HOSTED NETWORK SERVICES&apos;,
&apos;12200&apos;,&apos;MANAGED WAN SERVICES&apos;,
&apos;18100&apos;,&apos;TRADED GOODS&apos;,
&apos;14400&apos;,&apos;DISASTER RECOVERY AS A SERVICE&apos;,
&apos;14600&apos;,&apos;PLATFORM AS A SERVICE&apos;,
&apos;14700&apos;,&apos;PRIVATE CLOUD&apos;,
&apos;10100&apos;,&apos;MULTITENANT COLOCATION&apos;,
&apos;10200&apos;,&apos;COLOCATION SUPPORT &apos;,
&apos;10300&apos;,&apos;DEDICATED BUILDING COLOCATION&apos;,
&apos;13100&apos;,&apos;MANAGED SECURITY&apos;,
&apos;14200&apos;,&apos;STORAGE AS A SERVICE&apos;,
&apos;14100&apos;,&apos;COMPUTE AS A  SERVICE&apos;,
&apos;17100&apos;,&apos;IT MONITORING&apos;,
&apos;17200&apos;,&apos;IT ADMINISTRATION&apos;,
&apos;17300&apos;,&apos;IT PROFESSIONAL&apos;,
&apos;13200&apos;,&apos;PROFESSIONAL SECURITY&apos;,
&apos;14300&apos;,&apos;BACKUP &amp; RECOVERY AS A SERVICE&apos;,
&apos;14500&apos;,&apos;SOFTWARE AS A SERVICE&apos;,
&apos;Structured Cabling&apos;,&apos;Structured Cabling&apos;,
&apos;Ad-hoc&apos;,&apos;Ad-hoc&apos;,
&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_of_Measurement__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measurement__c</fullName>
    <label>Unit of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sqft</fullName>
            </value>
            <value>
                <fullName>Nos</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>KWH / KW</fullName>
            </value>
            <value>
                <fullName>VA/ KVA</fullName>
            </value>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>Mtr</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>TB</fullName>
            </value>
            <value>
                <fullName>Per Day</fullName>
            </value>
            <value>
                <fullName>Mbps</fullName>
            </value>
            <value>
                <fullName>Gbps</fullName>
            </value>
            <value>
                <fullName>Per Cubic Meter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Variable_UOM__c.field-meta.xml
<CustomField>
    <fullName>Variable_UOM__c</fullName>
    <label>Variable UOM</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Variable_Product__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hour</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>TB</fullName>
            </value>
            <value>
                <fullName>Mbps</fullName>
            </value>
            <value>
                <fullName>Tickets</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>Per Cubic Meter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/SBQQ__Dimension__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__PriceDimensionHelp</customHelpPage>
    <label>Price Dimension</label>
    <nameField>
        <label>Dimension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Dimension_Type__c.field-meta.xml
<CustomField>
    <fullName>Dimension_Type__c</fullName>
    <label>Dimension Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>VRC</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Distributor_Price__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Price__c</fullName>
    <label>Distributor Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Internal_Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Internal_Cost_Price__c</fullName>
    <label>Internal Cost Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Partner_Price__c.field-meta.xml
<CustomField>
    <fullName>Partner_Price__c</fullName>
    <label>Partner Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Product_Head_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Head_Price__c</fullName>
    <label>Product Head Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Sales_Head_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head_Price__c</fullName>
    <label>Sales Head Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>Contact.Account.Partner_Check__c</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TariffCardController.cls
public class TariffCardController {
    public string recordId{get;set;}
    public List<Product2> listOfProduct{get;set;}
    public List<SBQQ__Dimension__c> listOfProductDimensions{get;set;}
    public TariffCardWrapper.ProductWrapper productWrap{get;set;}
    public List<TariffCardWrapper.ProductWrapper> listOfProductWrap{get;set;}
    public String profileName { get; set;}
    public Boolean SalesProfile { get; set; }
    public Boolean PartnerProfile { get; set; }
    public Boolean DistributorPartnerProfile { get; set; }
    public String CurrentDatetime {get; Set;}
    public Boolean PartnerDisclamer {get; set;}
    public Boolean SalesDisclamer {get; set;}

    
    public Map<String,List<TariffCardWrapper.ProductWrapper>> mapOfProductWrap {get; set;}
    public Map<String,Set<String>> mapOfProductFamily {get; set;}
    
    public TariffCardController(){
 
        //recordId  = ApexPages.CurrentPage().getparameters().get('id');

         CurrentDatetime = DateTime.NOW().format('dd/MM/yyyy HH:mm:ss', UserInfo.getTimeZone().toString());

        PartnerDisclamer = false;
        SalesDisclamer = false;
        SalesProfile = false ;
        PartnerProfile = false;
        DistributorPartnerProfile = false;
        system.debug('recordId='+ recordId);
        mapOfProductWrap = new Map<String,List<TariffCardWrapper.ProductWrapper>>();
        mapOfProductFamily = new Map<String,Set<String>>();
        listOfProductWrap = new List<TariffCardWrapper.ProductWrapper>();
        listOfProduct = [SELECT Id, Name, Family,Product_Family_Text__c,Product_Line_Text__c,Product_Description__c,Description,Variable_UOM__c,Model_Name__c,Unit_of_Measurement__c,(SELECT Id,Dimension_Type__c,Name,SBQQ__Type__c,Distributor_Price__c,Internal_Cost_Price__c,Partner_Price__c,Product_Head_Price__c,Sales_Head_Price__c,
                                 Sales_Price__c,SBQQ__UnitPrice__c,SBQQ__Product__c FROM SBQQ__Dimensions__r) From Product2 WHERE SBQQ__Component__c = true AND IsActive = true and Product_Family_Text__c <> null];
        listOfProductDimensions = [SELECT Id,Dimension_Type__c,Name,SBQQ__Type__c,Distributor_Price__c,Internal_Cost_Price__c,Partner_Price__c,Product_Head_Price__c,Sales_Head_Price__c,
                                 Sales_Price__c,SBQQ__UnitPrice__c,SBQQ__Product__c From SBQQ__Dimension__c WHERE SBQQ__Product__c IN :listOfProduct ];
        for(Product2 prod:listOfProduct){
            productWrap = new TariffCardWrapper.ProductWrapper();
            productWrap.Name = prod.Name;
            productWrap.productFamily = prod.Product_Family_Text__c;
            productWrap.productDescription = prod.Description;
            productWrap.productLine = prod.Product_Line_Text__c;
            productWrap.UOM = prod.Unit_of_Measurement__c;
            productWrap.productBundleName=prod.Model_Name__c;
			
          for(SBQQ__Dimension__c Dim: prod.SBQQ__Dimensions__r){
                if(Dim.Dimension_Type__c == 'OTC'){
                    productWrap.SPrice.OTC = Dim.Sales_Price__c;
                    productWrap.DPrice.OTC = Dim.Distributor_Price__c;
					productWrap.PPrice.OTC = Dim.Partner_Price__c;
                    productWrap.UPrice.OTC = Dim.SBQQ__UnitPrice__c;
                }
              if(Dim.Dimension_Type__c == 'MRC'){
                    productWrap.SPrice.MRC = Dim.Sales_Price__c;
                    productWrap.DPrice.MRC = Dim.Distributor_Price__c;
					productWrap.PPrice.MRC = Dim.Partner_Price__c;
                    productWrap.UPrice.MRC = Dim.SBQQ__UnitPrice__c;
                }
              if(Dim.Dimension_Type__c == 'VRC'){
                    productWrap.SPrice.VRC = Dim.Sales_Price__c;
                    productWrap.DPrice.VRC = Dim.Distributor_Price__c;
					productWrap.PPrice.VRC = Dim.Partner_Price__c;
                    productWrap.UPrice.VRC = Dim.SBQQ__UnitPrice__c;
                }
            }
            listOfProductWrap.add(productWrap);
            
        }
        
        for (TariffCardWrapper.ProductWrapper P : listOfProductWrap) {
            if (mapOfProductWrap.containsKey(P.productBundleName)) {
                List<TariffCardWrapper.ProductWrapper> listOfProductWrapCopy = mapOfProductWrap.get(P.productBundleName);
                listOfProductWrapCopy.add(P);
                mapOfProductWrap.put(P.productBundleName, listOfProductWrapCopy);
            } else {
                mapOfProductWrap.put(P.productBundleName, new List<TariffCardWrapper.ProductWrapper> {P});
            }
        }
        
        for(TariffCardWrapper.ProductWrapper Product : listOfProductWrap){
            if(mapOfProductFamily.containsKey(Product.productFamily)){
                Set<String> listofProductBundlename = mapOfProductFamily.get(Product.productFamily);
                if (!listofProductBundlename.contains(Product.productBundleName)){
                    listofProductBundlename.add(Product.productBundleName);
                }
                mapOfProductFamily.put(Product.productFamily, listofProductBundlename);
            }else{
                mapOfProductFamily.put(Product.productFamily, new Set<String>{ Product.productBundleName });
            }
        }
        
        System.debug('inside controller');
        Id profileId = UserInfo.getProfileId();
        User currentUser = [SELECT Id, Account_Type__c FROM User WHERE Id = :UserInfo.getUserId()];
		String profileName =[Select Id, Name from Profile where Id=:profileId].Name;
         if (profileName  == 'Yotta Partner Profile' && !currentUser.Account_Type__c.Contains('Distributor') || currentUser.Account_Type__c.Contains('Partner')) {
            System.debug('Partner');
            PartnerProfile = true;
            PartnerDisclamer = true;
        }else if ((profileName  == 'Yotta Partner Profile' && currentUser.Account_Type__c.Contains('Distributor')) || profileName == 'Yotta Partner Manager Profile') {
            System.debug('Distributor');
            DistributorPartnerProfile = true;
            PartnerDisclamer = true;
        }else {
            System.debug('Sales');
            SalesProfile = true;
            SalesDisclamer = true;
        }
		system.debug('Profile Name'+profileName);
		system.debug('Sales Profile Name'+SalesProfile);
        system.debug('Parnter Profile Name'+PartnerProfile);
        system.debug('listOfProduct11' +listOfProduct);
        system.debug('listOfProductDimensions' +listOfProductDimensions);
        
    }
	
    public List<SBQQ__Dimension__c> GetDimension(Id ProductId){
        List<SBQQ__Dimension__c> dimen = [SELECT Id,Dimension_Type__c,Name,SBQQ__Type__c,Distributor_Price__c,Internal_Cost_Price__c,Partner_Price__c,Product_Head_Price__c,Sales_Head_Price__c,
                                  Sales_Price__c,SBQQ__UnitPrice__c,SBQQ__Product__c From SBQQ__Dimension__c WHERE SBQQ__Product__c = :ProductId ];
        return dimen;
    }    
    
    public class ProductDimensionWrapper{
        public string Name{get;set;}
        public string Family{get;set;}
        public string ProductLine{get;set;}
        public ProductDimensionWrapper(String Name,String Family,String ProductLine){
            this.Name = Name;
            this.Family = Family;
            this.ProductLine = ProductLine;
            
        }
        
    }
    
    
}