force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Ship To Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Company_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private Limited</fullName>
    </customValue>
    <customValue>
        <fullName>Public Limited</fullName>
    </customValue>
    <customValue>
        <fullName>Govt Company</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Liability Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Proprietorship/Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Trust/NGO/Society/HUF</fullName>
    </customValue>
    <masterLabel>Company Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerPortalWebhookListnerTest.cls
@isTest
public class CustomerPortalWebhookListnerTest
{
    @TestSetup
    static void makeData()
    {
        Account acc = new Account();
        acc.Name='Swati Kannaujiya';
        acc.Company_Type__c='Private Limited';
        acc.Industry='Pharma';
        insert acc;
   
        Contract cont = new Contract();
        //cont.Support_To_Account__c='10603';
        //cont.Support_To___c
        cont.AccountId = acc.Id;
        insert cont; 
        system.debug('account'+acc.id);
    }
    @isTest static void positiveTest1()
    {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String acNumber =[select Account_Number__c from account].Account_Number__c;
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalWebhookListner';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueOf('{ "bill_to_customerid" : "'+acNumber+'" }');
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalWebhookListner.manageBillToData();
        Test.stopTest();
        
        
    }
    
}