force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Authoritative_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Authoritative_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authoritative Signatory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Existing_Name__c.field-meta.xml
<CustomField>
    <fullName>Existing_Name__c</fullName>
    <description>Account Existing Name</description>
    <label>Existing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_SCF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Is_SCF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is SCF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Name_Change_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Name_Change_Effective_Date__c</fullName>
    <label>Name Change Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Name__c</fullName>
    <label>New Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Name_Change_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Name_Change_Effective_Date__c</fullName>
    <label>Name Change Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <label>Approved</label>
</RecordType>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Bill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Start_Date__c</fullName>
    <label>Bill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Bundle_Description__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Description__c</fullName>
    <label>Bundle Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <label>YNS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
    <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity of this subscription product purchased by the customer.</description>
    <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
                <default>true</default>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Deployment Pending</fullName>
            </value>
            <value>
                <fullName>Under Delivery</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Amendment in progress</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Under Decommission</fullName>
            </value>
            <value>
                <fullName>Under Commissioning</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SCFCustomerNameChangePDFController.cls
/* ****************************************************************************************************************
Name          : SCFCustomerNameChangePDFController
Description   : It is used for SCFCustomerNameChange PDF to fetch required data from Account and for lightning component
on Opportunity  for saving it as a file on account.

Author        : Riya Sharma(Compro Technologies)

**************************************************************************************************************** */
public without sharing class SCFCustomerNameChangePDFController {
    
    
    public Account accountDetails{get;set;}
    public String accountId {get;set;}
    public static string errorMessage {get;set;}
    public static Id FileId;
    
    //gets the current id of the account page
    public SCFCustomerNameChangePDFController() {
        accountId = ApexPages.currentPage().getParameters().get('id');
        System.debug('accountId' + accountId);
        
        //Queries the required data for pdf
        accountDetails = [Select Existing_Name__c,Account_Number__c,New_Customer_Name__c,Name_Change_Effective_Date__c,Name,BillingAddress,Authoritative_Signatory__r.Name,
                          Authoritative_Signatory__r.Title,Authoritative_Signatory__r.MobilePhone,Authoritative_Signatory__r.Email from Account where id = :accountId
                          LIMIT 1]; 
    }
    
    //This function gets the product details related to the account on the subscription field and stores it in a wrapper class
    //to be able to be used in pdf product table
    public List< ContractLineWrapper.ParentWrapper> ContractLines{ get{
        System.debug('accountId' + AccountId);
        List<Sbqq__Subscription__c> SubscriptionDetails = [Select Id,SBQQ__ContractNumber__c,Bundle_Description__c,SBQQ__ProductName__c,SBQQ__Quantity__c,Bill_Start_Date__c,toLabel(Location__c),
                                                           SBQQ__RequiredById__c 
                                                           from Sbqq__Subscription__c where SBQQ__Contract__r.AccountId = :accountId and SBQQ__RequiredById__c=null and Status__c='Active' and SBQQ__Quantity__c >= 0 ORDER BY SBQQ__ContractNumber__c ASC];
        
        
        List<ContractLineWrapper.ParentWrapper> parentWrapList = new List<ContractLineWrapper.ParentWrapper>(); 
        ContractLineWrapper.ParentWrapper parentWrap;
        if(SubscriptionDetails != null){
            for(Sbqq__Subscription__c subs: SubscriptionDetails){
                
                if (subs.SBQQ__RequiredById__c == null){  
                    System.debug(subs.SBQQ__Quantity__c);
                    parentWrap = new ContractLineWrapper.ParentWrapper();
                    System.debug('subs.SBQQ__ContractNumber__c' + subs.SBQQ__ContractNumber__c);
                    parentWrap.Qty = subs.SBQQ__Quantity__c;
                    System.debug('subs.SBQQ__ContractNumber__c' + subs.SBQQ__ContractNumber__c);
                    parentWrap.ContractNumber = subs.SBQQ__ContractNumber__c;
                    parentWrap.deliveryLocation = subs.Location__c;
                    parentWrap.productDescription = subs.Bundle_Description__c;
                    parentWrap.productName = subs.SBQQ__ProductName__c;
                    Date am = subs.Bill_Start_Date__c;           
                    String BillStartDate = DateTime.newInstance(am.year(),am.month(),am.day()).format('dd-MM-YYYY');         
                    parentWrap.BillStartDate = BillStartDate;
                    System.debug('subs.Id'+subs.Id);
                    parentWrapList.add(parentWrap);
                }
            }
        }
        
        System.debug('parentWrapMap'+parentWrapList);
        return parentWrapList;
        
    }set;}
    
    //This function helps save the pdf as file on account if user saves the pdf.
    @AuraEnabled
    public static void SavePDFAsFile(Id RecordId)
    {   
        System.debug(RecordId);
        System.debug('SavePDFAsFile' +  RecordId);   
        string pdfURL= '/apex/SCFCustomerNameChangePDF?id=' +RecordId;
        PageReference pdf = new PageReference(pdfURL);
        Blob pdfBody;
         
        Account acc = [Select Is_SCF_Generated__c,Name from Account where id = :RecordId];
        acc.Is_SCF_Generated__c = true;
        update acc;
    	        
        System.debug('inside If SavePDFAsFile');
        if(Test.isRunningTest()) {
            pdfBody = blob.valueOf('Unit.Test');
        } else {
             pdfBody = pdf.getContent();
        }
        
        Document__c doc = new Document__c();
		//doc.Account__c = quote.SBQQ__Account__c;
        doc.Object__c = 'Account';
        doc.Document_Category__c = 'SCF';
        doc.Document__c = 'Account Name Change SCF';
        doc.Name = 'SCF Customer Name Change';
        
        doc.Account__c = RecordId;
		insert doc;
        
       
        String currentDateTime = System.now().format();
        
        ContentVersion cont = new ContentVersion();
        cont.VersionData = pdfbody;
        System.debug('VersionData');
       
        cont.title = acc.Name + 'SCF-' +RecordId +'-'+currentDateTime + '.pdf';
        
        System.debug('currentDateTime  is'+ currentDateTime );
        cont.pathOnClient = acc.Name + 'SCF-' + RecordId  +'-'+currentDateTime + '.pdf';
        System.debug('tempAccountId:::::::' +RecordId);
        cont.FirstPublishLocationId = RecordId;
        System.debug('ContentVersion:::::::' +cont);
        insert cont;
        
        ContentVersion insertedcont = [Select ContentDocumentId from ContentVersion where ID =:cont.Id ][0]; 
        FileId= cont.Id; // FileId= insertedcont.ContentDocumentId;
        
        update acc;
        
        System.debug('FileId::'+FileId); 
        
    }
    
    //This function checks if required fields are available on the account record to view pdf and sends error in case such a 
    //field is missing
    @AuraEnabled
    public static AccountWrapper isValidAccount(Id AccId)
    {   
        AccountWrapper accWrapper;
        
        String errorMsg='Error:';
        Boolean isError=false;
        Account acc = [SELECT Id,Existing_Name__c,New_Customer_Name__c,Name_Change_Effective_Date__c,Name, OMT_Approval_Status__c FROM Account  where Id =: AccId];
        
        try{
            /*Not Required
            if(acc.Existing_Name__c == null)
            {
                System.debug('Error: Existing name is not available.');
                errorMsg+='Existing name is not available';
                isError = true;
                //return returnValidAccount = 'Error: Existing name is not available.';  
                
            }*/
            if(acc.New_Customer_Name__c == null)
            {
                System.debug('Error: New name is not available.');
                errorMsg+='New name is not available';
                isError = true;
                
            }
            if(acc.Name_Change_Effective_Date__c == null)
            {
                System.debug('Error: Name change date is not available.');
                errorMsg+='Name change date is not available';
                isError = true;
                
            }
            
            if(acc.OMT_Approval_Status__c == 'Approved')
            {
                System.debug('Error: SCF is already Approved, cannot generate the document.');
                errorMsg+='SCF is already Approved, cannot generate the document.';
                isError = true;
                
            }
            
            System.debug('acc is '+acc);
            if(isError){
                
                accWrapper = new AccountWrapper( isError, errorMsg);
                System.debug('accWrapper inside if is'+accWrapper);
                return accWrapper;
            }else{
                accWrapper = new AccountWrapper(isError, '');
                // sows error if a required field to view pdf is missing on account
                System.debug('accWrapper inside else is'+accWrapper);
                return accWrapper;
            }
            
        }
        catch(Exception e)
        {
            System.debug('Exception:::'+e);
            accWrapper = new AccountWrapper(true, e.getMessage());
            return accWrapper;
            // return err = 'ERROR in generating document ' + e.getMessage();
        }    
    }
    
    //Wrapper class for account to store the error messages in case if a required field to show pdf is missing
    public class AccountWrapper{
        @AuraEnabled public Boolean isError;
        @AuraEnabled public String errorMsg;
        public AccountWrapper(Boolean isError, String errorMsg){
            this.isError = isError;
            this.errorMsg = errorMsg;
        }
    }
    
}