force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <label>Partner Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Inactive Partner</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>Deboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Partner_Primary__c.field-meta.xml
<CustomField>
    <fullName>Partner_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner - Primary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Partner_Check__c</field>
            <operation>contains</operation>
            <valueField>$Source.PrimarySource__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner - Primary)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimarySource__c.field-meta.xml
<CustomField>
    <fullName>PrimarySource__c</fullName>
    <label>Primary Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Business Development - Digital</fullName>
            </value>
            <value>
                <fullName>Leadership Leads</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>YCIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <businessProcess>Partner Registration</businessProcess>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Regular_Lead.recordType-meta.xml
<RecordType>
    <fullName>Regular_Lead</fullName>
    <active>true</active>
    <businessProcess>Regular Lead</businessProcess>
    <label>Regular Lead</label>
</RecordType>

force-app/main/default/classes/LeadCreatePartnerController.cls
public class LeadCreatePartnerController {
    public String getAccNumber{get;set;}
    public String AccountName;
    public List<Account> accList;
    public RecordType  RecordType ;
    public Lead lead{
        get{
            if(lead == null)
                lead = new Lead();
            return lead;
        }
        set;
    }
    
    public LeadCreatePartnerController(){}
    
    public PageReference save() {
        //Insert lead with partner account if you get alliance partner else use default value for primary patner
        try{
            //lead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Regular Lead').getRecordTypeId();
            //if(getAccNumber!=NULL || getAccNumber!='') {
                RecordType = [Select Id from RecordType where DeveloperName = 'Regular_Lead' limit 1];
                accList = [Select Id, PartnerType__c from Account where Account_Number__c = :getAccNumber];
                if(accList.size() >0){
                    Account acc=accList[0];
                    if(acc.PartnerType__c != '' && acc.PartnerType__c != null){
                        if(acc.PartnerType__c.contains('Alliance Partner')){
                            AccountName = acc.Id;
                            lead.Partner_Primary__c = AccountName; 
                            lead.PrimarySource__c = 'Alliance Partner';
                        } else
                        	lead.PrimarySource__c = 'Partne Site';
                    }
                    else
                        lead.PrimarySource__c = 'Partne Site'; 
                   // lead.Customer_Number__c = getAccNumber;
                    lead.RecordTypeId = RecordType.Id;
                    insert lead;
                    return Page.LeadCreateForPartnerConfirmation;
                }
                else
                	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please enter a valid account number in customer number'));
                
        }
        catch(DMLException e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
        //ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM , 'New Lead is created!'));
        return null;
    }


}