force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Identity Proof</fullName>
            </value>
            <value>
                <fullName>Address Proof</fullName>
            </value>
            <value>
                <fullName>Additional/Optional Documents</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SCF</fullName>
                <label>Service Change Form</label>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerPortalDocumentRequest.cls
/**
 * Created by Mantesh sharma on 23/06/22.
 */
@RestResource(urlMapping = '/CustomerPortalDocumentRequest/*')
global with sharing class CustomerPortalDocumentRequest {
    @HttpPost
           global static void cpDocumentRequest(){
               try{
                   //Payload in request
                   String requestBody = RestContext.request.requestBody.toString();
                   CpDocumentListRequestWrapper CpDocument = (CpDocumentListRequestWrapper)JSON.deserialize(requestBody, CpDocumentListRequestWrapper.class);
                   //Creating Response Instance
                   RestResponse res = RestContext.response;

                   CpDocumentListResponseWrapper CpDocumentToRes = new CpDocumentListResponseWrapper();
                   CpDocumentToRes.accountNumber = CpDocument.accountNumber;
                   List<Document__c> documntList = new List<Document__c>([SELECT Id,Name,Account__r.Account_Number__c,Object__c,Document_Category__c,Document__c FROM Document__c WHERE Account__r.Account_Number__c = :CpDocument.accountNumber and Object__c = 'Account']);

                   Set<id> DocId = new Set<Id>();
                   for(Document__c doc :documntList){
                       DocId.add(doc.Id);
                   }
                   Map<String, List<ContentDistribution>> InsertMap = new Map<String, List<ContentDistribution>>();
                   List<ContentDistribution> cdListtoInsert = new List<ContentDistribution>();
                   Map<Id,List<String>> newCD = new Map<Id,List<String>>();
                   Map<Id,ContentDocumentLink> cdl = new Map<Id, ContentDocumentLink>([select Id,contentdocument.id,contentdocument.LatestPublishedVersion.Public_Url__c, contentdocument.title, contentdocument.filetype,linkedentityid,ShareType,Visibility from contentdocumentlink where linkedentityid IN :DocId]);
                   List<ContentDocumentLink> cdLink = new List<ContentDocumentLink>();
                    Map<Id,List<String>> DocvsURLMap = new Map<Id, List<String>>();
                   for (ContentDocumentLink tempcv : cdl.values()){


                        if(DocvsURLMap.containsKey(tempcv.LinkedEntityId)){
                            List<String> tempURL = DocvsURLMap.get(tempcv.LinkedEntityId);
                            tempURL.add(tempcv.ContentDocument.LatestPublishedVersion.Public_Url__c);
                            DocvsURLMap.put(tempcv.LinkedEntityId,tempURL);
                        }else{
                            DocvsURLMap.put(tempcv.LinkedEntityId,new List<String>{tempcv.ContentDocument.LatestPublishedVersion.Public_Url__c});
                        }

                   }
                   System.debug('cdl values '+ cdl.values());
                   System.debug('cdl keyset '+ cdl.keySet());


                 //  insert cdListtoInsert;
                   System.debug('ContentDistribution List'+cdListtoInsert);
                   for (Document__c doc : documntList) {
                       DocumentWrapper docWrapper = new DocumentWrapper();
                       System.debug('Document ---> ' + doc);
                           docWrapper.Name = doc.Name;
                           docWrapper.Objects = doc.Object__c;
                           docWrapper.Category = doc.Document_Category__c;
                           if (DocvsURLMap.get(doc.Id) != null) {
                                   docWrapper.ListofDocumentlink = DocvsURLMap.get(doc.Id);
                           }
                           CpDocumentToRes.documentWrapperList.add( docWrapper);
                   }
                   if(CpDocumentToRes != null){
                       res.statusCode = 200;
                       res.responseBody = Blob.valueOf(JSON.serialize(CpDocumentToRes));
                   }else{
                       res.statusCode = 400;
                   }
               }
               catch (Exception e)
               {
                   RestResponse res = RestContext.response;
                   res.statusCode = 500;
                   res.responseBody = Blob.valueOf(JSON.serialize(e.getLineNumber()+' -- '+e.getMessage()));
               }
            }
    public class CpDocumentListRequestWrapper
    {
        public String accountNumber;
    }
    public class CpDocumentListResponseWrapper
    {
        public String externalId;
        public String accountNumber;
        Public List<DocumentWrapper> documentWrapperList;
        public CpDocumentListResponseWrapper()
        {
            this.documentWrapperList = new List<DocumentWrapper>();
        }
    }
    public class DocumentWrapper
    {
        public String Name;
        public String Category;
        public String Objects;
        public List<String> ListofDocumentlink;
        public DocumentWrapper()
        {
            this.ListofDocumentlink = new List<String>();
        }
    }
}