force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Ship To Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerPortalGetOrderDetailsTest.cls
@isTest(SeeallData=true)
public class CustomerPortalGetOrderDetailsTest
{
    @isTest static void positiveTest1()
    {        
        Contract con = [SELECT Id,Contract_Number__c,Account.Account_Number__c,Support_To_Account__r.Account_Number__c FROM Contract WHERE Status = 'Activated' AND Name Like 'Amendment%' ORDER By CreatedDate DESC LIMIT 1 ];
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalGetOrderDetails';  //Request URL
        req.httpMethod = 'POST';  //HTTP Request Type
        req.requestBody = Blob.valueOf('{"bill_to_customerid":["'+con.Account.account_Number__c+'"],"sof_no":['+con.Contract_Number__c+'],"support_to_customerid":["'+con.Support_To_Account__r.Account_Number__c+'"]}');
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalGetOrderDetails.manageBillToData();
        Test.stopTest(); 
    }
    /*
     @isTest static void positiveTest2()
    {
		Contract con = [SELECT Id,Account.Account_Number__c FROM Contract LIMIT 1];
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalGetOrderDetails';  //Request URL
        req.httpMethod = 'POST';  //HTTP Request Type
        req.requestBody = Blob.valueOf('{"bill_to_customerid":["'+con.Account.account_Number__c+'"],"sof_no":[],"support_to_customerid":["'+con.Support_To_Account__r.Account_Number__c+'"]}');
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalGetOrderDetails.manageBillToData();
        Test.stopTest(); 
    }
*/

}