force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/Billing_Group__c.object-meta.xml
<CustomObject>
    <label>Billing Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Billing Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Group__c/fields/Bandwidth_Type__c.field-meta.xml
<CustomField>
    <fullName>Bandwidth_Type__c</fullName>
    <label>Bandwidth Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Burstable</fullName>
            </value>
            <value>
                <fullName>Data Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Groups</relationshipLabel>
    <relationshipName>Billing_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Billing Groups</relationshipLabel>
    <relationshipName>Billing_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN21</fullName>
                <label>YNS Mumbai – HO</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN23</fullName>
                <label>YNS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN22</fullName>
                <label>YNS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS ND1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <label>YNS ND1 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Groups (Support To Account)</relationshipLabel>
    <relationshipName>Billing_Groups_Support_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Total_Burstable_Up_To__c.field-meta.xml
<CustomField>
    <fullName>Total_Burstable_Up_To__c</fullName>
    <label>Total Burstable Up To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Total_Contracted_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Contracted_Value__c</fullName>
    <label>Total Contracted Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <formula>Variable_Bandwidth__r.UomValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UOM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Variable_Bandwidth__c.field-meta.xml
<CustomField>
    <fullName>Variable_Bandwidth__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variable Bandwidth</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Billing Groups</relationshipLabel>
    <relationshipName>Billing_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Ship To Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Billing_Group__c.field-meta.xml
<CustomField>
    <fullName>Billing_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Group</label>
    <referenceTo>Billing_Group__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <formula>SBQQ__Contract__r.Contract_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Line_Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Line_Sr_No__c</fullName>
    <label>Line Item Sr #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <label>YNS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <formula>TEXT(SBQQ__Product__r.Unit_of_Measurement__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UOM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_PushBillingGroupCustomerToKafka.cls
/* ****************************************************************************************************************
Name          : Batch_PushBillingGroupCustomerToKafka
Description   : Pushes billing group data for all customers to Kafka
Author        : Nandish Shenoy  
Creation Date : 1/10/2020
Modified Date : 1/10/2020
**************************************************************************************************************** */
public class Batch_PushBillingGroupCustomerToKafka implements Database.Batchable<sObject>,Database.Stateful, Database.AllowsCallouts {
    
    public String requestId ;
    public Boolean isFailed = false;

    public Batch_PushBillingGroupCustomerToKafka(String params, String requestId) {
        this.requestId = requestId;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        setIntegrationMessageStatus('In Progress');
        String strQuery = (!Test.isRunningTest()) ? 'Select id, Name, Account_Number__c From Account Where Type=\'Customer\'' : 'Select id, Name,Account_Number__c From Account';
        return Database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
        BillingGroupResponse response = new BillingGroupResponse();
        response.requestId = requestId;
        Map<Id, BillingGroupCustomers> mapIdToBillingGroup = new Map<Id, BillingGroupCustomers>();

        for( Billing_Group__c objBG : [SELECT Id, Name, Bill_To_Account__c, External_Id__c,Bill_To_Account__r.Account_Number__c, Bill_To_Account__r.Name,
                                       			Support_To_Account__c, Support_To_Account__r.Name, Total_Contracted_Value__c, Total_Burstable_Up_To__c,Bandwidth_Type__c,
                                       			Contract__c, Contract__r.Contract_Number__c, Variable_Bandwidth__r.Line_Sr_No__c, Valid_From__c,
                                       			UOM__c, Location__c, Support_To_Account__r.Account_Number__c
                                        FROM Billing_Group__c
                                        WHERE Bill_To_Account__c In :scope ] ){
            BillingGroupCustomers obBG = new BillingGroupCustomers();                                
            if( !mapIdToBillingGroup.containsKey(objBG.Bill_To_Account__c) ) {
                obBG.customer_id = objBG.Bill_To_Account__c;
                obBG.customer_name = objBG.Bill_To_Account__r.Name;
                obBG.customer_number = objBG.Bill_To_Account__r.Account_Number__c;
                obBG.billing_groups = new List<BillingGroup>();
                mapIdToBillingGroup.put(objBG.Bill_To_Account__c, obBG);
            } else {
                obBG = mapIdToBillingGroup.get( objBG.Bill_To_Account__c );
            }
            BillingGroup objBillG = new BillingGroup();
            objBillG.billing_group_id = objBG.Id;
            objBillG.billing_group_type = objBG.External_Id__c;  
            objBillG.support_cust_name =  objBG.Support_To_Account__r.Name;
            objBillG.support_cust_id =  objBG.Support_To_Account__c; 
            objBillG.support_number = objBG.Support_To_Account__r.Account_Number__c;
            objBillG.contracted_value = objBG.Total_Contracted_Value__c;
            objBillG.burstable_up_to = objBG.Total_Burstable_Up_To__c;
            objBillG.variable_sof_id = objBG.Contract__c;
            objBillG.variable_sof_number = objBG.Contract__r.Contract_Number__c;
            objBillG.variable_sof_line_sr_no = objBG.Variable_Bandwidth__r.Line_Sr_No__c;
            objBillG.bandwidth_type = objBG.Bandwidth_Type__c;
            objBillG.valid_from = objBG.Valid_From__c;
            objBillG.uom = objBG.UOM__c;
            objBillG.location = objBG.Location__c;
            obBG.billing_groups.add(objBillG);
        }
        response.customers = mapIdToBillingGroup.values();

        //String access_token = (new IntegrationBase()).getAuthorizationToken( Label.Kafka_Integration_Billing_Authorization );
        HttpResponse res = (new IntegrationBase()).getAuthorizationToken( Label.Kafka_Integration_Billing_Authorization );
        if( res.getStatusCode() == 200 || res.getStatusCode() == 201 ) {
            IntegrationBase.kafkaAuthToken token = (IntegrationBase.kafkaAuthToken)JSON.deserialize(res.getBody(), IntegrationBase.kafkaAuthToken.class);
            String access_token = token.access_token;
            HttpRequest req = new HttpRequest();
            Http mHttp = new Http();
            String resp = JSON.serialize(response);
            system.debug('=====Payload:::::' + resp);
            req.setMethod('POST'); 
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setHeader('Authorization', 'Bearer ' + access_token);
            req.setEndpoint(Label.Billing_Group);
            req.setBody( resp );
            req.setTimeout(120000);
            HttpResponse kafkaResponse ;
            if(System.Test.isRunningTest()){
                kafkaResponse = new HttpResponse();
                kafkaResponse.setStatusCode(200);
            } else {
                kafkaResponse = mHttp.send(req);
            }
            if( kafkaResponse.getStatusCode() != 200 && kafkaResponse.getStatusCode() != 201 ) {
                isFailed = true;
            }
        } else {
            isFailed = true;
        }
        
    }

    public void finish(Database.BatchableContext BC){
        setIntegrationMessageStatus((!isFailed) ? 'Success' : 'Failed');
    }

    private void setIntegrationMessageStatus(String status) {
        Integration_Message__c objMessage = new Integration_Message__c();
        objMessage.Integration_Status__c = status;
        objMessage.Unique_Key__c = requestId;
        upsert objMessage Unique_Key__c;  
    }

    public class BillingGroupResponse {
        public String requestid;
        public List<BillingGroupCustomers> customers;
    }

    public class BillingGroup {
        public String billing_group_id;
        public String billing_group_type;
        public String support_cust_name;
        public String support_cust_id;
        public String support_number;
        public Decimal contracted_value;
        public Decimal burstable_up_to;
        public String variable_sof_id;
        public String bandwidth_type;
        public String variable_sof_number;
        public String variable_sof_line_sr_no;
        public Date valid_from;
        public String uom;
        public String location;
    }

    public class BillingGroupCustomers {
        public String customer_name ;
        public String customer_id ;
        public String customer_number;
        public List<BillingGroup> billing_groups;
    }

}