force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Identity Proof</fullName>
            </value>
            <value>
                <fullName>Address Proof</fullName>
            </value>
            <value>
                <fullName>Additional/Optional Documents</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>SCF</fullName>
                <label>Service Change Form</label>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>SOW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerPortalKYCDocumentCreateTest.cls
/*
 * Created by Swati Kannaujiya on 24-05-2022.
 */
@isTest
public class CustomerPortalKYCDocumentCreateTest 
{
    @TestSetup
    static void makeData()
    {
        Account acc = new Account(Name = 'Test'+System.today());
        insert acc;
      Document__c doc = new Document__c();
        doc.Name='Aadhar';
        doc.Account__c=acc.Id;
        doc.Document_Category__c='Identity Proof';
        doc.Document__c='Aadhar';
        insert doc;
        
      ContentVersion conVersion = new Contentversion();
       conVersion.Title='ABC';
       conVersion.PathOnClient ='Penguins.pdf';
       conVersion.versiondata=EncodingUtil.base64Decode('This is version data');
       insert conVersion;
        
      ContentVersion conVersion1 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :conVersion.Id];

       /*ContentVersion conVersion1 = new ContentVersion();
        conVersion1.Title='ABCD';
        conVersion1.PathOnClient='Test2';
        conVersion1.ContentDocumentId='Test';
        conVersion1.versiondata=EncodingUtil.base64Decode('This is version data1');
        conVersion1.Id=conVersion.Id;
        insert conVersion1;*/
        
       ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = doc.Id;
        contentlink.ContentDocumentId = conVersion1.ContentDocumentId;
        contentlink.ShareType = 'V';
        insert contentlink;
  
    }
    @isTest static void positiveTest1()
    {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        Account acc = [SELECT Id,Account_Number__c FROM Account LIMIT 1];
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalKYCDocumentCreate';  //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueOf('{"IsDeleted": false, "Name": "Aadhar", "Account": "'+acc.Id+'", "DocumentCategory": "Identity Proof", "Document": "Aadhar", "ObjectName": "Account", "AccountNumber": "'+acc.Account_Number__c+'", "ExternalId": "123121","attachment":"This is PDF"}');
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalKYCDocumentCreate.CreateDocumentRecord();
        Test.stopTest();
      
    }
}