force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Address_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Address_External_Id__c</fullName>
    <label>Address External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <inlineHelpText>Total Length 10. 5 Alphabets, followed by 4 Digits and 1 Alphabet</inlineHelpText>
    <label>PAN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Postal_code__c.field-meta.xml
<CustomField>
    <fullName>Postal_code__c</fullName>
    <label>Postal code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>South1</fullName>
                <isActive>false</isActive>
                <label>South1</label>
            </value>
            <value>
                <fullName>South2</fullName>
                <isActive>false</isActive>
                <label>South2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>State does not exist with specified Country.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>State__c.Country__c</valueField>
        </filterItems>
        <infoMessage>Select Country to drill down related states</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <label>Contact Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_External_Id__c</fullName>
    <label>Contact External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Lead_Remarks__c</fullName>
    <label>Lead Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadContactsAuthorityLevel__c.field-meta.xml
<CustomField>
    <fullName>LeadContactsAuthorityLevel__c</fullName>
    <label>Lead Contacts Authority Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1: C Level / VP IT / Director Level / Key Decision Makers</fullName>
            </value>
            <value>
                <fullName>Tier 2: GM / AGM / Manager IT / Sr Manager IT. Mid Level managers handling Teams</fullName>
            </value>
            <value>
                <fullName>Tier 3: System Admin / Executives / Asst Managers : Influencers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/OnlineRegistered__c.field-meta.xml
<CustomField>
    <fullName>OnlineRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Online Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>South1</fullName>
                <isActive>false</isActive>
                <label>South1</label>
            </value>
            <value>
                <fullName>South2</fullName>
                <isActive>false</isActive>
                <label>South2</label>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>State does not exist with specified Country.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>State__c.Country__c</valueField>
        </filterItems>
        <infoMessage>Select Country to drill down related states</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/State_External_Key__c.field-meta.xml
<CustomField>
    <fullName>State_External_Key__c</fullName>
    <label>State External Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Company_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private Limited</fullName>
    </customValue>
    <customValue>
        <fullName>Public Limited</fullName>
    </customValue>
    <customValue>
        <fullName>Govt Company</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Liability Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>NBFC</fullName>
    </customValue>
    <customValue>
        <fullName>Proprietorship/Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Trust/NGO/Society/HUF</fullName>
    </customValue>
    <masterLabel>Company Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apparel &amp; Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Broadcast (TV, Radio, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Cargo &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Central Government</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Products</fullName>
    </customValue>
    <customValue>
        <fullName>Content Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Content Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Content Processing</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Global BFSI centers</fullName>
    </customValue>
    <customValue>
        <fullName>Global CDN Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global Internet Exchanges</fullName>
    </customValue>
    <customValue>
        <fullName>Global ISP</fullName>
    </customValue>
    <customValue>
        <fullName>Global TSP</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hi-tech and electronic</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Hoster &amp; Local DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Software Vendor (ISV)</fullName>
    </customValue>
    <customValue>
        <fullName>Info Tech Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>ITES/BPO/KPO</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CustomerPortalLead.cls
/**
 * Created by CloudRoute on 24-05-2022.
 */


@RestResource(urlMapping = '/CPLeadCreate/*')
global with sharing class CustomerPortalLead {

    @HttpPost
    global static void CreateLeadRecord() {
        ResponseWrapper resWrap = new ResponseWrapper();
        List<Lead> convertLeads =  new List<Lead>();

        try {
            Account AccountCreated;
            RestResponse res = RestContext.response;
            Contact ContactCreated;
            String requestBody = RestContext.request.requestBody.toString();
            LeadWrapper leadWrap = (LeadWrapper) JSON.deserialize(requestBody, LeadWrapper.class);
            /*System.debug('State ' + leadWrap);
            System.debug('Country ' + leadWrap.Country);
            State__c sat = [SELECT Id FROM State__c WHERE External_Key__c = :leadWrap.State];*/
            Lead newLead = new Lead();
            newLead.Company = leadWrap.Company;
            newLead.Email = leadWrap.Email;
            newLead.Status = leadWrap.Status;
            newLead.Industry = leadWrap.Industry;
            newLead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Regular Lead').getRecordTypeId();
            newLead.OnlineRegistered__c = leadWrap.OnlineRegistered;
            newLead.Country__c = leadWrap.Country;
            newLead.BillToSameasSupportTo__c = leadWrap.BillToSameasSupportTo;
            newLead.Region__c = leadWrap.Region;
            newLead.FirstName = leadWrap.FirstName;
            newLead.LastName = leadWrap.LastName;
            newLead.City__c = leadWrap.City;
            newLead.Phone = leadWrap.Phone;
            newLead.Postal_code__c = leadWrap.Postalcode;
            newLead.External_Id__c = leadWrap.ExternalId;
            newLead.Website = leadWrap.Website;
            newLead.PAN__c = leadWrap.PAN;
            newLead.Fax = leadWrap.Fax;
            newLead.Company_Type__c = leadWrap.CompanyType;
            newLead.Country_Code__c = leadWrap.CountryCode;
            newLead.Lead_Remarks__c = leadWrap.LeadRemarks;
            newLead.YottaIndustry__c = leadWrap.YottaIndustry;
            newLead.LeadContactsAuthorityLevel__c = leadWrap.LeadContactsAuthorityLevel;
            newLead.Description = leadWrap.Description;
            newLead.MobilePhone = leadWrap.MobilePhone;
            newLead.Contact_External_Id__c = leadWrap.ContactExternalId;
            newLead.Address_External_Id__c = leadWrap.AddressExternalId;
            newLead.State_External_Key__c = leadWrap.State;
            /*if (sat != null) {
                newLead.State__c = sat.Id;
            }*/

            System.debug('New Lead: --' + newLead);
            insert newLead;

            convertLeads.add(newLead);
            //Auto Lead Convert
            /*List<Database.LeadConvertResult> lcr = ConvertLead.Autoconvert(new List<Lead>{
                    newLead
            });*/

            Set<String> leadCompanies = new Set<String>();
            Set<String> leadEmails = new Set<String>();
            for(Lead l: convertLeads){
                leadCompanies.add(l.Company);
                leadEmails.add(l.Email);
            }

            List<Account> accountList = [Select id, name,(Select id, AccountId, Email from Contacts where email =: leadEmails) from Account where name =: leadCompanies];
            system.debug('accountList' + accountList);
            Map<String, Id> accountNameIdMap = new Map<String, Id>();
            Map<String, Contact> contactEmailMap = new Map<String, Contact>();
            for(Account a:accountList){
                accountNameIdMap.put(a.name.toLowercase(), a.id);
                for(Contact c: a.Contacts){
                    contactEmailMap.put(c.Email.toLowercase(), c);
                }
            }
            

            List<Database.LeadConvert> MassLeadconvert = new List<Database.LeadConvert>();
            for(Lead currentlead : convertLeads){
                //if(!(accountNameIdMap.containsKey(currentlead.Company) && contactEmailMap.containsKey(currentlead.Email))){
                if(!contactEmailMap.containsKey(currentlead.Email.toLowercase()) || (contactEmailMap.containsKey(currentlead.Email.toLowercase()) && accountNameIdMap.containsKey(currentlead.Company.toLowercase()) && contactEmailMap.get(currentlead.Email.toLowercase()).AccountId == accountNameIdMap.get(currentlead.Company.toLowercase()))){
                    Database.LeadConvert Leadconvert = new Database.LeadConvert();
                    Leadconvert.setLeadId(currentlead.id);
                    Leadconvert.setConvertedStatus('Assigned to Sales');
                    if(accountNameIdMap.containsKey(currentlead.Company.toLowercase()))
                        Leadconvert.setAccountId(accountNameIdMap.get(currentlead.Company.toLowercase()));
                    if(contactEmailMap.containsKey(currentlead.Email.toLowercase()))
                        Leadconvert.setContactId(contactEmailMap.get(currentlead.Email.toLowercase()).id);
                    Leadconvert.setDoNotCreateOpportunity(TRUE);

                    MassLeadconvert.add(Leadconvert);
                }
            }
            if (!MassLeadconvert.isEmpty()) {
                List<Database.LeadConvertResult> lcr = Database.convertLead(MassLeadconvert);


                if (!lcr.isEmpty()) {
                    AccountCreated = [SELECT Id,Account_Number__c,(SELECT Id,Contact_Id__c FROM Contacts WHERE Id = :lcr[0].getContactId()) FROM Account WHERE Id = :lcr[0].getAccountId()];
                    ContactCreated = AccountCreated.Contacts;
                }
            }
            System.debug('Account Created'+AccountCreated);
            System.debug('Contact Created'+ContactCreated);
            System.debug('Account Created - Debug'+newLead.ConvertedAccount.Account_Number__c);
            System.debug('Contact Created - Debug'+newLead.ConvertedContact.Contact_Id__c);

            resWrap.Success = true;
            resWrap.Message = 'Lead Created:'+ newLead.Id;
            resWrap.LeadExternalId = newLead.External_Id__c;
            resWrap.AccountNumber = AccountCreated.Account_Number__c == null ? 'Empty' : AccountCreated.Account_Number__c;
            resWrap.ContactNumber = ContactCreated.Contact_Id__c == null ? 'Empty' : ContactCreated.Contact_Id__c;


            if(resWrap != null){
                res.statusCode = 200;
                res.responseBody = Blob.valueOf(JSON.serialize(resWrap));
            }else{
                res.statusCode = 400;
            }

        } catch (Exception e) {
            RestResponse res = RestContext.response;
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(JSON.serialize(e.getMessage()));
        }
    }

    public class ResponseWrapper {
        public boolean Success;
        
        public String Message;
        public String LeadExternalId;
        public String AccountNumber;
        public String ContactNumber;
    }


    public class LeadWrapper {
        public String Company;    //XYZ Tests101 Company
        public String MobilePhone;    //9004732556
        public String Email;    //testv15g@gmail.com
        public String Status;    //Open
        public String Industry;    //Manufacturing
        public boolean OnlineRegistered;
        public String LeadContactsAuthorityLevel;    //Tier 1: C Level / VP IT / Director Level / Key Decision Makers
        public String YottaIndustry;    //Automotive
        public String Country;    //IN
        public String Region;    //West
        public String LeadRemarks;    //Test
        public String CountryCode;    //91
        public String CompanyType;    //Private Limited
        public String FirstName;    //Test
        public String LastName;    //Lead
        public String Vertical_Temp;    //Manufacturing
        public String Postalcode;    //421306
        public String State;    //a2I1m0000004JkMEAU
        public String City;
        public String Description;
        public String Fax;
        public String PAN;
        public String Phone;
        public String Website;
        public String ExternalId;
        public Boolean BillToSameasSupportTo;
        public String ContactExternalId;
        public String AddressExternalId;

    }

}