force-app/main/default/objects/Account/fields/BD_Manager__c.field-meta.xml
<CustomField>
    <fullName>BD_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BD_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/KYC_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Approval_Status__c</fullName>
    <inlineHelpText>This denotes the KYC Approval status of the Account.</inlineHelpText>
    <label>KYC Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not-Submitted</fullName>
                <default>true</default>
                <label>Not-Submitted</label>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <description>Field to be manually updated only by order manager and visible in partner community</description>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <label>Partner Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Inactive Partner</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>Deboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Send Record To Kafka</inlineHelpText>
    <label>Send To Kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerController__c/TriggerController__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerController</label>
</CustomObject>

force-app/main/default/objects/TriggerController__c/fields/DeactivateObjectTrigger__c.field-meta.xml
<CustomField>
    <fullName>DeactivateObjectTrigger__c</fullName>
    <label>DeactivateObjectTrigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apparel &amp; Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Broadcast (TV, Radio, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Cargo &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Central Government</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Products</fullName>
    </customValue>
    <customValue>
        <fullName>Content Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Content Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Content Processing</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Global BFSI centers</fullName>
    </customValue>
    <customValue>
        <fullName>Global CDN Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global Internet Exchanges</fullName>
    </customValue>
    <customValue>
        <fullName>Global ISP</fullName>
    </customValue>
    <customValue>
        <fullName>Global TSP</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hi-tech and electronic</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Hoster &amp; Local DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Software Vendor (ISV)</fullName>
    </customValue>
    <customValue>
        <fullName>Info Tech Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>ITES/BPO/KPO</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
        <isActive>false</isActive>
        <label>Manufacturing</label>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest {
    
    @testSetup
    public static void createData(){
        //create trigger controller
        TriggerController__c tc = new TriggerController__c(DeactivateObjectTrigger__c = '', isActive__c = TRUE);
        insert tc;
    }

    @isTest
    public static void createAccountAndSendToKafka()
    {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User user = new User(
                Username = 'yottamanager@example.com',
                Email = 'yottamanager@example.com',
                FirstName='Yotta',
                LastName = 'Manager',
                Alias = 'TUser',
                ProfileId = profile.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8'
        );
        insert user;
        //insert account
        Account acc = new Account(Name = 'Acc Name', Industry = 'Manufacturing', YottaIndustry__c = 'Automotive', Send_to_API_Layer__c = false ,Partner_Manager__c = user.Id,BD_Manager__c = user.Id);
        insert acc;
        //system.assertEquals(0, [Select count() from Integration_Message__c Where Account__c =: acc.Id]);
        Test.startTest();
        //send record to kafka by changing envelope fields
        Account objUpdatedAccount = new Account(Id=acc.Id);
        objUpdatedAccount.Industry = 'BFSI';
        objUpdatedAccount.YottaIndustry__c = 'FinTech';
        //objUpdatedAccount.PartnerType__c = 'Alliance Partner';
        objUpdatedAccount.Type = 'Customer';
        objUpdatedAccount.KYC_Approval_Status__c = 'Approved';
        objUpdatedAccount.KYC_Status__c = 'Complete';
        objUpdatedAccount.Partner_Manager__c = null;
        objUpdatedAccount.BD_Manager__c = null;
        update objUpdatedAccount;

        Test.stopTest();

    }










}