force-app/main/default/objects/Account/fields/Name_Change_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Name_Change_Effective_Date__c</fullName>
    <label>Name Change Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Adr-{00000}</displayFormat>
        <label>Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Tenure_Days__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Days__c</fullName>
    <label>Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Tenure_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Months__c</fullName>
    <label>Months</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Tenure_Years__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Years__c</fullName>
    <label>Years</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorised_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Authorised Signatory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Customer Authorised Signatory)</relationshipLabel>
    <relationshipName>Contracts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Contact Billing Contact)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_SPoC__c.field-meta.xml
<CustomField>
    <fullName>Customer_SPoC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer SPoC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Support_To_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Existing_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Existing_Billing_Address__c</fullName>
    <label>Existing Billing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Name_Change_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Name_Change_Effective_Date__c</fullName>
    <label>Name Change Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Master_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Master_Contract_Id__c</fullName>
    <label>Original Master Contract Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Quotes (Bill To Address)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contract_Tenure_Days__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Days__c</fullName>
    <label>Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorised_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GG: 26-Oct Created to get the Contact from Contract then make it available for update on Contract.</description>
    <label>Customer Authorised Signatory</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria- Customer Authorised</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Authorised Signatory)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Billing Contact)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_SPoC__c.field-meta.xml
<CustomField>
    <fullName>Customer_SPoC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GG: 26-Oct Created to get the Contact from Contract then make it available for update on Contract.</description>
    <label>Customer SPoC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria-Customer SPOC.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Support_To_Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer SPoC)</relationshipLabel>
    <relationshipName>Quotes4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Original_Master_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Master_Contract_Id__c</fullName>
    <label>Original Master Contract Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/SCF.recordType-meta.xml
<RecordType>
    <fullName>SCF</fullName>
    <active>true</active>
    <description>Used for SCF/Amendment Quotes</description>
    <label>SCF</label>
</RecordType>

force-app/main/default/classes/SCFAddressChangeController.cls
/* ****************************************************************************************************************
Name          : SCFAddressChangeController
Description   : It is used for address change and bill cycle change pdf to fetch required data from quote 
on Quote
Author        : Riya Sharma(Compro Technologies)

**************************************************************************************************************** */
public without sharing class SCFAddressChangeController {
    
    
    public static string errorMessage {get;set;}
    public static Id FileId;
    public String quoteId{get;set;}
    public SBQQ__Quote__c quote{get;set;}
    public Integer remainingYears {get;set;}
    public Integer remainingMonths {get;set;}
    public Integer remainingDays {get;set;}
    public Contract originalContract {get; set;}    
    
    public SCFAddressChangeController(ApexPages.StandardController stdController) {
        //gets the current id of the quote page
        quoteId = ApexPages.currentPage().getParameters().get('id');
        
        quote = [Select SBQQ__MasterContract__c, Original_Master_Contract_Id__c, toLabel(SBQQ__MasterContract__r.Business_Unit__c), SBQQ__MasterContract__r.SBQQ__AmendmentStartDate__c,SBQQ__MasterContract__r.StartDate from SBQQ__Quote__c where id =: quoteId ];
        Id contractId = quote.SBQQ__MasterContract__c;
        if(contractId == NULL){
            contractId = quote.Original_Master_Contract_Id__c;
        }
        if(contractId != NULL){
            System.debug('quote.Original_Master_Contract_Id__c'+quote.Original_Master_Contract_Id__c);
            originalContract = [SELECT Id, Contract_Tenure_Years__c, Contract_Tenure_Months__c,EndDate, Contract_Number__c, 
                                Customer_Authorised_Signatory__r.Name, Customer_Authorised_Signatory__r.Title, Customer_Authorised_Signatory__r.Email, Customer_Authorised_Signatory__r.MobilePhone, 
                                Contract_Tenure_Days__c, Customer_SPoC__r.Name, Customer_SPoC__r.Email,
                                Customer_SPoC__r.Phone, Customer_Billing_Contact__r.Name, Customer_Billing_Contact__r.Email,
                                Customer_Billing_Contact__r.Phone, Owner.Name, Owner.Email, Owner.Phone, ContractNumber, 
                                Bill_To_Address__r.AddressLine1__c, Bill_To_Address__r.AddressLine2__c,
                                Bill_To_Address__r.City__c, Business_Unit__c, SBQQ__AmendmentStartDate__c, 
                                StartDate FROM Contract WHERE Id =: contractId];
        }        
        
        remainingContract();
    }
    
    public void remainingContract(){
        
        //gets remaining days from contract to be used in pdf
               Date StartDate = originalContract.SBQQ__AmendmentStartDate__c - 1;
        Date EndDate = originalContract.EndDate  ;
        System.debug('originalContract.SBQQ__AmendmentStartDate__c' + originalContract.SBQQ__AmendmentStartDate__c);
          Integer months = originalContract.SBQQ__AmendmentStartDate__c.monthsBetween(EndDate);
         if (StartDate.day() > EndDate.day()) {          
            months--;
        }
        Date rolledBackEndDate = EndDate.addMonths(0 - months);
        Integer years =(Integer) Math.floor(months / 12.0);
        months = months - (years * 12);
        Integer days =  StartDate.daysBetween(rolledBackEndDate);
        remainingYears = years;
        remainingMonths = months;
        remainingDays = days;

        //remainingDays = originalContract.SBQQ__AmendmentStartDate__c.daysBetween(originalContract.EndDate);
        //remainingYears = originalContract.EndDate.year() - originalContract.SBQQ__AmendmentStartDate__c.year();
    }
    /*
//gets scf type from contract if its bill cycle change or address change
@AuraEnabled
public static String getSCFType(Id RecordId){
Contract con = [Select 	SCF_Type__c from Contract where id= :RecordId];
String scfType = con.SCF_Type__c;
return scfType;
}


//This function helps save the pdf as file on contract if user saves the pdf.
@AuraEnabled
public static void SavePDFAsFile(Id RecordId)
{   
System.debug(RecordId);
System.debug('SavePDFAsFile' +  RecordId);   
string pdfURL= '/apex/SCFAddressChange?id=' +RecordId;
PageReference pdf = new PageReference(pdfURL);
Blob pdfBody;

System.debug('inside If SavePDFAsFile');
if(Test.isRunningTest()) {
pdfBody = blob.valueOf('Unit.Test');
} else {
pdfBody = pdf.getContent();
}

ContentVersion cont = new ContentVersion();
cont.VersionData = pdfbody;
System.debug('VersionData');
String currentDateTime = System.now().format();
cont.title = 'SCF-' +RecordId +'-'+currentDateTime + '.pdf';

System.debug('currentDateTime  is'+ currentDateTime );
cont.pathOnClient = 'PO-' + RecordId  +'-'+currentDateTime + '.pdf';
System.debug('tempAccountId:::::::' +RecordId);
cont.FirstPublishLocationId = RecordId;
System.debug('ContentVersion:::::::' +cont);
insert cont;
ContentVersion insertedcont = [Select ContentDocumentId from ContentVersion where ID =:cont.Id ][0]; 
FileId= cont.Id; // FileId= insertedcont.ContentDocumentId;

System.debug('FileId::'+FileId); 

}

//This function checks if required fields are available on the contract record to view pdf and sends error in case such a 
//field is missing
@AuraEnabled
public static ContractWrapper isValidContract(Id ConId)
{   
ContractWrapper contWrapper;

String errorMsg='Error:';
Boolean isError=false;
Contract cont = [Select Account.Name,ContractNumber,StartDate,Bill_To_Address__c,
Customer_SPoC__c,Existing_Billing_Address__c,Name_Change_Effective_Date__c
from Contract where Id =: ConId];

try{
if(cont.Account.Name == null)
{
System.debug('Error: Account name is not available.');
errorMsg+='Account name is not available';
isError = true;

}
if(cont.Account.Name == null)
{
System.debug('Error: Bill to Account field is not available.');
errorMsg+='Bill to Account field is not available';
isError = true;


}
if(cont.StartDate == null)
{
System.debug('Error: StartDate is not available.');
errorMsg+='StartDate is not available';
isError = true; 

}
if(cont.Bill_To_Address__c == null)
{
System.debug('Error: Bill To Address is not available.');
errorMsg+='Bill To Address is not available';
isError = true;

}
if(cont.Customer_SPoC__c == null)
{
System.debug('Error: Customer SPoC is not available.');
errorMsg+='Customer SPoC is not available';
isError = true;

}
if(cont.Name_Change_Effective_Date__c == null)
{
System.debug('Error: Name Change Effective Date is not available.');
errorMsg+='Name Change Effective Date is not available';
isError = true;


}


System.debug('cont is '+cont);
if(isError){

contWrapper = new ContractWrapper( isError, errorMsg);
System.debug('contWrapper inside if is'+contWrapper);
return contWrapper;
}else{
contWrapper = new ContractWrapper(isError, '');
System.debug('contWrapper inside else is'+contWrapper);
return contWrapper;
}

}
catch(Exception e)
{
System.debug('Exception:::'+e);
contWrapper = new ContractWrapper(true, e.getMessage());
return contWrapper;
// return err = 'ERROR in generating document ' + e.getMessage();
}

}

//Wrapper class for contract to store the error messages in case if a required field to show pdf is missing
public class ContractWrapper{
@AuraEnabled public Boolean isError;
@AuraEnabled public String errorMsg;
public ContractWrapper(Boolean isError, String errorMsg){
this.isError = isError;
this.errorMsg = errorMsg;
}
}

*/
    
    
}