force-app/main/default/objects/Account/fields/Name_Change_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Name_Change_Effective_Date__c</fullName>
    <label>Name Change Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/New_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Name__c</fullName>
    <label>New Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <label>Partner Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Inactive Partner</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>Deboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactType__c.field-meta.xml
<CustomField>
    <fullName>ContactType__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Business Contact</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>IT Management</fullName>
            </value>
            <value>
                <fullName>IT Operations</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
                <label>Technical Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Commision_Model__c.field-meta.xml
<CustomField>
    <fullName>Partner_Commision_Model__c</fullName>
    <label>Partner Commision Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Model A</fullName>
            </value>
            <value>
                <fullName>Model B</fullName>
            </value>
            <value>
                <fullName>TP</fullName>
                <label>Transfer Price</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PartnerSecondary__c.field-meta.xml
<CustomField>
    <fullName>PartnerSecondary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner - Secondary</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5) OR 6</booleanFilter>
        <filterItems>
            <field>Account.Partner_Check__c</field>
            <operation>contains</operation>
            <valueField>$Source.SecondarySource__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__Renewal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__AmendedContract__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__Renewal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__RenewedContract__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__AmendedContract__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner - Secondary)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PartnerTertiary__c.field-meta.xml
<CustomField>
    <fullName>PartnerTertiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner - Tertiary</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5) OR 6</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria- Tertiary Source.</errorMessage>
        <filterItems>
            <field>Account.Partner_Check__c</field>
            <operation>contains</operation>
            <valueField>$Source.TertiarySource__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__Renewal__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__AmendedContract__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__Renewal__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__RenewedContract__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.SBQQ__AmendedContract__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner - Tertiary)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TertiarySource__c.field-meta.xml
<CustomField>
    <fullName>TertiarySource__c</fullName>
    <label>Tertiary Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Business Development - Digital</fullName>
            </value>
            <value>
                <fullName>Leadership Leads</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>YCIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Partner_Commision_Model__c.field-meta.xml
<CustomField>
    <fullName>Partner_Commision_Model__c</fullName>
    <label>Partner Commision Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Model A</fullName>
            </value>
            <value>
                <fullName>Model B</fullName>
            </value>
            <value>
                <fullName>TP</fullName>
                <label>Transfer Price</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Use_Transfer_Price__c.field-meta.xml
<CustomField>
    <fullName>Use_Transfer_Price__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Transfer Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
@isTest
public class OpportunityTriggerHandlerTest {
    
    @testSetup
    public static void testDataSetup() {
        TestDataFactory.createTriggerCustomSettings();
    }
    
    public static testmethod void testOppShare() {
        Account objAcc = TestDataFactory.createAccount();
        Id oppId;
        Id SecId;
        
        objAcc.PartnerType__c = 'Alliance Partner';
        objAcc.Partner_Manager__c = '0052u000000Ehr2AAC';
        insert objAcc;
        objAcc.IsPartner = True;
        Update objAcc;
        
        Contact objCon = new Contact();
        objCon.AccountId = objAcc.id;
        objCon.Email='test@gmail.com';
        objCon.ContactType__c='Primary';
        objCon.FirstName = 'Test';
        objCon.LastName = 'Test';
        objCon.Department='commercial';	
        objCon.Status__c = 'Active';
        objCon.MobilePhone = '9999998875';
        
        insert objCon;
        
        Account objAccount = new Account();
        objAccount.Name = 'Test -' + String.valueOf(System.now().getTime());
        // objAccount.New_Customer_Name__c = ' Name Test';
        //objAccount.Name_Change_Effective_Date__c = System.today();
        objAccount.PartnerType__c = 'Alliance Partner';
        objAccount.Partner_Manager__c = objAcc.Partner_Manager__c;
        insert objAccount;
        objAccount.IsPartner = True;
        Update objAccount;
        
        Contact objCont = new Contact();
        objCont.AccountId = objAccount.id;
        objCont.Email='test1@gmail.com';
        objCont.ContactType__c='Primary';
        objCont.FirstName = 'Test';
        objCont.LastName = 'Test1';
        objCont.Department='commercial';	
        objCont.Status__c = 'Active';
        objCont.MobilePhone = '9999998775';
        
        insert objCont;                                                
        
        Profile p = [Select ID, Name from Profile Where Name = 'Yotta Partners Profile'];
        
        user u = New User(
            UserName = 'test_' + math.random() + '@test.com',
            FirstName = 'Test-First',
            LastName = 'Test-Last',
            Alias = 'test',
            email = 'test' + math.random() + '@test.com',
            CommunityNickName = string.valueOf(math.random()).substring(0,6),
            ProfileID = p.id,
            TimeZoneSidKey = 'America/New_York', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            LanguageLocaleKey = 'en_US',
            ContactID = objCont.Id
            
        );
        
        insert u;
        Profile pro = [Select ID, Name from Profile Where Name = 'Yotta Partners Profile'];
        
        user us = New User(
            UserName = 'test_' + math.random() + '@test.com',
            FirstName = 'Test-First',
            LastName = 'Test-Last',
            Alias = 'test',
            email = 'test' + math.random() + '@test.com',
            CommunityNickName = string.valueOf(math.random()).substring(0,6),
            ProfileID = pro.id,
            TimeZoneSidKey = 'America/New_York', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            LanguageLocaleKey = 'en_US',
            ContactID = objCon.Id
            
        );
        
        insert us;
      
        Test.startTest();
        List<Opportunity> OppList = TestDataFactory.createOpportunity(1,objAcc.Id);
        List<Account> acc = [Select Id,name,IsPartner from Account where isPartner = true];
        System.debug('Partner Account' + acc);
        for(Opportunity objOpp:OppList ){
            oppId = objOpp.Id ;
            objOpp.SecondarySource__c = 'Alliance Partner';
            objOpp.PartnerSecondary__c =  acc[0].Id;
            objOpp.End_Customer_Address__c = 'Mumbai';
            objOpp.End_Customer_City__c = 'Mumbai';
            objOpp.Partner_Commision_Model__c = 'TP';
           
            
            if(acc.size()>1){
                objOpp.TertiarySource__c = 'Alliance Partner';
                objOpp.PartnerTertiary__c =  acc[1].Id;
            }
           
            insert OppList;
            
            for(Opportunity objOp:OppList ){
                if(acc.size()>1){
                    objOp.TertiarySource__c = 'Sales';
                    objOp.PartnerTertiary__c =  null;
                }
            }
                update OppList;
            
            
            
            /* SBQQ__Quote__c Quote = new SBQQ__Quote__c();
             Quote.Use_Transfer_Price__c = true;
             Quote.Partner_Commision_Model__c = 'TP';
             Quote.SBQQ__Primary__c = true ;
             Quote.SBQQ__Opportunity2__c = objOpp.Id;
             Quote.SBQQ__Type__c = 'Amendment';
             insert Quote;
            
             Opportunity opp = new Opportunity();
             opp.SBQQ__PrimaryQuote__c = Quote.SBQQ__Type__c;
             insert opp; */
           
                Test.stopTest();
            }
        }
        
        
    }