force-app/main/default/objects/Account/fields/OMT_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>OMT_Approval_Status__c</fullName>
    <inlineHelpText>This denotes the Name Change SCF Approval Status of the Account.</inlineHelpText>
    <label>OMT Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Not - Submitted</fullName>
                <default>true</default>
                <label>Not - Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/OMT_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>OMT_Approval_Status__c</fullName>
    <label>OMT Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not-Submitted</fullName>
                <default>true</default>
                <label>Not-Submitted</label>
            </value>
            <value>
                <fullName>In-Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <label>Approved</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
            <value>
                <fullName>DEL</fullName>
                <isActive>false</isActive>
                <label>DEL</label>
            </value>
            <value>
                <fullName>IN13</fullName>
                <isActive>false</isActive>
                <label>Navi Mumbai – DC2</label>
            </value>
            <value>
                <fullName>IN22</fullName>
                <isActive>false</isActive>
                <label>YNS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <isActive>false</isActive>
                <label>YNS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN23</fullName>
                <isActive>false</isActive>
                <label>YNS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN21</fullName>
                <isActive>false</isActive>
                <label>YNS Mumbai – HO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <label>Sale Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZTAD</fullName>
                <label>Sale of Service</label>
            </value>
            <value>
                <fullName>ZTAN</fullName>
                <label>Sale of Equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Dimension__c/SBQQ__Dimension__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__PriceDimensionHelp</customHelpPage>
    <label>Price Dimension</label>
    <nameField>
        <label>Dimension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Dimensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Component_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Component_Quantity__c</fullName>
    <label>Quantity/Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <defaultValue>&quot;Navi Mumbai – DC1&quot;</defaultValue>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <default>true</default>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <description>TWIN Field from Product</description>
    <label>Sale Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZTAD</fullName>
                <label>Sale of Service</label>
            </value>
            <value>
                <fullName>ZTAN</fullName>
                <label>Sale of Equipment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RenewalReminderControllerTest.cls
@isTest
global class RenewalReminderControllerTest {
    @isTest
    global static void RenewalReminderControllerTest(){
        
        Account accountList = TestDataFactory.createAccount();
        insert accountList;
        System.debug('Id.valueOf(accountList.Id)' + Id.valueOf(accountList.Id));
        
        List<Opportunity> opportunityList = TestDataFactory.createOpportunity(1,Id.valueOf(accountList.Id));
        insert opportunityList;        
        System.debug('Id.valueOf(opportunityList.Id)' + Id.valueOf(opportunityList[0].Id));
        
        // Id quoteId = Id.valueOf(quoteList[0].Id);
        Sbqq__Quote__c quote = new Sbqq__Quote__c();
        quote.Quote_Name__c = 'Test';
        quote.SBQQ__Account__c = Id.valueOf(accountList.Id);
        quote.SBQQ__StartDate__c=System.today().addMonths(1);
        quote.SBQQ__Opportunity2__c= Id.valueOf(opportunityList[0].Id);
        insert quote;
        
        List<Contract> contractList = TestDataFactory.createContract(1,Id.valueOf(accountList.Id));
        for(Contract objContract : contractList ) {
            //objContract.OMT_Approval_Status__c = 'Approved';
            objContract.SBQQ__Quote__c = quote.Id;
            objContract.ContractTerm = 100;
            objContract.Name = 'Test Contract Number';
            objContract.SBQQ__Opportunity__c = Id.valueOf(opportunityList[0].Id);
            objContract.Business_Unit__c='IN10';
            objContract.Document_Status__c = 'Complete';
            objContract.OMT_Approval_Status__c = 'Approved';
            
        }
        insert contractList;
        
        List<Product2> productList = TestDataFactory.createProduct(1);
        productList[0].Sale_Type__c='ZTAN';
        insert productList;        
        System.debug('Id.valueOf(productList.Id)' + Id.valueOf(productList[0].Id));
        
        List<Sbqq__Dimension__c> dimensionList = TestDataFactory.createDimension(1,Id.valueOf(productList[0].Id));
        insert dimensionList;
        
        List<Sbqq__QuoteLine__c> QuoteLineList = TestDataFactory.createParentQuoteLine(1, Id.valueOf(quote.Id),Id.valueOf(productList[0].Id),Id.valueOf(dimensionList[0].Id));
        insert QuoteLineList;
        
        
        
        Sbqq__QuoteLine__c a = new Sbqq__QuoteLine__c (SBQQ__Quote__c = quote.Id , Location__c = 'IN12',
                                                           SBQQ__Quantity__c=2,SBQQ__Product__c=Id.valueOf(productList[0].Id),
                                                           SBQQ__RequiredBy__c=Id.valueOf(quoteLineList[0].Id),SBQQ__Number__c=2,
                                                           SBQQ__Dimension__c=Id.valueOf(dimensionList[0].Id),Component_Quantity__c=2,
                                                           SBQQ__NetPrice__c =100,
                                                        SBQQ__Description__c = 'Test'
                                                          );
       
        insert a;   
        // Initialize VF setup
        ApexPages.CurrentPage().getParameters().put('id', quote.id);
        PageReference pageRef = ApexPages.currentPage();
        Test.setCurrentPage(pageRef);
         
         RenewalReminderController controller = new RenewalReminderController();
         controller.quoteId = quote.Id;
         Map<String, RenewalRemWrapper.ParentWrapper> lsr = controller.QuoteLines;
        
         RenReminder60Controller controller1 = new RenReminder60Controller();
         controller1.conId =  Id.valueOf(contractList[0].Id);
         Date enddate = controller1.endDate65;
        
         RenReminderCont controller2 = new RenReminderCont();
         controller2.conId =  Id.valueOf(contractList[0].Id);
         Date endate = controller2.endDate45;
        
        SOFEmailComponentController controller3 = new SOFEmailComponentController();
         controller3.recId =  Id.valueOf(contractList[0].Id);
        Contract contract = controller3.contract;
        
        

        
       
        
        
    }
}