force-app/main/default/objects/Account/fields/Partner_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerType__c.field-meta.xml
<CustomField>
    <fullName>PartnerType__c</fullName>
    <label>Partner Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Inactive Partner</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>Deboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Primary_Campaign__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Account/&quot; &amp; Primary_Campaign_Id__c &amp;&quot;/view&quot;, Primary_Campaign_Name__c ,&quot;_top&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Campaign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Campaign__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Account/&quot; &amp; Secondary_Campaign_Id__c &amp;&quot;/view&quot;, Secondary_Campaign_Name__c ,&quot;_top&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Campaign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tertiary_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Campaign__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Account/&quot; &amp; Tertiary_Campaign_Id__c &amp;&quot;/view&quot;, Tertiary_Campaign_Name__c ,&quot;_top&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tertiary Campaign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Auto_Convert__c.field-meta.xml
<CustomField>
    <fullName>Auto_Convert__c</fullName>
    <description>To trigger auto conversion code</description>
    <label>Auto Convert?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Creator__c.field-meta.xml
<CustomField>
    <fullName>Creator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partner_Manager__c.field-meta.xml
<CustomField>
    <fullName>Partner_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PartnerManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partner_Primary__c.field-meta.xml
<CustomField>
    <fullName>Partner_Primary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner - Primary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Partner_Check__c</field>
            <operation>contains</operation>
            <valueField>$Source.PrimarySource__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner - Primary)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partner_Secondary__c.field-meta.xml
<CustomField>
    <fullName>Partner_Secondary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner - Secondary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Partner_Check__c</field>
            <operation>contains</operation>
            <valueField>$Source.SecondarySource__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner - Secondary)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partner_Tertiary__c.field-meta.xml
<CustomField>
    <fullName>Partner_Tertiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner - Tertiary</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Partner_Check__c</field>
            <operation>contains</operation>
            <valueField>$Source.TertiarySource__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner - Tertiary)</relationshipLabel>
    <relationshipName>Leads3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Primary_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Primary_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>PrimaryLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimarySource__c.field-meta.xml
<CustomField>
    <fullName>PrimarySource__c</fullName>
    <label>Primary Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Business Development - Digital</fullName>
            </value>
            <value>
                <fullName>Leadership Leads</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>YCIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads (Secondary Campaign)</relationshipLabel>
    <relationshipName>SecondaryLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SecondarySource__c.field-meta.xml
<CustomField>
    <fullName>SecondarySource__c</fullName>
    <label>Secondary Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Business Development - Digital</fullName>
            </value>
            <value>
                <fullName>Leadership Leads</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>YCIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Tertiary_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tertiary Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads (Tertiary Campaign)</relationshipLabel>
    <relationshipName>TertiaryLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <businessProcess>Partner Registration</businessProcess>
    <label>Partner</label>
</RecordType>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
//****** Test Class for Trigger LeadTrigger ******
//****** Test Class for Class LeadTriggerHandler ******
//****** Test Class for Class AutoLeadConvertBatch ******

@isTest
public class LeadTriggerHandlerTest {
	
    @testSetup
    public static void testDataSetup() {
        TestDataFactory.createTriggerCustomSettings();
    }
    
    public static testmethod void testLeadShare() {
    	Lead objLead = TestDataFactory.createLead();
        objLead.OwnerId = [Select Id from Group where Name='IS Team' And Type='Queue'].Id;
        User objUser = [Select Id from User where Profile.Name='B2BMA Integration User' And isActive=true LIMIT 1];
        Test.startTest();
        system.runAs(objUser){
            insert objLead;
        }
        system.assertEquals(1, [Select count() from LeadShare where LeadId =: objLead.Id and RowCause='Manual' And UserOrGroupId=:objUser.Id]);
        Test.stopTest();
        
        objLead.Creator__c = UserInfo.getUserId();
        update objLead;
        system.assertEquals(1, [Select count() from LeadShare where LeadId =: objLead.Id and RowCause='Manual' And UserOrGroupId=:objLead.Creator__c]);
    }
    
    public static testmethod void testAutoLeadConvert() {
        
        Campaign camp1 = TestDataFactory.createCampaign();
        Campaign camp2 = TestDataFactory.createCampaign();
        Campaign camp3 = TestDataFactory.createCampaign();
        
        insert new List<Campaign>{ camp1, camp2, camp3 };
        
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Regular Lead').getRecordTypeId();
        
        Lead newAnewC = TestDataFactory.createLead();
        newAnewC.RecordTypeId = recordTypeId;
        newAnewC.Auto_Convert__c = 'Yes';
        newAnewC.Primary_Campaign__c = camp1.Id;
        newAnewC.Secondary_Campaign__c = camp2.Id;
        newAnewC.Tertiary_Campaign__c = camp3.Id;
        newAnewC.PrimarySource__c = 'Marketing';
        newAnewC.SecondarySource__c = 'Marketing';
        newAnewC.TertiarySource__c = 'Marketing';
        
        Lead oldAnewC = TestDataFactory.createLead();
        oldAnewC.RecordTypeId = recordTypeId;
        oldAnewC.Email += 'newC';
        oldAnewC.Auto_Convert__c = 'Yes';
        oldAnewC.Primary_Campaign__c = camp1.Id;
        oldAnewC.Secondary_Campaign__c = camp2.Id;
        oldAnewC.Tertiary_Campaign__c = camp3.Id;
        oldAnewC.PrimarySource__c = 'Marketing';
        oldAnewC.SecondarySource__c = 'Marketing';
        oldAnewC.TertiarySource__c = 'Marketing';
        
        Lead oldAOldC = TestDataFactory.createLead();
        oldAOldC.RecordTypeId = recordTypeId;
        oldAOldC.Auto_Convert__c = 'Yes';
        oldAOldC.Primary_Campaign__c = camp1.Id;
        oldAOldC.Secondary_Campaign__c = camp2.Id;
        oldAOldC.Tertiary_Campaign__c = camp3.Id;
        oldAOldC.PrimarySource__c = 'Marketing';
		oldAOldC.SecondarySource__c = 'Marketing';
        oldAOldC.TertiarySource__c = 'Marketing';
        
        Lead newAOldC = TestDataFactory.createLead();
        newAOldC.RecordTypeId = recordTypeId;
        //newAOldC.Company += 'newA';
        newAOldC.Auto_Convert__c = 'Yes';
        newAOldC.Primary_Campaign__c = camp1.Id;
        newAOldC.Secondary_Campaign__c = camp2.Id;
        newAOldC.Tertiary_Campaign__c = camp3.Id;
		newAOldC.PrimarySource__c = 'Marketing';
        newAOldC.SecondarySource__c = 'Marketing';
        newAOldC.TertiarySource__c = 'Marketing';
        
        Test.startTest();
        insert new List<Lead>{newAnewC, oldAnewC, oldAOldC, newAOldC};
        /*insert newAnewC;
        insert oldAnewC;
        insert oldAOldC;
        insert newAOldC;*/
        Test.stopTest();
    }
    
    public static testmethod void testAutoLeadConvert_partner() {
        
        Account acc1 = TestDataFactory.createAccount();
        Account acc2 = TestDataFactory.createAccount();
        Account acc3 = TestDataFactory.createAccount();
        
        insert new List<Account>{ acc1, acc2, acc3 };
            
        acc1.PartnerType__c = 'Alliance Partner,Consultant Partner,Marketing';
        acc2.PartnerType__c = 'Alliance Partner,Consultant Partner,Marketing';
        acc3.PartnerType__c = 'Alliance Partner,Consultant Partner,Marketing';
        acc1.Partner_Manager__c = System.UserInfo.getUserId();
         acc2.Partner_Manager__c = System.UserInfo.getUserId();
         acc3.Partner_Manager__c = System.UserInfo.getUserId();
        
        update acc1;
        update acc2;
        update acc3;
        
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Regular Lead').getRecordTypeId();
        
        Lead newAnewC = TestDataFactory.createLead();
        newAnewC.RecordTypeId = recordTypeId;
        newAnewC.Auto_Convert__c = 'Yes';
        newAnewC.Partner_Primary__c = acc1.Id;
        newAnewC.Partner_Secondary__c = acc2.Id;
        newAnewC.Partner_Tertiary__c = acc3.Id;
        newAnewC.PrimarySource__c = 'Consultant Partner	';
        newAnewC.SecondarySource__c = 'Consultant Partner	';
        newAnewC.TertiarySource__c = 'Consultant Partner	';
        
        Lead oldAnewC = TestDataFactory.createLead();
        oldAnewC.RecordTypeId = recordTypeId;
        oldAnewC.Email += 'newC';
        oldAnewC.Auto_Convert__c = 'Yes';
        oldAnewC.Partner_Primary__c = acc1.Id;
        oldAnewC.Partner_Secondary__c = acc2.Id;
        oldAnewC.Partner_Tertiary__c = acc3.Id;
        oldAnewC.PrimarySource__c = 'Consultant Partner	';
        oldAnewC.SecondarySource__c = 'Consultant Partner	';
        oldAnewC.TertiarySource__c = 'Consultant Partner	';
        
        Lead oldAOldC = TestDataFactory.createLead();
        oldAOldC.RecordTypeId = recordTypeId;
        oldAOldC.Auto_Convert__c = 'Yes';
        oldAOldC.Partner_Primary__c = acc1.Id;
        oldAOldC.Partner_Secondary__c = acc2.Id;
        oldAOldC.Partner_Tertiary__c = acc3.Id;
        oldAOldC.PrimarySource__c = 'Consultant Partner	';
		oldAOldC.SecondarySource__c = 'Consultant Partner	';
        oldAOldC.TertiarySource__c = 'Consultant Partner	';
        
        Lead newAOldC = TestDataFactory.createLead();
        newAOldC.RecordTypeId = recordTypeId;
        //newAOldC.Company += 'newA';
        newAOldC.Auto_Convert__c = 'Yes';
        newAOldC.Partner_Primary__c = acc1.Id;
        newAOldC.Partner_Secondary__c = acc2.Id;
        newAOldC.Partner_Tertiary__c = acc3.Id;
		newAOldC.PrimarySource__c = 'Consultant Partner';
        newAOldC.SecondarySource__c = 'Consultant Partner';
        newAOldC.TertiarySource__c = 'Consultant Partner';
        
        Test.startTest();
       // insert new List<Lead>{newAnewC, oldAnewC, oldAOldC, newAOldC};
        /*insert newAnewC;
        insert oldAnewC;
        insert oldAOldC;
        insert newAOldC;*/
        Test.stopTest();
    }
}