force-app/main/default/objects/Account/fields/Postal_code__c.field-meta.xml
<CustomField>
    <fullName>Postal_code__c</fullName>
    <label>Postal code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>South1</fullName>
                <isActive>false</isActive>
                <label>South1</label>
            </value>
            <value>
                <fullName>South2</fullName>
                <isActive>false</isActive>
                <label>South2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>State does not exist with specified Country.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>State__c.Country__c</valueField>
        </filterItems>
        <infoMessage>Select Country to drill down related states</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Lead_Remarks__c</fullName>
    <label>Lead Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadContactsAuthorityLevel__c.field-meta.xml
<CustomField>
    <fullName>LeadContactsAuthorityLevel__c</fullName>
    <label>Lead Contacts Authority Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1: C Level / VP IT / Director Level / Key Decision Makers</fullName>
            </value>
            <value>
                <fullName>Tier 2: GM / AGM / Manager IT / Sr Manager IT. Mid Level managers handling Teams</fullName>
            </value>
            <value>
                <fullName>Tier 3: System Admin / Executives / Asst Managers : Influencers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/OnlineRegistered__c.field-meta.xml
<CustomField>
    <fullName>OnlineRegistered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Online Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>South1</fullName>
                <isActive>false</isActive>
                <label>South1</label>
            </value>
            <value>
                <fullName>South2</fullName>
                <isActive>false</isActive>
                <label>South2</label>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>State does not exist with specified Country.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>State__c.Country__c</valueField>
        </filterItems>
        <infoMessage>Select Country to drill down related states</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Vertical_Temp__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Temp__c</fullName>
    <description>Backend Field used for mapping with Opty&apos;s Vertical, gets updated from process builder</description>
    <label>Vertical Temp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Verticals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/State__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apparel &amp; Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Broadcast (TV, Radio, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Cargo &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Central Government</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Products</fullName>
    </customValue>
    <customValue>
        <fullName>Content Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Content Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Content Processing</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Global BFSI centers</fullName>
    </customValue>
    <customValue>
        <fullName>Global CDN Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global Internet Exchanges</fullName>
    </customValue>
    <customValue>
        <fullName>Global ISP</fullName>
    </customValue>
    <customValue>
        <fullName>Global TSP</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hi-tech and electronic</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Hoster &amp; Local DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Software Vendor (ISV)</fullName>
    </customValue>
    <customValue>
        <fullName>Info Tech Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>ITES/BPO/KPO</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Verticals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>BFSI</fullName>
    </customValue>
    <customValue>
        <fullName>IT&amp;ITES</fullName>
    </customValue>
    <customValue>
        <fullName>Media and entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Govt &amp; PSU</fullName>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Conglomerate</fullName>
    </customValue>
    <masterLabel>Verticals</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerPortalLeadTest.cls
/*
 * Created by Swati Kannaujiya on 24-05-2022.
 */
@isTest
public class CustomerPortalLeadTest 
{
    @TestSetup
    static void makeData()
    {
        State__c state = new State__c();
        state.Name='Up';
        state.Country__c = 'IN';
        state.State_Code__c = '08';
        state.External_Key__c = 'IN-08';
        insert state;
        
        Lead objLead = new Lead(
        FirstName = 'Test',
        LastName = 'Test',
        Email = 'sandeep.CP@gmail.com',
        mobilephone = '9867050284',
        Country_Code__c = '91',
        Company = 'Cloudroute',
        Status = 'Open',
        Industry = 'IT&ITES',
        OnlineRegistered__c = true,
        LeadContactsAuthorityLevel__c = 'Tier 1: C Level / VP IT / Director Level / Key Decision Makers',
        YottaIndustry__c = 'Info Tech Services',
        Region__c = 'West',
        Lead_Remarks__c = 'Lead automatically created By Yotta MyAccount Portal',
        BillToSameasSupportTo__c = true,
        City__c = 'Mumbai',
        Country__c = 'IN',
        Vertical_Temp__c = 'BFSI',
        Postal_code__c = '400600',
        State__c = state.Id);
        insert objLead;
        
        Account acc = new Account();
        acc.Name = objLead.Company;
        insert acc;
        
        Contact con = new Contact();
        con.FirstName='Test1';
        con.LastName='Test2';
        con.Email = objLead.Email;
        con.Country_Code__c = '91';
        con.AccountId = acc.Id;
        insert con;
        
    } 
    @isTest static void positiveTest1()
    {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalLead';  //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueOf('{"Company": "TECP","MobilePhone": "9867050284","Email":"sand.CP@gmail.com","Status": "Open","Industry": "IT&ITES","OnlineRegistered": true,"LeadContactsAuthorityLevel": "Tier 1: C Level / VP IT / Director Level / Key Decision Makers","YottaIndustry": "Info Tech Services","Region": "West","LeadRemarks": "Lead automatically created By Yotta MyAccount Portal","CountryCode": "91","BillToSameasSupportTo": true,"City": "mumbai","Country": "IN","FirstName": "sandeep","LastName": "mhatre","Vertical_Temp": "IT&ITES","Postalcode": "400600","State": "IN-08","ExternalId": "YMA-Vziw0FGFCZ0pbLEt"}');
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalLead.CreateLeadRecord();
        Test.stopTest();
        
        
    }
    
    @isTest static void positiveTest2()
    {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalLead';  //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueOf('{"Company": "Cloudroute","MobilePhone": "9867050284","Email":"sandeep.CP@gmail.com","Status": "Open","Industry": "IT&ITES","OnlineRegistered": true,"LeadContactsAuthorityLevel": "Tier 1: C Level / VP IT / Director Level / Key Decision Makers","YottaIndustry": "Info Tech Services","Region": "West","LeadRemarks": "Lead automatically created By Yotta MyAccount Portal","CountryCode": "91","BillToSameasSupportTo": true,"City": "mumbai","Country": "IN","FirstName": "sandeep","LastName": "mhatre","Vertical_Temp": "IT&ITES","Postalcode": "400600","State": "IN-08","ExternalId": "YMA-Vziw0FGFCZ0pbLEt"}');
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalLead.CreateLeadRecord();
        Test.stopTest();
        
        
    }
    
    @isTest static void NegativeTest1()
    {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        //Test POST API
        req.requestURI = '/services/apexrest/CustomerPortalLead';  //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueOf('{"Company": "TECP","MobilePhone": "9867050284","Email":"sandeep.CP@gmail.com","Status": "Open","Industry": "IT&ITES","OnlineRegistered": true,"LeadContactsAuthorityLevel": "Tier 1: C Level / VP IT / Director Level / Key Decision Makers","YottaIndustry": "Info Tech Services","Region": "West","LeadRemarks": "Lead automatically created By Yotta MyAccount Portal","CountryCode": "91","BillToSameasSupportTo": true,"City": "mumbai","Country": "IN","FirstName": "sandeep","LastName": "mhatre","Vertical_Temp": "IT&ITES","Postalcode": "400600","State": "IN-13","ExternalId": "YMA-Vziw0FGFCZ0pbLEt"}');
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerPortalLead.CreateLeadRecord();
        Test.stopTest();
        
        
    }

}