force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>South1</fullName>
                <isActive>false</isActive>
                <label>South1</label>
            </value>
            <value>
                <fullName>South2</fullName>
                <isActive>false</isActive>
                <label>South2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Infrastructure_Details__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Details__c</fullName>
    <label>Infrastructure Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <externalId>true</externalId>
    <label>Opportunity Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TertiarySource__c.field-meta.xml
<CustomField>
    <fullName>TertiarySource__c</fullName>
    <label>Tertiary Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alliance Partner</fullName>
            </value>
            <value>
                <fullName>Reseller Partner</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>Consultant Partner</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-Commission</fullName>
            </value>
            <value>
                <fullName>Distributor Partner-TP</fullName>
            </value>
            <value>
                <fullName>Business Partner</fullName>
            </value>
            <value>
                <fullName>ERP Partner-Commission</fullName>
            </value>
            <value>
                <fullName>ERP Partner-TP</fullName>
            </value>
            <value>
                <fullName>ERP Technology Partner B2B</fullName>
            </value>
            <value>
                <fullName>YIC Partner</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Business Development - Digital</fullName>
            </value>
            <value>
                <fullName>Leadership Leads</fullName>
            </value>
            <value>
                <fullName>Government Partner - TP</fullName>
            </value>
            <value>
                <fullName>Government Partner - Commission</fullName>
            </value>
            <value>
                <fullName>Government Partner - Technology B2B</fullName>
            </value>
            <value>
                <fullName>YCIC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Verticals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Verticals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>BFSI</fullName>
    </customValue>
    <customValue>
        <fullName>IT&amp;ITES</fullName>
    </customValue>
    <customValue>
        <fullName>Media and entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Govt &amp; PSU</fullName>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Conglomerate</fullName>
    </customValue>
    <masterLabel>Verticals</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RedAlertNotification.cls
/**
 * Created by CloudRoute on 22-03-2022.
 */

public with sharing class RedAlertNotification {

    @InvocableMethod(label = 'Send Red Alert' description = 'Send Red Alert')
    public static void sendNotificationEmail(List<String> params) {

        Map<String, String> inputString = (Map<String, String>)JSON.deserialize(params[0], Map<String, String>.class);
        Id recordId=(Id)inputString.get('recordId');
        String emailBody=(String)inputString.get('emailBody');

        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        Set<String> SenderAddress = new Set<String>();
        Organization org = [SELECT IsSandbox FROM Organization LIMIT 1];
        Opportunity objMsg = [SELECT Id,Name,Account.Name,Owner.Name,StageName,CloseDate,Infrastructure_Details__c,OpportunityId__c,Region__c,Vertical__c,PrimarySource__c,SecondarySource__c,TertiarySource__c,Account.Owner.Email FROM Opportunity Where Id = :recordId];
        System.debug('Opportunity Record '+objMsg);
        List<User> UserDetail = [SELECT Id,Name,Email,UserRole.Name FROM User WHERE UserRole.Name <> null];
        for (User Us: UserDetail){
            if(Us.UserRole.Name.contains('Sales Head')){
                SenderAddress.add(Us.Email);
            }
            if(objMsg.Region__c != null && Us.UserRole.Name.Contains('Regional Head - '+objMsg.Region__c)){
                SenderAddress.add(Us.Email);
            }
            if (objMsg.Vertical__c != null && Us.UserRole.Name.contains('Vertical Head - '+objMsg.Vertical__c)) {
                SenderAddress.add(Us.Email);
            }
            if(((objMsg.SecondarySource__c != null && objMsg.PrimarySource__c.contains('Marketing')) || (objMsg.SecondarySource__c != null && objMsg.SecondarySource__c.contains('Marketing')) || (objMsg.SecondarySource__c != null && objMsg.TertiarySource__c.contains('Marketing'))) && Us.UserRole.Name.contains('IS Head')){
                SenderAddress.add(Us.Email);
            }
            if((objMsg.SecondarySource__c != null && objMsg.PrimarySource__c.contains('Partner')) || (objMsg.SecondarySource__c != null && objMsg.SecondarySource__c.contains('Partner')) || (objMsg.SecondarySource__c != null && objMsg.TertiarySource__c.contains('Partner'))){
                SenderAddress.add(Us.Email);
                if((objMsg.SecondarySource__c != null && objMsg.PrimarySource__c.contains('Distributor')) || (objMsg.SecondarySource__c != null && objMsg.SecondarySource__c.contains('Distributor')) || (objMsg.SecondarySource__c != null && objMsg.TertiarySource__c.contains('Distributor'))){
                    SenderAddress.add('nmasand@yotta.com');
                    SenderAddress.add(objMsg.Account.Owner.Email);
                }
            }
        }
        Set<String> BUHead = new Set<String>{'njadhav@yotta.com','rsheth@yotta.com','speerzade@yotta.com','rgarg@yotta.com','spanda@yotta.com'};
        SenderAddress.addAll(BUHead);
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        if( org.IsSandbox ) {
            message.setToAddresses( new List<String>{'yash.p@cloudroute.in','yashparsiya098@gmail.com','jahuja@yotta.com','smadav@yotta.com','samhatre@yotta.com'});
        } else {
            message.setToAddresses(new List<String>(SenderAddress));
            //message.setCcAddresses( new List<String>{'automation@yotta.com'});// CC Email Address
        }
        String finalBody = 'Opportunity Id: '+objMsg.OpportunityId__c+',<br/> ' +
                ' Account Name : '+objMsg.Account.Name+
                '<br/> Opportunity Name :'+ objMsg.Name+
                '<br/> Opportunity Owner : '+objMsg.Owner.Name+
                '<br/> Stage : '+objMsg.StageName+
                '<br/> Expected Closure Date : '+objMsg.CloseDate.format()+
                '<br/> Infrastructure Details :  '+objMsg.Infrastructure_Details__c+
                '<br/><br/>     Required Following help : <br/><br>'+emailBody;
        message.setHtmlBody( finalBody );
        message.setSenderDisplayName(objMsg.Owner.Name);
        message.setSubject( 'Red Alert For ' + objMsg.OpportunityId__c );
        messages.add(message);
        System.debug('List SenderEmailAddress:  '+SenderAddress);
        System.debug('Email Body :  '+finalBody);
        if( !messages.isEmpty() ){
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            System.debug('Results: '+results);
        }

    }

}