force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>South1</fullName>
                <isActive>false</isActive>
                <label>South1</label>
            </value>
            <value>
                <fullName>South2</fullName>
                <isActive>false</isActive>
                <label>South2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Formula to pull Vertical of the Bill To Account. This will be used for reports.</description>
    <formula>TEXT( Account.Industry )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vertical</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Infrastructure_Details__c.field-meta.xml
<CustomField>
    <fullName>Infrastructure_Details__c</fullName>
    <label>Infrastructure Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PoliticalAlignment__c.field-meta.xml
<CustomField>
    <fullName>PoliticalAlignment__c</fullName>
    <label>Political Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promoter_s_Support_Required__c.field-meta.xml
<CustomField>
    <fullName>Promoter_s_Support_Required__c</fullName>
    <label>Support Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesConfidence__c.field-meta.xml
<CustomField>
    <fullName>SalesConfidence__c</fullName>
    <label>Sales Confidence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reasonably Confident</fullName>
            </value>
            <value>
                <fullName>100% Confident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SupportTo__c.field-meta.xml
<CustomField>
    <fullName>SupportTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TenderRFP__c.field-meta.xml
<CustomField>
    <fullName>TenderRFP__c</fullName>
    <label>Tender/RFP?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Pre-Tender/RFP Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Verticals</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apparel &amp; Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Broadcast (TV, Radio, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Cargo &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Central Government</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Products</fullName>
    </customValue>
    <customValue>
        <fullName>Content Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Content Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Content Processing</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Global BFSI centers</fullName>
    </customValue>
    <customValue>
        <fullName>Global CDN Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global Internet Exchanges</fullName>
    </customValue>
    <customValue>
        <fullName>Global ISP</fullName>
    </customValue>
    <customValue>
        <fullName>Global TSP</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hi-tech and electronic</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Hoster &amp; Local DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Software Vendor (ISV)</fullName>
    </customValue>
    <customValue>
        <fullName>Info Tech Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>ITES/BPO/KPO</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
        <isActive>false</isActive>
        <label>Manufacturing</label>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Verticals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>BFSI</fullName>
    </customValue>
    <customValue>
        <fullName>IT&amp;ITES</fullName>
    </customValue>
    <customValue>
        <fullName>Media and entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Govt &amp; PSU</fullName>
        <label>Government</label>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Conglomerate</fullName>
    </customValue>
    <masterLabel>Verticals</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RedAlertNotification_Test.cls
@isTest
public class RedAlertNotification_Test {
@isTest
    Public static  void redAlertNotificationTest() {
      Test.startTest();
        Account acc = new Account(Name = 'cloudroute solution',Type = 'Private Limited',Industry= 'Education');
        insert acc;
        Opportunity opp = new Opportunity(  StageName = 'Qualification',       
                                                Name = 'Amendment for contract #00007239',                     
                                                Probability = 10,                           
                                                Infrastructure_Details__c = 'Test classes',
                                                CurrencyIsoCode = 'INR',
                                                TenderRFP__c = 'Yes',
                                                Promoter_s_Support_Required__c = 'No',
                                                 SupportTo__c = acc.ID,
                                                CloseDate = Date.parse('06/07/2022'),
                                                Amount = 45678,
                                                PoliticalAlignment__c = 'Positive', 
                                                SalesConfidence__c= 'Reasonably Confident',
                                                 Type = 'Existing Business', 
                                                Region__c = 'west',
                                                Vertical__c = 'Manufacturing',
                                                YottaIndustry__c = 'Apparel & Fashion',
                                                Location__c = 'IN11',
                                                PrimarySource__c='Sales',
                                                 AccountId = acc.ID);
                                               
                                                         
                 insert opp;
        RedAlertNotification.sendNotificationEmail(new List<String>{'{\"recordId\" : \"'+opp.Id+'\", \"emailBody\" : \"' + 'test' + '\"}'});
             test.stopTest();
        
          }
    
}