force-app/main/default/objects/Account/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Send Record To Kafka</inlineHelpText>
    <label>Send To Kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerController__c/TriggerController__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerController</label>
</CustomObject>

force-app/main/default/objects/TriggerController__c/fields/DeactivateObjectTrigger__c.field-meta.xml
<CustomField>
    <fullName>DeactivateObjectTrigger__c</fullName>
    <label>DeactivateObjectTrigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apparel &amp; Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Broadcast (TV, Radio, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Cargo &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Central Government</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Products</fullName>
    </customValue>
    <customValue>
        <fullName>Content Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Content Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Content Processing</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Global BFSI centers</fullName>
    </customValue>
    <customValue>
        <fullName>Global CDN Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global Internet Exchanges</fullName>
    </customValue>
    <customValue>
        <fullName>Global ISP</fullName>
    </customValue>
    <customValue>
        <fullName>Global TSP</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hi-tech and electronic</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Hoster &amp; Local DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Software Vendor (ISV)</fullName>
    </customValue>
    <customValue>
        <fullName>Info Tech Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>ITES/BPO/KPO</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
        <isActive>false</isActive>
        <label>Manufacturing</label>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/IntegrationBaseTest.cls
@isTest
public class IntegrationBaseTest extends TriggerHandler {
    
    @testSetup
    static void setup() {
        //create trigger controller
        TriggerController__c tc = new TriggerController__c(DeactivateObjectTrigger__c = '', isActive__c = TRUE);
        insert tc;
        
        //insert account
        Account acc = new Account(Name = 'Acc Name', Industry = 'Manufacturing', YottaIndustry__c = 'Automotive', Send_to_API_Layer__c = TRUE);
        insert acc;
    }
    
    @isTest
    public static void generateRequestTemplate(){
       
        List<Account> accList = [Select Id from Account Limit 1];
        IntegrationBase baseFramework = new IntegrationBase();
        baseFramework.CreateIntegrationRequestEnvelope('Account_Topic', accList[0].Id);
    }
    
    @isTest
    public static void testCallout(){
        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        IntegrationBase baseFramework = new IntegrationBase();
        HttpResponse res = baseFramework.makeCallout('{caseId : 1, nbsRefId : 2, purchaseOrder : {externalId : 1}}', 'GET', 'http://example.com/example/test');
        Test.stopTest();
    }
    
    @isTest
    public static void testCalloutWithHeader(){
        Test.startTest();
        Map<string, object> header = new Map<string, object>();
        header.put('authorization','testkey');
        //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        IntegrationBase baseFramework = new IntegrationBase();
        HttpResponse res = baseFramework.makeCalloutWithHeader('{caseId : 1, nbsRefId : 2, purchaseOrder : {externalId : 1}}', 'GET', 'http://example.com/example/test', header);
        Test.stopTest();
    }
    
    @isTest
    public static void testCreateIM(){
        IntegrationBase baseFramework = new IntegrationBase();
        List<Account> accountList = [Select Id from Account Limit 1];
        baseFramework.createIMRecord(null, accountList[0].Id, 'Create', 'Real Time', '','','{caseId : 1, nbsRefId : 2, purchaseOrder : {externalId : 1}}', '{caseId : 1, nbsRefId : 2, purchaseOrder : {externalId : 1}}',
                             false, 'Account_Topic');
    }
    
    @isTest
    public static void testCreateMinimalistIM(){
        IntegrationBase baseFramework = new IntegrationBase();
        List<Account> accList = [Select Id from Account Limit 1];
        baseFramework.createMinimalisticIMRecord(null, accList[0].Id, 'Create', 'Real Time', '{caseId : 1, nbsRefId : 2, purchaseOrder : {externalId : 1}}', false,'Integration', '', 'Success');
    }

    @isTest
    public static void testRetrial(){
        IntegrationBase baseFramework = new IntegrationBase();
        baseFramework.validForRetrial(400,1);
    }
    
}