force-app/main/default/objects/Account/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Send Record To Kafka</inlineHelpText>
    <label>Send To Kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>State does not exist with specified Country.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>State__c.Country__c</valueField>
        </filterItems>
        <infoMessage>Select Country to drill down related states</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/YottaIndustry__c.field-meta.xml
<CustomField>
    <fullName>YottaIndustry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Adr-{00000}</displayFormat>
        <label>Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/AddressType__c.field-meta.xml
<CustomField>
    <fullName>AddressType__c</fullName>
    <label>Address Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/GSTApplicable__c.field-meta.xml
<CustomField>
    <fullName>GSTApplicable__c</fullName>
    <label>GST Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State2__c.field-meta.xml
<CustomField>
    <fullName>State2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>State does not exist with specified Country.</errorMessage>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>State__c.Country__c</valueField>
        </filterItems>
        <infoMessage>Select Country to drill down related states</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>2bdel_State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/fields/State_Code__c.field-meta.xml
<CustomField>
    <fullName>State_Code__c</fullName>
    <label>State Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerController__c/TriggerController__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerController</label>
</CustomObject>

force-app/main/default/objects/TriggerController__c/fields/DeactivateObjectTrigger__c.field-meta.xml
<CustomField>
    <fullName>DeactivateObjectTrigger__c</fullName>
    <label>DeactivateObjectTrigger</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apparel &amp; Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Broadcast (TV, Radio, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Cargo &amp; Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Central Government</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Products</fullName>
    </customValue>
    <customValue>
        <fullName>Content Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Content Distribution</fullName>
    </customValue>
    <customValue>
        <fullName>Content Processing</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electricity</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Fintech</fullName>
    </customValue>
    <customValue>
        <fullName>Global BFSI centers</fullName>
    </customValue>
    <customValue>
        <fullName>Global CDN Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Global Internet Exchanges</fullName>
    </customValue>
    <customValue>
        <fullName>Global ISP</fullName>
    </customValue>
    <customValue>
        <fullName>Global TSP</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hi-tech and electronic</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Hoster &amp; Local DC Players</fullName>
    </customValue>
    <customValue>
        <fullName>Hyperscalers</fullName>
    </customValue>
    <customValue>
        <fullName>Independent Software Vendor (ISV)</fullName>
    </customValue>
    <customValue>
        <fullName>Info Tech Services</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>ITES/BPO/KPO</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
        <isActive>false</isActive>
        <label>Manufacturing</label>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AddressTriggerHandlerTest.cls
@isTest
public class AddressTriggerHandlerTest {
    
    @testSetup
    public static void createData(){
        //create trigger controller
        TriggerController__c tc = new TriggerController__c(DeactivateObjectTrigger__c = '', isActive__c = TRUE);
        insert tc;
    }
    
    @isTest
    public static void createAddressAndSendToKafka(){
        
        //insert account
        Account acc = new Account(Name = 'Acc Name', Industry = 'Manufacturing', YottaIndustry__c= 'Automotive');
        insert acc;
        
        State__c objState = new State__c();
        objState.Active__c = true;
        objState.Country__c = 'IN';
        objState.State_Code__c = 'MH';
        insert objState;
        
        //insert Address
        Address__c add = new Address__c(AddressLine1__c = 'Sample Add', 
                                                City__c = 'city',
                                        	 Country__c = 'IN',
                                          PostalCode__c = '101010',
                                       GSTApplicable__c = 'No',
                                              State2__c = objState.Id,
                                         AddressType__c = 'Billing',
                                             Account__c =  acc.Id,
                                   Send_To_Api_layer__c =  TRUE);
        insert add;
        
        //send record to kafka by changing envelope fields
        add.AddressLine1__c = 'Yotta add';
        update add;
    }
}