force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Quote #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/partnerOpptyEmailController.cls
public without sharing class partnerOpptyEmailController {
    public String quoteId{get;set;}
    
    public Sbqq__Quote__c getPartnerEmailInf{
        get{
         getPartnerEmailInf = quoteId != null ? [Select SBQQ__Opportunity2__r.Name,SBQQ__Opportunity2__c,SBQQ__Account__r.Name,Quote__c from SBQQ__Quote__c where
                                            id= : quoteId] : new Sbqq__Quote__c(); 
         return getPartnerEmailInf; 
       //  return quoteId != null ? [Select SBQQ__Opportunity2__r.Name,SBQQ__Opportunity2__c,SBQQ__Account__r.Name,Quote__c from SBQQ__Quote__c where
         //                                   id= : quoteId];
        } set; 
    }
}