force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__TerminatedDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TerminatedDate__c</fullName>
    <description>Date on which this subscription terminated.</description>
    <inlineHelpText>Date the subscription terminated. Automatically populated when covered asset is upgraded.</inlineHelpText>
    <label>Terminated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
                <default>true</default>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Deployment Pending</fullName>
            </value>
            <value>
                <fullName>Under Delivery</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Amendment in progress</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Under Decommission</fullName>
            </value>
            <value>
                <fullName>Under Commissioning</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExpireContractBatch.cls
/* ****************************************************************************************************************
Name          : ExpireContractBatch
Description   : ExpireContractBatch Apex Batch Class function is to expire active Contract
                
Author        : Sumeet Gholap (Compro Technologies)
Creation Date : 13-November-2020
**************************************************************************************************************** */
global class ExpireContractBatch implements Database.Batchable<SObject>, Database.Stateful { 
    global Integer recordsProcessed = 0; 

    global Database.QueryLocator start(Database.BatchableContext bc){ 
        return Database.getQueryLocator('SELECT Id, SBQQ__RenewalQuoted__c, Status, EndDate FROM Contract WHERE EndDate <= TODAY AND Status = \'Activated\' AND SBQQ__RenewalQuoted__c = FALSE'); 
    }

    global void execute(Database.BatchableContext bc, List<Contract> scope){ 
        Map<Id, Contract> contractMap = new Map<Id, Contract>();

        for(Contract contract : scope){
            contract.Status = 'Expired';
            contractMap.put(contract.Id, contract);
        }
            
        List<SBQQ__Subscription__c> subsList = [SELECT Id, SBQQ__Contract__c, Status__c, SBQQ__TerminatedDate__c FROM SBQQ__Subscription__c WHERE SBQQ__Contract__c IN: contractMap.keySet() and Status__c != 'Deactivated' and Status__c != 'Cancelled' and Status__c != 'Amendment in Progress'  and SBQQ__TerminatedDate__c = NULL];
        for(SBQQ__Subscription__c sub : subsList)
            sub.Status__c = 'Expired';
        
        if(scope.size() > 0)
            update scope;
        if(subsList.size() > 0)
            update subsList;
        
    } 

    global void finish(Database.BatchableContext bc){} 
}