force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Adr-{00000}</displayFormat>
        <label>Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN10</fullName>
                <label>Yotta Data Services Private Limited</label>
            </value>
            <value>
                <fullName>IN20</fullName>
                <label>Yotta Network Services Private Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Tenure_Days__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Days__c</fullName>
    <label>Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Tenure_Months__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Months__c</fullName>
    <label>Months</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Tenure_Years__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Years__c</fullName>
    <label>Years</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorised_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Authorised Signatory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Customer Authorised Signatory)</relationshipLabel>
    <relationshipName>Contracts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Contact Billing Contact)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_SPoC__c.field-meta.xml
<CustomField>
    <fullName>Customer_SPoC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer SPoC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Support_To_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Master_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Master_Contract_Id__c</fullName>
    <label>Original Master Contract Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/OTC_Advance_Payment_Term_SOS__c.field-meta.xml
<CustomField>
    <fullName>OTC_Advance_Payment_Term_SOS__c</fullName>
    <inlineHelpText>One Time Charges Advance Payment Term</inlineHelpText>
    <label>OTC Advance Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>25%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/RC_Advance_Payment_Term_SOS__c.field-meta.xml
<CustomField>
    <fullName>RC_Advance_Payment_Term_SOS__c</fullName>
    <inlineHelpText>Recurring Charges Advance Payment Terms</inlineHelpText>
    <label>RC Advance Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly in Advance</fullName>
            </value>
            <value>
                <fullName>Monthly in Arrears</fullName>
            </value>
            <value>
                <fullName>Quarterly in Advance</fullName>
            </value>
            <value>
                <fullName>Quarterly in Arrears</fullName>
            </value>
            <value>
                <fullName>Half yearly in Advance</fullName>
            </value>
            <value>
                <fullName>Half yearly in Arrears</fullName>
            </value>
            <value>
                <fullName>Yearly in Advance</fullName>
            </value>
            <value>
                <fullName>Yearly in Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Quotes (Bill To Address)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contract_Tenure_Days__c.field-meta.xml
<CustomField>
    <fullName>Contract_Tenure_Days__c</fullName>
    <label>Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorised_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GG: 26-Oct Created to get the Contact from Contract then make it available for update on Contract.</description>
    <label>Customer Authorised Signatory</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria- Customer Authorised</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Authorised Signatory)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Billing Contact)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_SPoC__c.field-meta.xml
<CustomField>
    <fullName>Customer_SPoC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GG: 26-Oct Created to get the Contact from Contract then make it available for update on Contract.</description>
    <label>Customer SPoC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria-Customer SPOC.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Support_To_Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer SPoC)</relationshipLabel>
    <relationshipName>Quotes4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Original_Master_Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Master_Contract_Id__c</fullName>
    <label>Original Master Contract Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCFBillCycleChangeController.cls
/* ****************************************************************************************************************
Name          : SCFBillCycleChangeController
Description   : It is used for bill cycle change pdf to fetch required data from quote 
on Quote
Author        : Riya Sharma(Compro Technologies)

**************************************************************************************************************** */
public without sharing class SCFBillCycleChangeController {
    
    
    public static string errorMessage {get;set;}
    public static Id FileId;
    public String quoteId{get;set;}
    public SBQQ__Quote__c quote{get;set;}
    public Integer remainingYears {get;set;}
    public Integer remainingMonths {get;set;}
    public Integer remainingDays {get;set;}
    public Contract originalContract {get; set;}    
    
    public SCFBillCycleChangeController(ApexPages.StandardController stdController) {
        //gets the current id of the quote page
        quoteId = ApexPages.currentPage().getParameters().get('id');
        
        quote = [Select SBQQ__MasterContract__c, Original_Master_Contract_Id__c, toLabel(SBQQ__MasterContract__r.Business_Unit__c), SBQQ__MasterContract__r.SBQQ__AmendmentStartDate__c,SBQQ__MasterContract__r.StartDate from SBQQ__Quote__c where id =: quoteId ];
         Id contractId = quote.SBQQ__MasterContract__c;
        if(contractId == NULL){
            contractId = quote.Original_Master_Contract_Id__c;
        }
        if(contractId != NULL){
            System.debug('quote.Original_Master_Contract_Id__c'+quote.Original_Master_Contract_Id__c);
            originalContract = [SELECT Id, Contract_Tenure_Years__c, Contract_Tenure_Months__c,EndDate, OTC_Advance_Payment_Term_SOS__c, RC_Advance_Payment_Term_SOS__c, Contract_Number__c, 
                                Customer_Authorised_Signatory__r.Name, Customer_Authorised_Signatory__r.Title, Customer_Authorised_Signatory__r.Email, Customer_Authorised_Signatory__r.MobilePhone, 
                                Contract_Tenure_Days__c, Customer_SPoC__r.Name, Customer_SPoC__r.Email,
                                Customer_SPoC__r.Phone, Customer_Billing_Contact__r.Name, Customer_Billing_Contact__r.Email,
                                Customer_Billing_Contact__r.Phone, Owner.Name, Owner.Email, Owner.Phone, ContractNumber, 
                                Bill_To_Address__r.AddressLine1__c, Bill_To_Address__r.AddressLine2__c,
                                Bill_To_Address__r.City__c, Business_Unit__c, SBQQ__AmendmentStartDate__c, 
                                StartDate FROM Contract WHERE Id =: contractId];
        }        
        
        remainingContract();
    }
    
    public void remainingContract(){
        
        //gets remaining days from contract to be used in pdf
        //System.debug('originalContract.SBQQ__AmendmentStartDate__c' + originalContract.SBQQ__AmendmentStartDate__c);
        
        
        Date StartDate = originalContract.SBQQ__AmendmentStartDate__c - 1;
        Date EndDate = originalContract.EndDate  ;
        System.debug('originalContract.SBQQ__AmendmentStartDate__c' + originalContract.SBQQ__AmendmentStartDate__c);
          Integer months = originalContract.SBQQ__AmendmentStartDate__c.monthsBetween(EndDate);
         if (StartDate.day() > EndDate.day()) {          
            months--;
        }
        Date rolledBackEndDate = EndDate.addMonths(0 - months);
        Integer years =(Integer) Math.floor(months / 12.0);
        months = months - (years * 12);
        Integer days =  StartDate.daysBetween(rolledBackEndDate);
        remainingYears = years;
        remainingMonths = months;
        remainingDays = days;
        //remainingDays = originalContract.SBQQ__AmendmentStartDate__c.daysBetween(originalContract.EndDate);
        //remainingYears = originalContract.EndDate.year() - originalContract.SBQQ__AmendmentStartDate__c.year();
    }
}