force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Adr-{00000}</displayFormat>
        <label>Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <label>Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <label>Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Quotes (Bill To Address)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Support_To_Customer__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Support To Customer)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteProposalEmailComponentController.cls
public class QuoteProposalEmailComponentController {
	public QuoteProposalEmailComponentController() {
		System.debug(recId);
	}

	public Id recId {get; set;}
	public SBQQ__Quote__c quote {get{
			SBQQ__Quote__c quote = recId != null ? [SELECT Id, Owner.Name, Owner.Phone , Bill_To_Address__r.AddressLine1__c, Bill_To_Address__r.AddressLine2__c, Bill_To_Address__r.City__c, toLabel(Bill_To_Address__r.Country__c), SBQQ__Account__r.Name, Customer_Contact__r.Name, SBQQ__Account__c, SBQQ__Opportunity2__r.Name, Support_To_Customer__r.Name, Support_To_Customer__r.Phone FROM SBQQ__Quote__c WHERE Id = : recId]: new Sbqq__Quote__c();
			return quote;
		}
		set;
	}
}