force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Adr-{00000}</displayFormat>
        <label>Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Last_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Sync_Date__c</fullName>
    <label>Last Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Sync_Date__c</fullName>
    <label>Last Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Last_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Sync_Date__c</fullName>
    <label>Last Sync Date / Last SCF Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/Add_Payload_as_URL_Param__c.field-meta.xml
<CustomField>
    <fullName>Add_Payload_as_URL_Param__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Payload as URL Param</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/HeaderMap__c.field-meta.xml
<CustomField>
    <fullName>HeaderMap__c</fullName>
    <description>header key value compbinaitons for integration request
example= key:value</description>
    <inlineHelpText>header key value compbinaitons for integration request
example= key:value</inlineHelpText>
    <label>HeaderMap</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <label>Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/Integration_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Integration_Authorization__c</fullName>
    <label>Integration Authorization</label>
    <referenceTo>Integration_Authorization__mdt</referenceTo>
    <relationshipLabel>Integration Credentials</relationshipLabel>
    <relationshipName>Integration_Credentials</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Integration_Credential__mdt/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kafka</fullName>
            </value>
            <value>
                <fullName>NBS</fullName>
                <isActive>false</isActive>
                <label>NBS</label>
            </value>
            <value>
                <fullName>Netcore</fullName>
                <isActive>false</isActive>
                <label>Netcore</label>
            </value>
            <value>
                <fullName>Signzy</fullName>
                <isActive>false</isActive>
                <label>Signzy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Type__c.field-meta.xml
<CustomField>
    <fullName>Integration_Type__c</fullName>
    <label>Integration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Real Time</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Number_of_Retrials__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Retrials__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Retrials</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Parent_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Name__c</fullName>
    <label>Parent Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Response_Envelope__c.field-meta.xml
<CustomField>
    <fullName>Response_Envelope__c</fullName>
    <label>Response Envelope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Valid_for_Retrial__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Retrial__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Valid for Retrial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Last_Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Sync_Date__c</fullName>
    <label>Last Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/OutboundIntegrationBatch.cls
/*
*   Name        : OutboundIntegrationBatch
*   Description : Handles All Integration Logic 
*   Author      : Nandish Shenoy
*   Create On   : 01 May 2020
*   |-------------------------------------------------------------------------|
*   | Version | Modified By      | Date       | Comment                       |
*   |-------------------------------------------------------------------------|
*   | 0.1     | Nandish          | 01/05/2020 | Initial Version of Class      |
*   |-------------------------------------------------------------------------|
*/
global class OutboundIntegrationBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    
    global String query;
    global List<Integration_Message__c> imList;
    global List<Integration_Message__c> updatedIMList;
    global Map<String, Integration_Credential__mdt> credsMap; //added for use in finish method
    global String jobId ;
    global Boolean isRetrialBatch = false;
    /*Map<Id, String> mapMsgIdToRequestEnvelope = new Map<Id, String>();*/

    global OutboundIntegrationBatch() {
        //providing memory to global vars
        updatedIMList = new List<Integration_Message__c>();
        credsMap = new Map<String, Integration_Credential__mdt>();
        for(Integration_Credential__mdt creds:[SELECT ID, Add_Payload_as_URL_Param__c, Http_Method__c, DeveloperName, Endpoint__c, HeaderMap__c, Password__c, Integration_Type__c, Username__c FROM Integration_Credential__mdt WHERE isActive__c = true]){
            credsMap.put(creds.DeveloperName, creds);
        }
    }

    global OutboundIntegrationBatch(List<Integration_Message__c> tmpIMList){  
        //providing memory to global vars
        updatedIMList = new List<Integration_Message__c>();
        imList = new List<Integration_Message__c>();
        imList = tmpIMList;
        credsMap = new Map<String, Integration_Credential__mdt>();
        for(Integration_Credential__mdt creds:[SELECT ID, Add_Payload_as_URL_Param__c, Http_Method__c, DeveloperName, Endpoint__c, HeaderMap__c, Password__c, Integration_Type__c, Username__c, Integration_Authorization__c FROM Integration_Credential__mdt WHERE isActive__c = true]){
            credsMap.put(creds.DeveloperName, creds);
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        if(imList != null){       
            query = IntegrationConstants.STR_OUTBOUNDBATCH_BASEQUERY + ' WHERE ID IN:imList';
        }else{
            query = IntegrationConstants.STR_OUTBOUNDBATCH_BASEQUERY + ' WHERE (Integration_Status__c=\'In Progress\' OR Integration_Status__c=\'Failed\') AND Valid_for_Retrial__c = true'; 
        }
        return Database.getQueryLocator(query);
    }    

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        TriggerHandler.bypassAllTriggers();
        IntegrationBase iBase = new IntegrationBase();
        List<SObject> lstParentRecords = new List<SObject>();
        
        for( Integration_Message__c objMessage : (List<Integration_Message__c>)scope ) {
            Map<String,Object> header = new Map<String, Object>();
            String idRecordId = '';
            if( objMessage.Address__c <> null ) {
                idRecordId = objMessage.Address__c;
            } else if( objMessage.Account__c <> null ) {
                idRecordId = objMessage.Account__c;
            } else if( objMessage.Contact__c <> null ) {
                idRecordId = objMessage.Contact__c;
            } else if( objMessage.Contract__c <> null) {
                idRecordId = objMessage.Contract__c;
            } else if(objMessage.Product2__c <> null){
                idRecordId = objMessage.Product2__c;
            }
            if( String.isNotBlank(idRecordId) ) {
                try {
                    String requestEnv = iBase.CreateIntegrationRequestEnvelope(objMessage.Parent_Template_Name__c, idRecordId);
                    if( credsMap.containsKey( objMessage.Parent_Template_Name__c ) ) {
                        Integration_Credential__mdt creds = credsMap.get(objMessage.Parent_Template_Name__c);
                        if( creds.HeaderMap__c <>  null ) {
                            header = (Map<String, Object>)JSON.deserializeUntyped(creds.HeaderMap__c);
                        }
                        String strMessage = '';
                        String endPoint = creds.Endpoint__c;
                        system.debug('Payload ' + requestEnv);
                        //mapMsgIdToRequestEnvelope.put(objMessage.Id , requestEnv);
                        HttpResponse res = iBase.getAuthorizationToken( creds.Integration_Authorization__c );
                        if( res.getStatusCode() == 200 || res.getStatusCode() == 201 ) {
                            IntegrationBase.kafkaAuthToken token = (IntegrationBase.kafkaAuthToken)JSON.deserialize(res.getBody(), IntegrationBase.kafkaAuthToken.class);
                            String accesstoken = token.access_token;
                            system.debug('===>>>' + accesstoken);
                            Map<String, Object> mapkeyToValueHeader = new Map<String, Object>();
                            mapkeyToValueHeader.put( 'Content-Type', 'application/json' );
                            mapkeyToValueHeader.put( 'Authorization', 'Bearer '+ accesstoken );
                            HttpResponse response = iBase.makeCalloutWithHeader(requestEnv, creds.Http_Method__c, endPoint, mapkeyToValueHeader);
                            Integration_Message__c im = iBase.createIMRecord(objMessage.ID, idRecordId,'', '', '','', strMessage, response.getBody(), false, objMessage.Parent_Template_Name__c);
                            if(response.getStatusCode() == 200) {
                                im.Unique_Key__c = idRecordId + '_' + im.Parent_Template_Name__c + '_Success_'+ objMessage.Name; 
                                im.Integration_Status__c = 'Success';
                                im.Valid_for_Retrial__c = false;
                                im.Error_Code__c = null;
                            } else {
                                im.Unique_Key__c = idRecordId + '_' + im.Parent_Template_Name__c + '_Failed_'+ objMessage.Name; im.Integration_Status__c = 'Failed';im.Error_Code__c = String.valueOf(response.getStatusCode());
                                if( objMessage.Number_of_Retrials__c == null ) { objMessage.Number_of_Retrials__c = 0;}
                                im.Number_of_Retrials__c = objMessage.Number_of_Retrials__c + 1;im.Valid_for_Retrial__c = true;
                                if( im.Number_of_Retrials__c >= 3 ) {im.Valid_for_Retrial__c = false; }
                            }
                            updatedIMList.add( im ); 
                        } else {
                            Integration_Message__c im = iBase.createIMRecord(objMessage.ID, idRecordId,'', '', '','', strMessage, res.getBody(), false, objMessage.Parent_Template_Name__c);im.Unique_Key__c = idRecordId + '_' + im.Parent_Template_Name__c + '_Failed_'+ objMessage.Name;im.Integration_Status__c = 'Failed';
                            im.Error_Code__c = String.valueOf(res.getStatusCode());im.Response_Envelope__c = res.getBody();
                            if( objMessage.Number_of_Retrials__c == null ) {objMessage.Number_of_Retrials__c = 0;}
                            im.Number_of_Retrials__c = objMessage.Number_of_Retrials__c + 1;im.Valid_for_Retrial__c = true;
                            if( im.Number_of_Retrials__c >= 3 ) {im.Valid_for_Retrial__c = false; }
                            updatedIMList.add( im );
                        } 
                    }
                    ContentVersion cv = new ContentVersion();
                    cv.VersionData = Blob.valueOf(requestEnv);
                    cv.Title = 'JSON File -' + objMessage.ID + '-' + String.valueOf(Datetime.now().getTime());
                    cv.PathOnClient = 'JSON File -' + objMessage.ID + '-' + String.valueOf(Datetime.now().getTime());
                    cv.FirstPublishLocationId = objMessage.ID;
                    insert cv;
                }catch(Exception e){
                    Integration_Message__c im = iBase.createIMRecord(objMessage.ID, idRecordId,'', '', '','', '', e.getMessage(), false, objMessage.Parent_Template_Name__c);
                    im.Unique_Key__c = idRecordId + '_' + im.Parent_Template_Name__c + '_Failed_'+ objMessage.Name; 
                    im.Integration_Status__c = 'Failed';
                    im.Response_Envelope__c = e.getMessage();
                    if( objMessage.Number_of_Retrials__c == null ) {
                        objMessage.Number_of_Retrials__c = 0;
                    }
                    im.Number_of_Retrials__c = objMessage.Number_of_Retrials__c + 1;
                    im.Valid_for_Retrial__c = true;
                    if( im.Number_of_Retrials__c >= 3 ) {
                        im.Valid_for_Retrial__c = false;
                    }
                    updatedIMList.add( im );
                }
            } 
        }
        
        TriggerHandler.clearAllBypass();
    }
    
    /*private void createContentVersion( Id integrationMessageId, String jsonPayload) {
        ContentVersion cv = new ContentVersion();
        cv.VersionData = Blob.valueOf(jsonPayload);
        cv.Title = 'JSON File -' + integrationMessageId + '-' + String.valueOf(Datetime.now().getTime());
        cv.PathOnClient = 'JSON File -' + integrationMessageId + '-' + String.valueOf(Datetime.now().getTime());
        cv.FirstPublishLocationId = integrationMessageId;
        insert cv;
    }*/

    global void finish(Database.BatchableContext BC){
        if( !updatedIMList.isEmpty()) {
            update updatedIMList;
        }

        /*List<ContentVersion> lstContentVersion = new List<ContentVersion>();
        Map<Id, ContentVersion> mapLinkToContentVersionNew = new Map<Id, ContentVersion>();

        for( Id objMsgId : mapMsgIdToRequestEnvelope.keySet() ) {
            ContentVersion cv = new ContentVersion();
            cv.VersionData = Blob.valueOf(mapMsgIdToRequestEnvelope.get(objMsgId));
            cv.Title = 'JSON File -' + objMsgId + '-' + String.valueOf(Datetime.now().getTime());
            cv.PathOnClient = 'JSON File -' + objMsgId + '-' + String.valueOf(Datetime.now().getTime());
            mapLinkToContentVersionNew.put( objMsgId, cv);
            lstContentVersion.add( cv );
        }  
        upsert lstContentVersion;
        List<ContentDocumentLink> lstCDLinks = new List<ContentDocumentLink>();
        for( Id objMsgId : mapLinkToContentVersionNew.keySet() ) {
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = [ SELECT ContentDocumentId FROM ContentVersion WHERE Id =: mapLinkToContentVersionNew.get(objMsgId).Id ].ContentDocumentId;
            cdl.LinkedEntityId = objMsgId;
            cdl.ShareType = 'V';
            lstCDLinks.add( cdl );
        }    
        insert lstCDLinks;*/

        if( jobId != null ) {
            System.abortJob( jobId );
        }

        List<sObject> lstsObjectsToUpdate = new List<sObject>();
        for( Integration_Message__c objMessage : updatedIMList ) {
            if( objMessage.Integration_Status__c == 'Success' ) {
                String idRecordId = ''; 
                sObject sObj = null;
                if( objMessage.Address__c <> null ) {
                    idRecordId = objMessage.Address__c;
                    sObj = new Address__c();
                } else if( objMessage.Account__c <> null ) {
                    idRecordId = objMessage.Account__c;
                    sObj = new Account();
                } else if( objMessage.Contact__c <> null ) {
                    idRecordId = objMessage.Contact__c;
                    sObj = new Contact();
                } else if( objMessage.Contract__c <> null) {
                    idRecordId = objMessage.Contract__c;
                    sObj = new Contract();
                } else if(objMessage.Product2__c <> null){
                    idRecordId = objMessage.Product2__c;
                    sObj = new Product2();
                }
                sObj.Id = idRecordId;
                sObj.put('last_sync_date__c', Datetime.now());
                lstsObjectsToUpdate.add( sObj );
            }
        }
        update lstsObjectsToUpdate;    
    }         
}