force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Adr-{00000}</displayFormat>
        <label>Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Downstream_Reference_ID__c.field-meta.xml
<CustomField>
    <fullName>Downstream_Reference_ID__c</fullName>
    <label>Downstream Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Number_of_Retrials__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Retrials__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Retrials</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Parent_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template_Name__c</fullName>
    <label>Parent Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Request_Envelope__c.field-meta.xml
<CustomField>
    <fullName>Request_Envelope__c</fullName>
    <label>Request Envelope</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Response_Envelope__c.field-meta.xml
<CustomField>
    <fullName>Response_Envelope__c</fullName>
    <label>Response Envelope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Valid_for_Retrial__c.field-meta.xml
<CustomField>
    <fullName>Valid_for_Retrial__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Valid for Retrial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegrationConstants.cls
/* ****************************************************************************************************************
Name          : IntegrationConstants
Description   : Stores constant keywords used in IntegrationFramework
Author        : Nandish Shenoy  
Creation Date : 20/5/2020
Modified Date : 29/5/2020
**************************************************************************************************************** */
public with sharing class IntegrationConstants {
    
    public static final String STR_ACCOUNT_TEMPLATE_NAME = Label.Integration_Account_Metadata;
    public static final String STR_CONTACT_TEMPLATE_NAME = Label.Integration_Contact_Metadata;
    public static final String STR_ADDRESS_TEMPLATE_NAME = Label.Integration_Address_Metadata;
    public static final String STR_PRODUCT_TEMPLATE_NAME = Label.Integration_Product_Metadata;
    public static final String STR_OUTBOUNDBATCH_BASEQUERY = 'SELECT ID, Name, Parent_Template_Name__c, Valid_for_Retrial__c, Number_of_Retrials__c, Account__c, Contact__c, Address__c, Product2__c, Contract__c, Error_Code__c, Error_Description__c, Integration_Status__c, Downstream_Reference_ID__c, Request_Envelope__c, Response_Envelope__c, Unique_Key__c FROM Integration_Message__c';
    public static final String STR_CONTRACT_TEMPLATE_NAME = Label.Integration_Contract_Metadata;
    public static final String STR_NO_TEMPLATE_NAME = 'NO_TEMPLATE';
	
    public static void dummyMethod() {
        Decimal int1 = 0;
        Decimal int2 = 0;
    }
    
}