force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Integration Messages</relationshipLabel>
    <relationshipName>Integration_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Number_of_Retrials__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Retrials__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Retrials</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Id__c</fullName>
    <formula>IF( !ISBLANK(Account__c), Account__c,
IF( !ISBLANK( Contact__c ), Contact__c,
IF( !ISBLANK(Address__c), Address__c,
IF( !ISBLANK(Product2__c), Product2__c,
IF( !ISBLANK(Contract__c), Contract__c, &apos;&apos;)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Record Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Related_Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Name__c</fullName>
    <formula>IF( !ISBLANK(Account__c), &apos;Account: &apos; + Account__r.Name, 
  IF( !ISBLANK( Contact__c ), &apos;Contact: &apos; + Contact__r.FirstName + &apos; &apos; + Contact__r.LastName, 
     IF( !ISBLANK(Address__c), &apos;Address: &apos; + Address__r.Name, 
        IF( !ISBLANK(Product2__c), &apos;Product: &apos; + Product2__r.Name, 
           IF( !ISBLANK(Contract__c), &apos;Contract: &apos; + Contract__r.Contract_Number__c, &apos;&apos;)
        )
     )
  )
)</formula>
    <label>Related Record Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Webservice_params__c.field-meta.xml
<CustomField>
    <fullName>Webservice_params__c</fullName>
    <label>Webservice params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Webservice_Request__c.field-meta.xml
<CustomField>
    <fullName>Webservice_Request__c</fullName>
    <label>Webservice Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FetchCustomerBillingGroups</fullName>
            </value>
            <value>
                <fullName>FetchBillingSOFs</fullName>
            </value>
            <value>
                <fullName>FetchProductSubscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Quote #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/IntegrationMessageHandler.cls
/*
*   Name        : IntegrationMessageHandler
*   Description : Integration Document and Webservice  
*   Author      : Nandish Shenoy
*   Create On   : 
*   |-------------------------------------------------------------------------|
*   | Version | Modified By      | Date       | Comment                       |
*   |-------------------------------------------------------------------------|
*   | 0.1     | Nandish          |            | Initial Version of Class      |
*   |-------------------------------------------------------------------------|
*/
public class IntegrationMessageHandler extends TriggerHandler {
    
    public override void afterUpdate() {
        sendDocumentsToKafka( (List<Integration_Message__c>)trigger.new, (Map<Id, Integration_Message__c>)trigger.oldMap );
        sendNotificationEmail( (List<Integration_Message__c>)trigger.new, (Map<Id, Integration_Message__c>)trigger.oldMap );
    }

    public override void afterInsert() {
       processWebservice( (List<Integration_Message__c>)trigger.new, (Map<Id, Integration_Message__c>)trigger.oldMap );
		sendProductDetailBackupandPower( (List<Integration_Message__c>)trigger.new, (Map<Id, Integration_Message__c>)trigger.oldMap);

    }

    private void sendDocumentsToKafka(List<Integration_Message__c> lstTriggerNew, Map<Id, Integration_Message__c> mapTriggerOld) {
            
        Set<Id> setContractIds = new Set<Id>();
        for(Integration_Message__c objIM : lstTriggerNew) {
            if( objIM.Contract__c != null && 
                objIM.Integration_Status__c == 'Success' && 
                (mapTriggerOld.get( objIM.Id ).Integration_Status__c == 'Not Processed' || mapTriggerOld.get( objIM.Id ).Integration_Status__c == 'In Progress') ) {
                setContractIds.add( objIM.Contract__c );
            }
        }
        if( !setContractIds.isEmpty() ) {
            Set<Id> setIMIds = new Set<Id>();
            for(Integration_Message__c objIM : [SELECT Id 
                                                FROM Integration_Message__c 
                                                WHERE Contract__c In :setContractIds AND Document__c != null AND Integration_Status__c = 'Not Processed']) {
                setIMIds.add( objIM.Id );                                    
            }
            if( !setIMIds.isEmpty() ) {
                database.executeBatch( new Batch_ContractDocumentsKafkaIntegration(setIMIds), 1 );
            }
        }
        /*
        Set<Id> setQuoteId = new Set<Id>();
        if( !setContractIds.isEmpty() ) {
            Set<Id> setQuoteId = new Set<Id>();
            for( Contract objContract : [SELECT SBQQ__Quote__c, Id 
                                        FROM Contract 
                                        WHERE Id In:setContractIds ]) {
                setQuoteId.add( objContract.SBQQ__Quote__c );
            }
            if( !setQuoteId.isEmpty() ) {
                Set<Id> setIMIds = new Set<Id>();
                for(Integration_Message__c objIM : [SELECT Id, Document__c
                                                    FROM Integration_Message__c 
                                                    WHERE Document__r.Quote__c In: setQuoteId
                                                    AND Integration_Status__c = 'Not Processed' ]) {
                    setIMIds.add( objIM.Id );
                }
                if( !setIMIds.isEmpty() ) {
                    database.executeBatch( new Batch_ContractDocumentsKafkaIntegration(setIMIds), 1 );
                }
            }
        }*/
    }

    /* 
        Does NOT do bulk Processing.
    */
    public void processWebservice( List<Integration_Message__c> lstTriggerNew, Map<Id, Integration_Message__c> mapTriggerOld ) {
        for( Integration_Message__c objIntegration : lstTriggerNew ) {
            if( objIntegration.Webservice_Request__c <> null && objIntegration.Webservice_Request__c <> 'FetchProductSubscription') { // Added Condition
                Type t = Type.forName(objIntegration.Webservice_Request__c);
                IntegrationExtension extension = (IntegrationExtension)t.newInstance();
                extension.runExtension(objIntegration.Webservice_params__c, objIntegration.Unique_Key__c);
                break;
            }      
        }
        
    }
    
    private void sendNotificationEmail( List<Integration_Message__c> lstTriggerNew, Map<Id, Integration_Message__c> mapTriggerOld ) {
        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();
        Organization org = [SELECT IsSandbox FROM Organization LIMIT 1];
        for( Integration_Message__c objMsg: lstTriggerNew ) {
            Integration_Message__c oldRecord = mapTriggerOld.get( objMsg.Id );
            Integration_Message__c newRecord = objMsg;
            if( newRecord.Number_of_Retrials__c != oldRecord.Number_of_Retrials__c && newRecord.Number_of_Retrials__c == 3 && newRecord.Error_Code__c <> null) {
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                String body = 'Error encountered on ' + objMsg.Name + ' for <a href="' + URL.getOrgDomainUrl().toExternalForm() + '/' + objMsg.Related_Record_Id__c + '">' + objMsg.Related_Record_Name__c + '<a><br/>Unique Key: ' + objMsg.Unique_Key__c
                + '<br/>'+
                'IM Message :' + '<a href="' + URL.getOrgDomainUrl().toExternalForm() + '/' + objMsg.Id + '">' + objMsg.Name +'<a>';
                //'IM Message : ' + URL.getOrgDomainUrl().toExternalForm() + '/' + objMsg.Id 
                if( org.IsSandbox ) {
                    message.setToAddresses( new List<String>{'samhatre@yotta.com', 'yash.p@cloudroute.in'});
                } else {
                    //message.setToAddresses(new List<String>{'itdevelopment@yotta.com'});message.setCcAddresses( new List<String>{'automation@yotta.com'});
                    message.setToAddresses(new List<String>{'automation@yotta.com'});
                    message.setCcAddresses( new List<String>{'yash.p@cloudroute.in'});
                }
                message.setHtmlBody( body );message.setSubject( 'Integration Failure For ' + objMsg.Related_Record_Name__c );messages.add(message);
            }
        }
        if( !messages.isEmpty() )
        	Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
    }
        /* Backup and Power JSON Integration Batch */
    private void sendProductDetailBackupandPower(List<Integration_Message__c> lstTriggerNew, Map<Id, Integration_Message__c> mapTriggerOld){
        for(Integration_Message__c objIntegration : lstTriggerNew){
            if(objIntegration.Webservice_Request__c == 'FetchProductSubscription'){
                List<String> ProductCodeList = objIntegration.Webservice_params__c.split(',');
                FetchBackupandPower.FetchSubscriptionDetails(ProductCodeList,objIntegration.Unique_Key__c);
                break;
            }
        }
    }
}