force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentVersionTriggerHandlerTest.cls
/**
* Created by yatishsalian on 28/06/22.
*/
@IsTest(SeeAllData = false)
public with sharing class ContentVersionTriggerHandlerTest {

@TestSetup static void makeData() {


    Account acct = new Account();
    acct.Name = 'Test Account1';
    insert acct;

    List<Document__c> DocInsert = new List<Document__c>();
    Document__c sobj1 = new Document__c( Name='Test',Account__c= acct.Id,Object__c = 'Account'
    );
    DocInsert.add(sobj1);
    Document__c sobj2 = new Document__c( Name='Test',Account__c= acct.Id,Object__c = 'Account'
    );
    DocInsert.add(sobj2);
    Document__c sobj3 = new Document__c( Name='Test',Account__c= acct.Id,Object__c = 'Account'
    );
    DocInsert.add(sobj3);
    if (!DocInsert.isEmpty()) {
        insert DocInsert;
    }
// Create Document
    ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
    insert contentVersion;
    List<ContentDocumentLink> Insertlist  = new List<ContentDocumentLink>();
//create ContentDocumentLink  record
    ContentDocumentLink cdl1 = new ContentDocumentLink();
    cdl1.LinkedEntityId = sobj1.Id;
    List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
    cdl1.ContentDocumentId = documents[0].Id;
    cdl1.ShareType = 'V';
    cdl1.Visibility = 'AllUsers';
    Insertlist.add(cdl1);
    ContentDocumentLink cdl2 = new ContentDocumentLink();
    cdl2.LinkedEntityId = sobj2.Id;
    cdl2.ContentDocumentId = documents[0].Id;
    cdl2.ShareType = 'V';
    cdl2.Visibility = 'AllUsers';
    Insertlist.add(cdl2);
    ContentDocumentLink cdl3 = new ContentDocumentLink();
    cdl3.LinkedEntityId = sobj3.Id;
    cdl3.ContentDocumentId = documents[0].Id;
    cdl3.ShareType = 'V';
    cdl3.Visibility = 'AllUsers';
    Insertlist.add(cdl3);

    if(!Insertlist.isEmpty()){
        insert Insertlist;
    }
}

@IsTest static void testOnAfterInsert(){

    Account acct = [SELECT Id FROM Account LIMIT 1];
    Document__c sobj1 = new Document__c( Name='Test',Account__c= acct.Id,Object__c = 'Account'
    );
    insert sobj1;
    ContentDocumentLink cdl1 = new ContentDocumentLink();
    cdl1.LinkedEntityId = sobj1.Id;
    List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
    cdl1.ContentDocumentId = documents[0].Id;
    cdl1.ShareType = 'V';
    cdl1.Visibility = 'AllUsers';
    insert cdl1;

}
}