force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Category__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Advance Payment</fullName>
            </value>
            <value>
                <fullName>Authority Letter / Resolution authorising the signatory to sign the Contract</fullName>
            </value>
            <value>
                <fullName>Authority Letter (supported by Board Resolution)</fullName>
            </value>
            <value>
                <fullName>Board Resolution</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Business Commencement Certificate</fullName>
            </value>
            <value>
                <fullName>Certificate of Commencement of Business (for public limited companies)</fullName>
            </value>
            <value>
                <fullName>Certificate of registration</fullName>
            </value>
            <value>
                <fullName>Current registered lease or licence Agreement along with Utility bill(s)</fullName>
            </value>
            <value>
                <fullName>Current Shareholding Pattern</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name anddetailsofcurrent Trustees/Chairman/President/Karta</fullName>
            </value>
            <value>
                <fullName>Declaration enlisting name and other details of current existing Partners</fullName>
            </value>
            <value>
                <fullName>Declaration on Letterhead enlisting all partners names with their inclusion date</fullName>
            </value>
            <value>
                <fullName>Design Document</fullName>
            </value>
            <value>
                <fullName>Documents described basis kind of the legal entity forming JVs/SPVs/consortium</fullName>
            </value>
            <value>
                <fullName>Domicile certificate with address issued by a municipal corporation</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>Duly executed Partnership Deed (as amended and updated up to date)</fullName>
            </value>
            <value>
                <fullName>Electricity bill</fullName>
            </value>
            <value>
                <fullName>Financial Statement(s) filed on RoC</fullName>
            </value>
            <value>
                <fullName>GST registration certificate</fullName>
            </value>
            <value>
                <fullName>Importer Exporter Code Number certificate</fullName>
            </value>
            <value>
                <fullName>List of present Director(s)</fullName>
            </value>
            <value>
                <fullName>Master Service Level Agreement (MSA)</fullName>
            </value>
            <value>
                <fullName>MoA / AoA</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>MSME Certificate (if registered)</fullName>
            </value>
            <value>
                <fullName>MSME Declaration (if not registered)</fullName>
            </value>
            <value>
                <fullName>MTNL-BSNL phone line bill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/About_Yotta_Summary_Type__c.field-meta.xml
<CustomField>
    <fullName>About_Yotta_Summary_Type__c</fullName>
    <label>About Yotta Summary Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brief</fullName>
            </value>
            <value>
                <fullName>Detailed</fullName>
                <default>true</default>
                <label>Detailed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Additional_CC_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_CC_s_Email__c</fullName>
    <inlineHelpText>In case of multiple Id&apos;s use &apos;;&apos; as separator</inlineHelpText>
    <label>Additional CC&apos;s Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Contracted__c.field-meta.xml
<CustomField>
    <fullName>Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Currency_Conversion_Factor__c.field-meta.xml
<CustomField>
    <fullName>Currency_Conversion_Factor__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Factor</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Quote #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Customer Accepted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBQQ__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <inlineHelpText>Please use font size of 10</inlineHelpText>
    <label>Scope of Work</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Technical_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Technical_Approval_Status__c</fullName>
    <label>Technical Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Required</fullName>
                <default>true</default>
                <label>Approval Required</label>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Term_Condition_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Term_Condition_Approval_Status__c</fullName>
    <label>Term &amp; Condition Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Yotta_s_Certifications_Required__c.field-meta.xml
<CustomField>
    <fullName>Yotta_s_Certifications_Required__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Yotta’s Certifications Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Yotta_s_Customers_Required__c.field-meta.xml
<CustomField>
    <fullName>Yotta_s_Customers_Required__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Yotta’s Customers Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Yotta_s_Products_and_Services_Required__c.field-meta.xml
<CustomField>
    <fullName>Yotta_s_Products_and_Services_Required__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Yotta’s Products and Services Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateQuotePDFDocumentTest.cls
@isTest
public class GenerateQuotePDFDocumentTest {
    @testSetup
    public static void pdfGenerationTest(){
        
        Account accountList = TestDataFactory.createAccount();
        insert accountList;
        System.debug('Id.valueOf(accountList.Id)' + Id.valueOf(accountList.Id));
        
        List<Contact> contactList = TestDataFactory.createContact(1,Id.valueOf(accountList.Id));
        insert contactList;
        
        List<Opportunity> opportunityList = TestDataFactory.createOpportunity(1,Id.valueOf(accountList.Id));
        insert opportunityList;        
        System.debug('Id.valueOf(opportunityList.Id)' + Id.valueOf(opportunityList[0].Id));
        
        Id opptyId = Id.valueOf(opportunityList[0].Id);
        
        List<Sbqq__Quote__c> quoteList = TestDataFactory.createQuote(1,Id.valueOf(accountList.Id),opptyId);
        insert quoteList;        
        System.debug('Id.valueOf(quoteList.Id)' + Id.valueOf(quoteList[0].Id));
        
        for (Sbqq__Quote__c quote:quoteList){
            quote.Customer_Contact__c = Id.valueOf(contactList[0].Id);
            quote.Additional_CC_s_Email__c = 'riya.sharma@comprotechnologies.com';
            quote.Contracted__c = False;
            quote.SBQQ__Type__c = 'Amendment';
            System.debug(quote.Customer_Contact__c + 'quote.Customer_Contact__c');
        }
        
            System.debug('update');
            upsert quoteList ;
        for (Sbqq__Quote__c quote1:quoteList){
            System.debug('quote.SBQQ__Status__c' + quote1.SBQQ__Status__c);
            //quote1.SBQQ__Status__c = 'Rejected';
            quote1.SCF_Type__c = 'Address Change';

        }
          Sbqq__Quote__c quote2 = new Sbqq__Quote__c (Quote_Name__c = 'Test'  , SBQQ__Account__c = Id.valueOf(accountList.Id),
                                                   SBQQ__StartDate__c=System.today(),SBQQ__EndDate__c =System.today().addYears(1), SBQQ__SubscriptionTerm__c = 24,
                                                   Currency_Conversion_Factor__c =1,
                                                   About_Yotta_Summary_Type__c = 'Detailed',Yotta_s_Products_and_Services_Required__c ='Yes',
                                                   Yotta_s_Certifications_Required__c = 'Yes',Yotta_s_Customers_Required__c = 'Yes',
                                                   SBQQ__Opportunity2__c= Id.valueOf(opportunityList[0].Id),
                                                   Scope_of_Work__c ='scope od work');
        insert quote2;
        quote2.SBQQ__Type__c = 'Amendment';
        quote2.SCF_Type__c = 'SCFBillCycleChange';
        update quote2;
        
         Sbqq__Quote__c quote3 = new Sbqq__Quote__c (Quote_Name__c = 'Test'  , SBQQ__Account__c = Id.valueOf(accountList.Id),
                                                   SBQQ__StartDate__c=System.today(),SBQQ__EndDate__c =System.today().addYears(1), SBQQ__SubscriptionTerm__c = 24,
                                                   Currency_Conversion_Factor__c =1,
                                                   About_Yotta_Summary_Type__c = 'Detailed',Yotta_s_Products_and_Services_Required__c ='Yes',
                                                   Yotta_s_Certifications_Required__c = 'Yes',Yotta_s_Customers_Required__c = 'Yes',
                                                   SBQQ__Opportunity2__c= Id.valueOf(opportunityList[0].Id),
                                                   Scope_of_Work__c ='scope od work');
        insert quote3;
        quote3.SBQQ__Type__c = 'Amendment';
        quote3.SCF_Type__c = 'SCFTransferOfService';
        update quote3;
        
         Sbqq__Quote__c quote4 = new Sbqq__Quote__c (Quote_Name__c = 'Test'  , SBQQ__Account__c = Id.valueOf(accountList.Id),
                                                   SBQQ__StartDate__c=System.today(),SBQQ__EndDate__c =System.today().addYears(1), SBQQ__SubscriptionTerm__c = 24,
                                                   Currency_Conversion_Factor__c =1,
                                                   About_Yotta_Summary_Type__c = 'Detailed',Yotta_s_Products_and_Services_Required__c ='Yes',
                                                   Yotta_s_Certifications_Required__c = 'Yes',Yotta_s_Customers_Required__c = 'Yes',
                                                   SBQQ__Opportunity2__c= Id.valueOf(opportunityList[0].Id),
                                                   Scope_of_Work__c ='scope od work');
        insert quote4;
        
        quote4.SBQQ__Type__c = 'Amendment';
        quote4.SCF_Type__c = 'CombinedSCF';
        update quote4;

        System.debug('quoteList' + quoteList);
        upsert quoteList ;
        for (Sbqq__Quote__c quote1:quoteList){
            System.debug('quote.SBQQ__Status__c' + quote1.SBQQ__Status__c);
            quote1.Technical_Approval_Status__c = 'Approved';
            quote1.Term_Condition_Approval_Status__c = 'Approved';
            quote1.SBQQ__Status__c = 'Approved';
            //quote1.SCF_Type__c = 'Address Change';

        }
        upsert quoteList;
        
        
        
    }
    
    static testMethod void pdfGenerationCheckTest(){
        List<Sbqq__Quote__c> a = [select id,SCF_Type__c,SBQQ__Account__c,SBQQ__Status__c from Sbqq__Quote__c];
        //System.debug('a.SBQQ__Status__c' + a.SBQQ__Status__c);
        for(Sbqq__Quote__c quote: a){
        GenerateQuotePDFDocument.pdfGenerationCheck(quote.Id,quote.SCF_Type__c);
        GenerateQuotePDFDocument.SavePDFAsFile(quote.Id,quote.SCF_Type__c);
        GenerateQuotePDFDocument.sendEmail(quote.Id,quote.SCF_Type__c);

        try{
            GenerateContract.createContract(quote.Id);
        }catch(Exception e){}
        
        Document__c doc = new Document__c();
        doc.Document_Category__c = 'Quote';
        doc.Document__c = 'Proposal Quote';
        doc.Quote__c = quote.Id;
        doc.Account__c = quote.SBQQ__Account__c;
        doc.Object__c = 'Quote';
        insert doc;

        try{
            GenerateContract.createContract(quote.Id);
        }catch(Exception e){}
        }
    }
}