force-app/main/default/objects/Contact/fields/Deactivation_Status__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Status__c</fullName>
    <description>Created By Nandish for Contact Deactivation</description>
    <label>Deactivation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request Generated</fullName>
            </value>
            <value>
                <fullName>Deactivation in Progress</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Deactivation Approved</fullName>
            </value>
            <value>
                <fullName>Deactivation Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Generate_Deactivation_Request__c.field-meta.xml
<CustomField>
    <fullName>Generate_Deactivation_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created by Nandish for Contact Deactivation Integration</description>
    <label>Generate Deactivation Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/isPartner__c.field-meta.xml
<CustomField>
    <fullName>isPartner__c</fullName>
    <formula>Account.Is_Ready_for_Integration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Ready for Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Replacement_Contact__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By Nandish for Contact Deactivation</description>
    <label>Replacement Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Active Contact from the same Account.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>Contact.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Replaced Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To Kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorised_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Authorised Signatory</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Customer Authorised Signatory)</relationshipLabel>
    <relationshipName>Contracts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Contact Billing Contact)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Exec_Mgmt_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Exec_Mgmt_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Exec Mgmt Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Customer Exec Mgmt Contact)</relationshipLabel>
    <relationshipName>Contracts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_SPoC__c.field-meta.xml
<CustomField>
    <fullName>Customer_SPoC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer SPoC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Support_To_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Tech_SPOC__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tech_SPOC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Tech SPOC</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Support_To_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Customer Tech SPOC)</relationshipLabel>
    <relationshipName>CustTechSPOC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Last_Quote__c.field-meta.xml
<CustomField>
    <fullName>Last_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Last Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Contract__c.field-meta.xml
<CustomField>
    <fullName>Original_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Send_To_API_Layer__c.field-meta.xml
<CustomField>
    <fullName>Send_To_API_Layer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to send Contract to Kafka</description>
    <inlineHelpText>Check to send Contract to Kafka</inlineHelpText>
    <label>Send To Kafka</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <label>Approved</label>
</RecordType>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Request_Template__mdt/Integration_Request_Template__mdt.object-meta.xml
<CustomObject>
    <label>Integration Request Template</label>
    <pluralLabel>Integration Request Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Request_Template__mdt/fields/All_Fields__c.field-meta.xml
<CustomField>
    <fullName>All_Fields__c</fullName>
    <label>All Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Authorised_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Customer_Authorised_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GG: 26-Oct Created to get the Contact from Contract then make it available for update on Contract.</description>
    <label>Customer Authorised Signatory</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria- Customer Authorised</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Authorised Signatory)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Billing Contact)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Status__c</field>
            <operation>notEqual</operation>
            <value>Inactive</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
/* ****************************************************************************************************************
Name          : ContactTriggerHandler
Description   : ContactTriggerHandler is a handler class for Contact Trigger.
Author        : Nandish Shenoy  
Creation Date : 10/5/2020
Modified Date : 29/5/2020
**************************************************************************************************************** */
public class ContactTriggerHandler extends TriggerHandler {

    private static List<Contact> lstContactsToSend = new List<Contact>();
    private static Set<Id> setReplaceContacts = new Set<Id>();

    public override void beforeInsert() {
        try {
            filterContactsToSendToKafka((List<Contact>) trigger.new, null);
        } catch (Exception e) {
            System.debug('EXCEPTION AT->' + e.getLineNumber() + ' MESSAGE->' + e.getMessage());
        }
    }

    public override void beforeUpdate() {
        try {
            system.debug('=====');
            validateContactDeactivation((Map<Id, Contact>) trigger.newMap, (Map<Id, Contact>) trigger.oldMap);
            filterContactsToSendToKafka((List<Contact>) trigger.new, (Map<Id, Contact>) trigger.oldMap);
        } catch (Exception e) {
            System.debug('EXCEPTION AT->' + e.getLineNumber() + ' MESSAGE->' + e.getMessage());
        }
    }

    public override void afterInsert() {
        try {


            if (!lstContactsToSend.isEmpty()) {
                sendContactsDetailsToSAP(lstContactsToSend);
            }
        } catch (Exception e) {
            System.debug('EXCEPTION AT->' + e.getLineNumber() + ' MESSAGE->' + e.getMessage());
        }
    }

    public override void afterUpdate() {
        try {
            if (!setReplaceContacts.isEmpty()) {
                replaceDeactivatedContacts((Map<Id, Contact>) trigger.newMap);
            }
            if (!lstContactsToSend.isEmpty()) {
                sendContactsDetailsToSAP(lstContactsToSend);
            }
        } catch (Exception e) {
            System.debug('EXCEPTION AT->' + e.getLineNumber() + ' MESSAGE->' + e.getMessage());
        }
    }

    //checks if value for a particular field has changed
    public Boolean isUpdated(Id recordId, String fieldName) {
        Object oldValue = (Object) ((Contact) (Trigger.oldMap.get(recordId))).get(fieldName);
        Object newValue = (Object) ((Contact) (Trigger.newMap.get(recordId))).get(fieldName);
        if (oldValue != newValue)
            return TRUE;
        else
                return FALSE;
    }

    private Boolean isFieldChanged(sObject sObj, Set<String> setFields) {
        if (Boolean.valueOf(sObj.get('ispartner__c')) == false) {
            return false;
        }
        for (String fieldName : setFields) {
            if (!String.isBlank(fieldName.trim()) && !fieldName.contains('.') && isUpdated(sObj.Id, fieldName.trim())) {
                return true;
            }
        }
        return false;
    }

    private void filterContactsToSendToKafka(List<Contact> lstTriggerNew, Map<Id, Contact> mapTriggerOld) {
        lstContactsToSend = new List<Contact>();
        Set<String> setFields = new Set<String>();
        for (Integration_Request_Template__mdt irt : [
                SELECT All_Fields__c
                FROM Integration_Request_Template__mdt
                WHERE DeveloperName = :IntegrationConstants.STR_CONTACT_TEMPLATE_NAME
                LIMIT 1
        ]) {
            setFields.addAll(irt.All_Fields__c.split(','));
        }
        if (mapTriggerOld <> null) {
            for (Contact objContact : lstTriggerNew) {
                if ((objContact.Send_To_API_Layer__c && objContact.Send_To_API_Layer__c <> mapTriggerOld.get(objContact.Id).Send_To_API_Layer__c) || isFieldChanged(objContact, setFields)) {
                    objContact.Send_To_API_Layer__c = false;
                    lstContactsToSend.add(objContact);
                }
            }
        } else {
            for (Contact objContact : lstTriggerNew) {
                if (objContact.Send_To_API_Layer__c) {
                    objContact.Send_To_API_Layer__c = false;
                    lstContactsToSend.add(objContact);
                }
            }
        }
    }

    private void sendContactsDetailsToSAP(List<Contact> lstContacts) {
        IntegrationBase iBase = new IntegrationBase();
        List<Integration_Message__c> lstIntegrationMessagesToInsert = new List<Integration_Message__c>();
        for (Contact objContact : lstContacts) {
            Integration_Message__c objMessage = new Integration_Message__c();
            objMessage = iBase.createIMRecord(null, objContact.Id, '', '', '', '', '', '', true, IntegrationConstants.STR_CONTACT_TEMPLATE_NAME);
            lstIntegrationMessagesToInsert.add(objMessage);
            objMessage.Unique_Key__c = objContact.Id + '_' + IntegrationConstants.STR_CONTACT_TEMPLATE_NAME + '_' + 'Pending';
        }
        if (!lstIntegrationMessagesToInsert.isEmpty()) {
            upsert lstIntegrationMessagesToInsert Unique_Key__c;
            OutboundIntegrationBatch batchJob = new OutboundIntegrationBatch(lstIntegrationMessagesToInsert);
            database.executeBatch(batchJob, 1);
        }
    }

    private void validateContactDeactivation(Map<Id, Contact> mapTriggerNew, Map<Id, Contact> mapTriggerOld) {
        Set<Id> setContactsDeactivated = new Set<Id>();

        for (Contact objContact : mapTriggerNew.values()) {
            if (objContact.Generate_Deactivation_Request__c && !mapTriggerOld.get(objContact.Id).Generate_Deactivation_Request__c) {
                setContactsDeactivated.add(objContact.Id);
                objContact.Generate_Deactivation_Request__c = false;
            }
            if (objContact.Replacement_Contact__c != mapTriggerOld.get(objContact.Id).Replacement_Contact__c && objContact.Replacement_Contact__c != null) {
                if (objContact.Deactivation_Status__c == 'Deactivation Denied') {
                    objContact.Deactivation_Status__c = 'Deactivated';
                    objContact.Status__c = 'Inactive';
                    objContact.Send_To_API_Layer__c = true;
                } else {
                    setReplaceContacts.add(objContact.Id);
                }
            }
            if (objContact.Deactivation_Status__c == 'Deactivation Approved' && objContact.Deactivation_Status__c != mapTriggerOld.get(objContact.Id).Deactivation_Status__c) {
                objContact.Deactivation_Status__c = 'Deactivated';
                objContact.Status__c = 'Inactive';
                objContact.Send_To_API_Layer__c = true;
            }
        }

        if (setContactsDeactivated.isEmpty() && setReplaceContacts.isEmpty()) return ;

        List<String> lstContactFields = new List<String>{
                '(Select Id From ContractsSigned Where Status !=\'Renewed\' And Status !=\'Expired\')',
                '(Select Id From Contracts4__r Where Status !=\'Renewed\' And Status !=\'Expired\')',
                '(Select Id From Contracts1__r Where Status !=\'Renewed\' And Status !=\'Expired\')',
                '(Select Id From Contracts3__r Where Status !=\'Renewed\' And Status !=\'Expired\')',
                '(Select Id From Contracts__r Where Status !=\'Renewed\' And Status !=\'Expired\')',
                '(Select Id From CustTechSPOC__r Where Status !=\'Renewed\' And Status !=\'Expired\')',
                '(Select Id From Quotes__r)',
                '(Select Id From Quotes1__r)',
                '(Select Id From Quotes2__r)',
                '(Select Id From Quotes3__r)',
                '(Select Id From Quotes4__r)',
                '(Select Id From Quotes5__r)'
        };

        for (Contact objContact : (List<Contact>) Database.query('Select Id, Replacement_Contact__c,' + String.join(lstContactFields, ',') + ' From Contact Where Id In :setContactsDeactivated')) {
            Contact objNewTrigger = mapTriggerNew.get(objContact.Id);
            if (!objContact.ContractsSigned.isEmpty() || !objContact.Contracts4__r.isEmpty() || !objContact.Contracts1__r.isEmpty() ||
                    !objContact.Contracts3__r.isEmpty() || !objContact.Contracts__r.isEmpty() || !objContact.CustTechSPOC__r.isEmpty() ||
                    !objContact.Quotes__r.isEmpty() || !objContact.Quotes1__r.isEmpty() || !objContact.Quotes2__r.isEmpty() ||
                    !objContact.Quotes3__r.isEmpty() || !objContact.Quotes4__r.isEmpty() || !objContact.Quotes5__r.isEmpty()) {
                if (objNewTrigger.Replacement_Contact__c == null) {
                    objNewTrigger.addError('Please provide a replacement Contact');
                } else {
                    objNewTrigger.Deactivation_Status__c = 'Deactivated';
                    objNewTrigger.Status__c = 'Inactive';
                }
            } else {
                objNewTrigger.Send_To_API_Layer__c = true;
                objNewTrigger.Deactivation_Status__c = 'Deactivation in Progress';
            }
        }
    }

    public void replaceDeactivatedContacts(Map<Id, Contact> mapTriggerNew) {
        List<Contract> lstContractsToUpdate = new List<Contract>();
        List<SBQQ__Quote__c> lstQuoteToUpdate = new List<SBQQ__Quote__c>();
        for (Contract objContract : [
                SELECT Id, Customer_Billing_Contact__c, Customer_Authorised_Signatory__c,
                        Customer_Exec_Mgmt_Contact__c, Customer_SPoC__c, Customer_Tech_SPOC__c, CustomerSignedId, Customer_Contact__c
                FROM Contract
                WHERE (Customer_Billing_Contact__c In :setReplaceContacts
                OR Customer_Authorised_Signatory__c In :setReplaceContacts
                OR Customer_Exec_Mgmt_Contact__c In :setReplaceContacts
                OR Customer_SPoC__c In :setReplaceContacts
                OR Customer_Tech_SPOC__c In :setReplaceContacts
                OR CustomerSignedId In :setReplaceContacts
                OR Customer_Contact__c In :setReplaceContacts) And Status NOT In ( 'Expired', 'Renewed' )
        ]) {

            if (objContract.Customer_Billing_Contact__c != null && setReplaceContacts.contains(objContract.Customer_Billing_Contact__c)) {
                Contact objContact = mapTriggerNew.get(objContract.Customer_Billing_Contact__c);
                objContract.Customer_Billing_Contact__c = objContact.Replacement_Contact__c;
            }
            if (objContract.Customer_Authorised_Signatory__c != null && setReplaceContacts.contains(objContract.Customer_Authorised_Signatory__c)) {
                Contact objContact = mapTriggerNew.get(objContract.Customer_Authorised_Signatory__c);
                objContract.Customer_Authorised_Signatory__c = objContact.Replacement_Contact__c;
            }
            if (objContract.Customer_Exec_Mgmt_Contact__c != null && setReplaceContacts.contains(objContract.Customer_Exec_Mgmt_Contact__c)) {
                Contact objContact = mapTriggerNew.get(objContract.Customer_Exec_Mgmt_Contact__c);
                objContract.Customer_Exec_Mgmt_Contact__c = objContact.Replacement_Contact__c;
            }
            if (objContract.Customer_SPoC__c != null && setReplaceContacts.contains(objContract.Customer_SPoC__c)) {
                Contact objContact = mapTriggerNew.get(objContract.Customer_SPoC__c);
                objContract.Customer_SPoC__c = objContact.Replacement_Contact__c;
            }
            if (objContract.Customer_Tech_SPOC__c != null && setReplaceContacts.contains(objContract.Customer_Tech_SPOC__c)) {
                Contact objContact = mapTriggerNew.get(objContract.Customer_Tech_SPOC__c);
                objContract.Customer_Tech_SPOC__c = objContact.Replacement_Contact__c;
            }
            if (objContract.CustomerSignedId != null && setReplaceContacts.contains(objContract.CustomerSignedId)) {
                Contact objContact = mapTriggerNew.get(objContract.CustomerSignedId);
                objContract.CustomerSignedId = objContact.Replacement_Contact__c;
            }
            if (objContract.Customer_Contact__c != null && setReplaceContacts.contains(objContract.Customer_Contact__c)) {
                Contact objContact = mapTriggerNew.get(objContract.Customer_Contact__c);
                objContract.Customer_Contact__c = objContact.Replacement_Contact__c;
            }
            lstContractsToUpdate.add(objContract);
        }

        for (SBQQ__Quote__c objQuote : [
                SELECT Id, Customer_Billing_Contact__c, Customer_Authorised_Signatory__c,
                        SBQQ__PrimaryContact__c, Customer_Exec_Mgmt_Contact__c, Customer_SPoC__c, Customer_Tech_SPOC__c, Customer_Contact__c
                FROM SBQQ__Quote__c
                WHERE (Customer_Billing_Contact__c In :setReplaceContacts
                OR Customer_Authorised_Signatory__c In :setReplaceContacts
                OR Customer_Exec_Mgmt_Contact__c In :setReplaceContacts
                OR Customer_SPoC__c In :setReplaceContacts
                OR Customer_Tech_SPOC__c In :setReplaceContacts
                OR SBQQ__PrimaryContact__c In :setReplaceContacts
                OR Customer_Contact__c In :setReplaceContacts)
                AND Contracted__c = False
        ]) {

            if (objQuote.Customer_Billing_Contact__c != null && setReplaceContacts.contains(objQuote.Customer_Billing_Contact__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.Customer_Billing_Contact__c);
                objQuote.Customer_Billing_Contact__c = objContact.Replacement_Contact__c;
            }
            if (objQuote.Customer_Authorised_Signatory__c != null && setReplaceContacts.contains(objQuote.Customer_Authorised_Signatory__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.Customer_Authorised_Signatory__c);
                objQuote.Customer_Authorised_Signatory__c = objContact.Replacement_Contact__c;
            }
            if (objQuote.Customer_Exec_Mgmt_Contact__c != null && setReplaceContacts.contains(objQuote.Customer_Exec_Mgmt_Contact__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.Customer_Exec_Mgmt_Contact__c);
                objQuote.Customer_Exec_Mgmt_Contact__c = objContact.Replacement_Contact__c;
            }
            if (objQuote.Customer_SPoC__c != null && setReplaceContacts.contains(objQuote.Customer_SPoC__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.Customer_SPoC__c);
                objQuote.Customer_SPoC__c = objContact.Replacement_Contact__c;
            }
            if (objQuote.Customer_Tech_SPOC__c != null && setReplaceContacts.contains(objQuote.Customer_Tech_SPOC__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.Customer_Tech_SPOC__c);
                objQuote.Customer_Tech_SPOC__c = objContact.Replacement_Contact__c;
            }
            if (objQuote.SBQQ__PrimaryContact__c != null && setReplaceContacts.contains(objQuote.SBQQ__PrimaryContact__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.SBQQ__PrimaryContact__c);
                objQuote.SBQQ__PrimaryContact__c = objContact.Replacement_Contact__c;
            }
            if (objQuote.Customer_Contact__c != null && setReplaceContacts.contains(objQuote.Customer_Contact__c)) {
                Contact objContact = mapTriggerNew.get(objQuote.Customer_Contact__c);
                objQuote.Customer_Contact__c = objContact.Replacement_Contact__c;
            }

            lstQuoteToUpdate.add(objQuote);
        }
        try {
            System.debug('ContractList' + lstContractsToUpdate);
            if (!lstContractsToUpdate.isEmpty()) {
                update lstContractsToUpdate;
            }
            System.debug('QuoteList' + lstQuoteToUpdate);
            if (!lstQuoteToUpdate.isEmpty()) {
                update lstQuoteToUpdate;
            }
        } catch (Exception e) {
            System.debug('Error Occured  ==' + e.getLineNumber() + '====' + e.getMessage());
            insert new Error_Log__c(Type__c = e.getCause() + '=====' + e.getLineNumber(), Message__c = e.getMessage());
        }
    }
}