force-app/main/default/objects/Billing_Group__c/Billing_Group__c.object-meta.xml
<CustomObject>
    <label>Billing Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Billing Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Group__c/fields/Bandwidth_Type__c.field-meta.xml
<CustomField>
    <fullName>Bandwidth_Type__c</fullName>
    <label>Bandwidth Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Burstable</fullName>
            </value>
            <value>
                <fullName>Data Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN21</fullName>
                <label>YNS Mumbai – HO</label>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN23</fullName>
                <label>YNS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN22</fullName>
                <label>YNS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS ND1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <label>YNS ND1 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/reset__c.field-meta.xml
<CustomField>
    <fullName>reset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>reset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Groups (Support To Account)</relationshipLabel>
    <relationshipName>Billing_Groups_Support_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Total_Burstable_Up_To__c.field-meta.xml
<CustomField>
    <fullName>Total_Burstable_Up_To__c</fullName>
    <label>Total Burstable Up To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Group__c/fields/Total_Contracted_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Contracted_Value__c</fullName>
    <label>Total Contracted Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Bill Cycle Change</fullName>
            </value>
            <value>
                <fullName>Contract Line SCF</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Support_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Support_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Ship To Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bandwidth_Type__c.field-meta.xml
<CustomField>
    <fullName>Bandwidth_Type__c</fullName>
    <label>Bandwidth Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Burstable</fullName>
            </value>
            <value>
                <fullName>Data Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IN12</fullName>
                <label>YIS NM1 - Data Center</label>
            </value>
            <value>
                <fullName>Customer Site</fullName>
            </value>
            <value>
                <fullName>IN14</fullName>
                <label>YIS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN15</fullName>
                <label>YIS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN11</fullName>
                <label>Mumbai Region</label>
            </value>
            <value>
                <fullName>IN16</fullName>
                <label>YIS TB1 - Data Center</label>
            </value>
            <value>
                <fullName>IN18</fullName>
                <label>YIS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN19</fullName>
                <label>YIS AS1 - Office</label>
            </value>
            <value>
                <fullName>I101</fullName>
                <label>YIS TN1 - Data Center</label>
            </value>
            <value>
                <fullName>I102</fullName>
                <label>YIS TB2 - Data Center</label>
            </value>
            <value>
                <fullName>IN26</fullName>
                <label>YIS G1 - Office</label>
            </value>
            <value>
                <fullName>IN29</fullName>
                <label>YIS TS - Office</label>
            </value>
            <value>
                <fullName>DEL</fullName>
                <isActive>false</isActive>
                <label>DEL</label>
            </value>
            <value>
                <fullName>IN13</fullName>
                <isActive>false</isActive>
                <label>Navi Mumbai – DC2</label>
            </value>
            <value>
                <fullName>IN22</fullName>
                <isActive>false</isActive>
                <label>YNS AP1 - Data Center</label>
            </value>
            <value>
                <fullName>IN25</fullName>
                <isActive>false</isActive>
                <label>YNS D1 - Data Center</label>
            </value>
            <value>
                <fullName>IN23</fullName>
                <isActive>false</isActive>
                <label>YNS KA1 - Data Center</label>
            </value>
            <value>
                <fullName>IN21</fullName>
                <isActive>false</isActive>
                <label>YNS Mumbai – HO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Variable_Product__c.field-meta.xml
<CustomField>
    <fullName>Variable_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Variable Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__ProductOption__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NMDC1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Bill_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Start_Date__c</fullName>
    <label>Bill Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Billing_Group__c.field-meta.xml
<CustomField>
    <fullName>Billing_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Group</label>
    <referenceTo>Billing_Group__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <label>Quote Line Sr #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__ProductOption__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProductOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product option that generated this line (if any).</description>
    <inlineHelpText>Product option that generated this line (if any).</inlineHelpText>
    <label>Product Option</label>
    <referenceTo>SBQQ__ProductOption__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SCF_Type__c.field-meta.xml
<CustomField>
    <fullName>SCF_Type__c</fullName>
    <label>SCF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Deactivation</fullName>
            </value>
            <value>
                <fullName>Facility Change</fullName>
            </value>
            <value>
                <fullName>New Line</fullName>
            </value>
            <value>
                <fullName>Price Change</fullName>
            </value>
            <value>
                <fullName>Transfer of Service</fullName>
            </value>
            <value>
                <fullName>Upgrade/Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
                <default>true</default>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Deployment Pending</fullName>
            </value>
            <value>
                <fullName>Under Delivery</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Amendment in progress</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Under Decommission</fullName>
            </value>
            <value>
                <fullName>Under Commissioning</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Technical_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Technical_End_Date__c</fullName>
    <label>Technical End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Technical_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Technical_Start_Date__c</fullName>
    <label>Technical Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Variable_Product__c.field-meta.xml
<CustomField>
    <fullName>Variable_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Variable Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_BillingGroupUpdate.cls
public class Batch_BillingGroupUpdate implements Database.Batchable < SObject > , Database.Stateful {
	//public List < Billing_Group__c > billGroupList {get;set;}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator('SELECT Id,Bandwidth_Type__c,Total_Contracted_Value__c,Total_Burstable_Up_To__c,Status__c,reset__c FROM Billing_Group__c WHERE reset__c = true');
	}

	public void execute(Database.BatchableContext bc, List < Billing_Group__c > scope) {
		Map < Id, List < SBQQ__Subscription__c > > billingGroupSubMap = new Map < Id, List < SBQQ__Subscription__c >> ();
		//billGroupList = new List < Billing_Group__c > ();

		List < SBQQ__Subscription__c > subList = [SELECT Id, SCF_Type__c, S_No__c, SBQQ__RequiredById__c, Base_Value__c, SBQQ__Bundle__c, Variable_Product__c, SBQQ__ProductOption__c, SBQQ__Contract__c,
                            Technical_Start_Date__c, Technical_End_Date__c, Bill_Start_Date__c,SBQQ__Contract__r.AccountId, SBQQ__Contract__r.Support_To_Account__c, Location__c, Billing_Group__c,
                            SBQQ__Quantity__c, SBQQ__SegmentIndex__c, Component_Quantity__c, Burstable_Upto__c, Burstable_upto_bundle__c, SBQQ__Product__c, SBQQ__Product__r.Model_Name__c,
                            Product_Family__c, Product_Line__c, SBQQ__ProductName__c, Bandwidth_Type__c, SBQQ__TerminatedDate__c, Status__c FROM SBQQ__Subscription__c
                            WHERE Billing_Group__c IN: scope AND Variable_Product__c = False AND SBQQ__Quantity__c >= 0 AND Technical_Start_Date__c != null AND Technical_End_Date__c = null];
        
		if (!subList.isEmpty() && subList.size() > 0) {
			for (SBQQ__Subscription__c sub: subList) {
				List < SBQQ__Subscription__c > subList1;
				if (billingGroupSubMap.containsKey(sub.Billing_Group__c))
					subList1 = billingGroupSubMap.get(sub.Billing_Group__c);
				else
					subList1 = new List < SBQQ__Subscription__c > ();
				subList1.add(sub);
				billingGroupSubMap.put(sub.Billing_Group__c, subList1);
			}
		}
		for (Billing_Group__c bg: scope) {
			bg.Total_Contracted_Value__c = 0;
			bg.Total_Burstable_Up_To__c = 0;
            Decimal compQ = 0;
			//bg.Status__c = 'Inactive';
			
            if (billingGroupSubMap.containsKey(bg.Id)) {
				for (SBQQ__Subscription__c sub: billingGroupSubMap.get(bg.Id)) {
					//if (!sub.Variable_Product__c) {
						if (bg.Bandwidth_Type__c == 'Burstable') {
							if(sub.Technical_End_Date__c != NULL || ((sub.Status__c == 'Renewed' || sub.Status__c=='Decommissioned') && sub.Bill_Start_Date__c != null )) {
								//billingGrp.reset__c = true;
								// if (sub.Technical_End_Date__c != NULL || (sub.Status__c == 'Renewed' && sub.Bill_Start_Date__c != null )) {

								//bg.Total_Contracted_Value__c = sub.Base_Value__c;
							}else {
								bg.Total_Contracted_Value__c += sub.Base_Value__c;
							}
							if (compQ < sub.Base_Value__c) {
								compQ = sub.Base_Value__c;
								bg.Total_Burstable_Up_To__c = sub.Burstable_upto_bundle__c;
							}

							} else if (bg.Bandwidth_Type__c == 'Data Transfer') {
								if(sub.Technical_End_Date__c != NULL || ((sub.Status__c == 'Renewed' || sub.Status__c=='Decommissioned') && sub.Bill_Start_Date__c != null )) {
								//billingGrp.reset__c = true;
								// if (sub.Technical_End_Date__c != NULL || (sub.Status__c == 'Renewed' && sub.Bill_Start_Date__c != null )) {

									//bg.Total_Contracted_Value__c -= sub.Base_Value__c;
								}else {
								bg.Total_Contracted_Value__c += sub.Base_Value__c;
								}
						/*if (bg.Bandwidth_Type__c == 'Burstable') {
							//if (!sub.Variable_Product__c && sub.Technical_Start_Date__c != null && sub.Technical_End_Date__c == null) {
								if (compQ < sub.Base_Value__c) {
									compQ = sub.Base_Value__c;
									bg.Total_Burstable_Up_To__c = sub.Burstable_upto_bundle__c;
								}
							//}
						}*/
					//}
				}
					if(sub.Status__c=='Active'){
						bg.status__c='Active';
					}
				}

				//bg.Status__c = 'Active';
			}
			bg.reset__c = false;
			//billGroupList.add(bg);
		}
		if (scope != null && scope.size() > 0)
			update scope;
	}

	public void finish(Database.BatchableContext bc) {}
}