force-app/main/default/objects/Billing_Group__c/Billing_Group__c.object-meta.xml
<CustomObject>
    <label>Billing Group</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Billing Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <label>Contract Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <displayFormat>IM - {000000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Message__c/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Message__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <description>Format of this field will be
Failed/ NP and Valid for Retrial - Object type_Record ID_IntegrationStatus
Success and Not Valid for Retrial - Object type_Record ID_IntegrationStatus_Im Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SObject Type_SFDC Record ID_Status_AutoNumber(For Success)</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Billing_Group__c.field-meta.xml
<CustomField>
    <fullName>Billing_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Group</label>
    <referenceTo>Billing_Group__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number__c</fullName>
    <formula>SBQQ__Contract__r.Contract_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/is_ready_for_billing_group_integration__c.field-meta.xml
<CustomField>
    <fullName>is_ready_for_billing_group_integration__c</fullName>
    <formula>ISPICKVAL(SBQQ__Contract__r.Status, &apos;Approved&apos;) || ISPICKVAL(SBQQ__Contract__r.Status, &apos;Activated&apos;) || ISPICKVAL(SBQQ__Contract__r.Status, &apos;Expired&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>is ready for billing group integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Line_Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Line_Sr_No__c</fullName>
    <label>Line Item Sr #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
                <default>true</default>
                <label>Contracted</label>
            </value>
            <value>
                <fullName>Deployment Pending</fullName>
            </value>
            <value>
                <fullName>Under Delivery</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Amendment in progress</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Under Decommission</fullName>
            </value>
            <value>
                <fullName>Under Commissioning</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Variable_Product__c.field-meta.xml
<CustomField>
    <fullName>Variable_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Variable Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_PushBillingGroupSOFsToKafka.cls
/* ****************************************************************************************************************
Name          : Batch_PushBillingGroupSOFsToKafka
Description   : Class to call custom Webservice through Composite Interface
Author        : Nandish Shenoy  
Creation Date : 06/10/2020
Modified Date : 20/07/2021
**************************************************************************************************************** */
public without sharing class Batch_PushBillingGroupSOFsToKafka implements Database.Batchable<sObject>,Database.Stateful, Database.AllowsCallouts {

    public String requestId ;
    public String params ;
    public Boolean isFailed = false;
    public String Body;

    public Batch_PushBillingGroupSOFsToKafka(String params, String requestId) {
        this.params = params;
        this.requestId = requestId;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String billingGrpId = params;
        setIntegrationMessageStatus('In Progress');
        String strQuery = (!Test.isRunningTest()) ? 
                            'Select Id, Name, SBQQ__Contract__c, SBQQ__Contract__r.Contract_Number__c, Line_Sr_No__c, SBQQ__Product__c, Status__c From SBQQ__Subscription__c Where Billing_Group__c = :billingGrpId And is_ready_for_billing_group_integration__c=true And Variable_Product__c=false ORDER BY SBQQ__Contract__r.Contract_Number__c DESC' 
                        : 'Select Id, Name, SBQQ__Contract__c, SBQQ__Contract__r.Contract_Number__c, Line_Sr_No__c, SBQQ__Product__c, Status__c From SBQQ__Subscription__c Where Billing_Group__c = :billingGrpId';
        return Database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
        /*BillingGrpSOFResponse response = new BillingGrpSOFResponse();
        SBQQ__Subscription__c objSub = (SBQQ__Subscription__c)scope[0];
        response.requestId = requestId;
        response.sofnumber = objSub.SBQQ__Contract__r.Contract_Number__c;
        response.lineitemnumber = objSub.Line_Sr_No__c;
        response.sof_list = new Set<String>();
        for( SBQQ__Subscription__c objSubs : [SELECT Id, SBQQ__Contract__r.Contract_Number__c
                                                FROM SBQQ__Subscription__c
                                                WHERE SBQQ__Product__c = :objSub.SBQQ__Product__c
                                                 ]) {//AND is_ready_for_billing_group_integration__c=true
            response.sof_list.add( objSubs.SBQQ__Contract__r.Contract_Number__c );
        }

        //String access_token = (new IntegrationBase()).getAuthorizationToken( Label.Kafka_Integration_Billing_Authorization );*/

        BGResponseWrapper response = new BGResponseWrapper();
        response.billing_group_id = this.params;
        response.requestId = this.requestId;
        response.sofdetails = new List<SOFDetailsWrapper>();
        
        Map<String, List<SBQQ__Subscription__c>> mapContractNumberToLstSubs = new Map<String, List<SBQQ__Subscription__c>>();

        for( SBQQ__Subscription__c objSubs : (List<SBQQ__Subscription__c>)scope) {
            if( !mapContractNumberToLstSubs.containsKey(objSubs.SBQQ__Contract__r.Contract_Number__c) ) {
                mapContractNumberToLstSubs.put( objSubs.SBQQ__Contract__r.Contract_Number__c, new List<SBQQ__Subscription__c>{objSubs} );
            } else {
                mapContractNumberToLstSubs.get( objSubs.SBQQ__Contract__r.Contract_Number__c ).add( objSubs );
            }
        }

        for( String strContractNumber :  mapContractNumberToLstSubs.keySet() ) {
            SOFDetailsWrapper sofDetail = new SOFDetailsWrapper();
            sofDetail.sof_no = strContractNumber;
            sofDetail.line_items = new List<LineItemDetails>();
            for( SBQQ__Subscription__c objSubs : mapContractNumberToLstSubs.get(strContractNumber)) {
                LineItemDetails lineItem = new LineItemDetails();
                lineItem.line_no = objSubs.Line_Sr_No__c;
                lineItem.line_state = objSubs.Status__c;
                sofDetail.line_items.add( lineItem );
            }
            response.sofdetails.add( sofDetail );  
        }

        HttpResponse res = (new IntegrationBase()).getAuthorizationToken( Label.Kafka_Integration_Billing_Authorization );
        
        if( res.getStatusCode() == 200 || res.getStatusCode() == 201 ) {
            IntegrationBase.kafkaAuthToken token = (IntegrationBase.kafkaAuthToken)JSON.deserialize(res.getBody(), IntegrationBase.kafkaAuthToken.class);
            String access_token = token.access_token;
            HttpRequest req = new HttpRequest();
            Http mHttp = new Http();
            String resp = JSON.serialize(response);
            system.debug('resp' + resp);
            req.setMethod('POST'); 
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setHeader('Authorization', 'Bearer ' + access_token);
            req.setEndpoint(Label.Billing_Group_Response);
            req.setBody( resp );
            req.setTimeout(120000);
            HttpResponse kafkaResponse ;
            if(System.Test.isRunningTest()){
                kafkaResponse = new HttpResponse();
                kafkaResponse.setStatusCode(200);
            } else {
                kafkaResponse = mHttp.send(req);
            }
            if( kafkaResponse.getStatusCode() != 200 && kafkaResponse.getStatusCode() != 201 ) {
                isFailed = true;
                Body = resp;
            }
        } else {
            isFailed = true;
        }
    }
    
    public void finish(Database.BatchableContext BC){
        System.debug('Body  == '+Body);
        system.debug('====Status ' + isFailed);
        setIntegrationMessageStatus((!isFailed) ? 'Success' : 'Failed');
    }

    private void setIntegrationMessageStatus(String status) {
        Integration_Message__c objMessage = new Integration_Message__c();
        objMessage.Integration_Status__c = status;
        objMessage.Unique_Key__c = requestId;
        upsert objMessage Unique_Key__c;  
    }

    /*public class BillingGrpSOFResponse {
        public String requestId;
        public String sofnumber;
        public String lineitemnumber;
        public Set<String> sof_list;
    }*/

    public class BGResponseWrapper {
        public String requestId;
        public String billing_group_id;
        public List<SOFDetailsWrapper> sofdetails;
    }

    public class SOFDetailsWrapper {
        public String sof_no;
        public List<LineItemDetails> line_items;
    }

    public class LineItemDetails {
        public String line_no;
        public String line_state;
    }
}